// resources/js/Features/PageBuilder/Templates/AgroTemplate.js
import { node, container } from './helpers';

export const AGRO_TEMPLATE = {
    ROOT: container({ bgColor: '#fdfbf7', bgType: 'color', gap: 0, paddingTop: 0, paddingBottom: 0 }, [
        'hero-agro', 'product-agro', 'features-agro',
        'countdown-agro', 'testimonials-agro', 'faq-agro', 'checkout-agro',
    ]),

    'hero-agro': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#fdfbf7', 
            bgGradientTo: '#ecfdf5',   
            bgGradientDirection: 145,
            minHeight: 600,
            paddingTop: 110, paddingBottom: 110, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center', contentMaxWidth: 860, contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '🌿 ১০০% প্রাকৃতিক ও খাঁটি',
            badgeColor: '#166534', badgeBgColor: '#dcfce7',
            title: 'বিসমিল্লাহ বাজারের খাঁটি\nসুন্দরবনের প্রাকৃতিক মধু',
            titleSize: 60, titleWeight: '800', titleColor: '#064e3b',
            titleLineHeight: 1.15, titleLetterSpacing: 0,
            fontFamily: "'Hind Siliguri', sans-serif",
            subtitle: 'কোনো প্রকার প্রসেসিং বা ভেজাল ছাড়াই সরাসরি মৌয়ালদের থেকে সংগৃহীত। আপনার পরিবারের সুস্বাস্থ্যের জন্য প্রকৃতির আসল উপহার।',
            subtitleSize: 18, subtitleColor: '#4b5563', subtitleMaxWidth: 650, subtitleLineHeight: 1.7,
            showPrimaryBtn: true,
            primaryBtnText: '🛒 অর্ডার করুন — ক্যাশ অন ডেলিভারি',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#166534', primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#166534', primaryBtnBorderRadius: 8, primaryBtnSize: 'lg',
            showSecondaryBtn: false,
            showStats: true,
            stats: [
                { value: '১০,০০০+', label: 'সন্তুষ্ট গ্রাহক', show: true },
                { value: 'BSTI', label: 'অনুমোদিত মান', show: true },
                { value: '১০০%', label: 'খাঁটি গ্যারান্টি', show: true },
            ],
            decorShape: 'blob-tr', decorColor: '#f59e0b', decorOpacity: 20,
            animation: 'slideUp', animationDelay: '0',
        }),
    },

    'product-agro': {
        ...node('ProductWidget', {
            layout: 'side-by-side', maxWidth: 1060,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            imageRatio: '1:1', imageBorderRadius: 16, imageShadow: 'lg',
            fontFamily: "'Hind Siliguri', sans-serif",
            showGallery: true,
            showBadge: true, badgeText: 'Best Seller', badgeBg: '#166534', badgeColor: '#ffffff',
            showTitle: true, titleSize: 34, titleWeight: '800', titleColor: '#064e3b', titleLineHeight: 1.25,
            showPrice: true, priceColor: '#166534', priceSize: 38, priceWeight: '800',
            showOriginalPrice: true, showDiscountBadge: true, currencySymbol: '৳',
            showRating: true, ratingValue: 4.9, reviewCount: 1250, starColor: '#f59e0b',
            showDescription: true, descriptionSize: 16, descriptionColor: '#4b5563', descriptionLines: 4,
            showSpecs: true,
            specs: [
                { icon: '🍯', label: 'উৎস', value: 'সুন্দরবনের গহীন অরণ্য', show: true },
                { icon: '⚖️', label: 'পরিমাণ', value: '১ কেজি / ৫০০ গ্রাম', show: true },
                { icon: '🧪', label: 'টেস্ট', value: 'ল্যাব টেস্টেড ও সার্টিফাইড', show: true },
                { icon: '📦', label: 'প্যাকেজিং', value: 'নিরাপ নিরাপদ ফুড-গ্রেড জার', show: true },
            ],
            showTrust: true,
            trustItems: [
                { icon: '✅', text: 'ভেজাল প্রমাণে টাকা ফেরত', bg: '#f0fdf4', color: '#166534', show: true },
                { icon: '🚚', text: 'সারা দেশে হোম ডেলিভারি', bg: '#fffbeb', color: '#d97706', show: true },
            ],
            showStock: true, stockText: '🔥 এই লটের মাত্র কয়েক জার অবশিষ্ট আছে!',
            stockBg: '#fef2f2', stockColor: '#dc2626',
            showCta: true,
            ctaText: '🍯 এখনই অর্ডার করুন',
            ctaUrl: '#checkout', ctaBg: '#166534', ctaTextColor: '#ffffff',
            ctaRadius: 8, ctaSize: 'lg',
            ctaSubText: 'অগ্রিম পেমেন্ট নেই • পণ্য হাতে পেয়ে টাকা দিন',
            animation: 'fadeUp',
        }),
    },

    'features-agro': {
        ...node('FeaturesWidget', {
            sectionTitle: 'কেন আমাদের পণ্যটি সেরা?',
            sectionSubtitle: 'আমরা স্বাস্থ্যের সাথে কোনো আপোষ করি জৈন। সরাসরি প্রকৃতি থেকে আপনার টেবিলে।',
            titleColor: '#064e3b', subtitleColor: '#4b5563',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            fontFamily: "'Hind Siliguri', sans-serif",
            columns: 3, layout: 'vertical', gap: 24,
            bgType: 'color', bgColor: '#f0fdf4', 
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#bbf7d0', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'sm', cardPadding: 32,
            iconShape: 'circle', iconBg: '#dcfce7', iconColor: '#166534', iconSize: 'lg',
            itemTitleColor: '#064e3b', itemDescColor: '#4b5563',
            itemTitleSize: 18, itemDescSize: 15,
            showNumbers: false,
            items: [
                { title: '১০০% খাঁটি ও প্রাকৃতিক', description: 'কোনো প্রকার আর্টিফিশিয়াল কালার, ফ্লেভার বা প্রিজারভেটিভ ব্যবহার করা হয় না।', icon: '🌿', iconBg: '', iconColor: '' },
                { title: 'সরাসরি সংগ্রহ', description: 'মাঝখানে কোনো দালাল নেই। সরাসরি প্রান্তিক চাষি ও মৌয়ালদের থেকে সংগৃহীত।', icon: '👨‍🌾', iconBg: '', iconColor: '' },
                { title: 'ল্যাব টেস্টেড', description: 'প্রতিটি লট প্যাকেজিংয়ের আগে অত্যাধুনিক ল্যাবে পরীক্ষা করে মান নিশ্চিত করা হয়।', icon: '🔬', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'countdown-agro': {
        ...node('CountdownWidget', {
            mode: 'evergreen', durationHours: 24,
            showDays: false,
            fontFamily: "'Hind Siliguri', sans-serif",
            showHeadline: true,
            headline: '⏳ স্পেশাল ডিসকাউন্ট শেষ হতে আর মাত্র কয়েক ঘণ্টা!',
            headlineSize: 26, headlineColor: '#064e3b', headlineWeight: '800',
            showSubtitle: true,
            subtitle: 'স্টক শেষ হওয়ার আগেই আপনার পরিবারের জন্য খাঁটি পণ্যটি নিশ্চিত করুন।',
            subtitleColor: '#4b5563', subtitleSize: 16,
            expiredMessage: '⚠️ অফারটি শেষ হয়ে গেছে।',
            displayStyle: 'card', boxSize: 'md',
            boxBg: '#ffffff', boxTextColor: '#064e3b',
            labelColor: '#4b5563', boxRadius: 8, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '🔥 ২ কেজি অর্ডারে পাচ্ছেন ফ্রি ডেলিভারি!',
            urgencyBarBg: '#fef3c7', urgencyBarText: '#d97706',
            bgType: 'gradient', bgGradientFrom: '#ecfdf5', bgGradientTo: '#fdfbf7', bgGradientDirection: 180,
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
        }),
    },

    'testimonials-agro': {
        ...node('TestimonialWidget', {
            title: 'গ্রাহকদের সন্তুষ্টিই আমাদের অর্জন',
            subtitle: 'যারা আমাদের পণ্য ব্যবহার করেছেন, তাদের বাস্তব অভিজ্ঞতা।',
            bgColor: '#fdfbf7', padding: 80,
            fontFamily: "'Hind Siliguri', sans-serif",
            layout: 'grid', cardStyle: 'shadow',
            starColor: '#f59e0b', showVerified: true,
            reviews: [
                { name: 'আরিফুর রহমান', role: 'ঢাকা', text: 'মধুটা হাতে পেয়েই ঘ্রাণ শুনে বুঝেছি এটা আসল। এখন থেকে নিয়মিত এখান থেকেই নেব ইনশাআল্লাহ।', stars: 5, avatar: '' },
                { name: 'নাসরিন সুলতানা', role: 'চট্টগ্রাম', text: 'বাচ্চাদের জন্য খাঁটি মধু খুঁজছিলাম অনেক দিন। আপনাদের প্রোডাক্ট সত্যিই অসাধারণ। প্যাকেজিংও খুব ভালো ছিল।', stars: 5, avatar: '' },
                { name: 'জুবায়ের হোসাইন', role: 'সিলেট', text: 'ডেলিভারি খুব ফাস্ট ছিল। আর মধুর স্বাদ একদম গ্রামের বাড়ির মতো। ধন্যবাদ আপনাদের।', stars: 5, avatar: '' },
            ],
        }),
    },

    'faq-agro': {
        ...node('FaqWidget', {
            title: 'সাধারণ জিজ্ঞাসা (FAQ)',
            subtitle: 'অর্ডার করার আগে আপনার মনের কনফিউশন দূর করুন।',
            bgColor: '#f0fdf4', padding: 80,
            fontFamily: "'Hind Siliguri', sans-serif",
            accentColor: '#166534', iconStyle: 'plus', layout: 'default',
            questions: [
                { q: 'মধু জমে গেলে কি নকল?', a: 'না, খাঁটি মধু জমে যাওয়া একটি স্বাভাবিক প্রক্রিয়া, বিশেষ করে শীতকালে। রোদে বা হালকা গরম পানিতে রাখলে আবার স্বাভাবিক হয়ে যাবে।' },
                { q: 'পণ্য পছন্দ না হলে কি রিটার্ন করা যাবে?', a: 'অবশ্যই। ডেলিভারি ম্যানের সামনে চেক করে যদি মনে হয় ভেজাল আছে, তবে সাথে সাথে রিটার্ন করতে পারবেন।' },
                { q: 'ডেলিভারি চার্জ কত?', a: 'ঢাকায় ডেলিভারি চার্জ ৬০ টাকা, ঢাকার বাইরে ১২০ টাকা। তবে ২ কেজির বেশি অর্ডারে ডেলিভারি ফ্রি!' },
            ],
        }),
    },

    'checkout-agro': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 32, borderRadius: 12,
            shadow: 'md', borderWidth: 1, borderColor: '#bbf7d0',
            fontFamily: "'Hind Siliguri', sans-serif",
            showHeader: true, headerText: '🌿 ডেলিভারি এড্রেস দিন',
            headerBgColor: '#f0fdf4', headerTextColor: '#166534', headerSize: 20,
            showProductSummary: true, summaryLayout: 'row',
            showRating: true, ratingValue: 5, reviewCount: 1250,
            showMultiProduct: false,
            showQuantity: true, showAddress: true, showDistrict: true, showNote: true,
            nameLabel: 'আপনার নাম', phoneLabel: 'ফোন নম্বর',
            addressLabel: 'বিস্তারিত ঠিকানা', districtLabel: 'জেলা',
            noteLabel: 'অতিরিক্ত নোট (যদি থাকে)', quantityLabel: 'পরিমাণ',
            formLayout: 'two-col',
            unitLabel: 'কেজি', presetQuantities: '1, 2, 5', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true,
            bundles: [
                { qty: 2, price: 1900 },
                { qty: 5, price: 4500 },
            ],
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার কনফার্ম করুন',
            buttonBgColor: '#166534', buttonTextColor: '#ffffff',
            buttonBorderRadius: 8, buttonSize: 'lg', buttonFullWidth: true,
            buttonIcon: '✅', buttonSubText: 'কোনো অগ্রিম পেমেন্ট করতে হবে না',
            showTrustBadges: true,
            trustBadges: [
                { icon: '🌿', text: '১০০% অর্গানিক', show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি', show: true },
                { icon: '🛡️', text: 'মানি ব্যাক গ্যারান্টি', show: true },
                { icon: '🚚', text: 'ফাস্ট ডেলিভারি', show: true },
            ],
            showUrgency: true, urgencyText: '🔥 দ্রুত অর্ডার করুন, স্টক সীমিত!',
            urgencyBgColor: '#fef2f2', urgencyTextColor: '#dc2626',
            showSocialProof: true,
            socialProofText: 'আজ ইতিমধ্যে ৪৫ জন অর্ডার করেছেন',
            socialProofIcon: '👥',
            enableSpamPrevention: true, spamIntervalMinutes: 30,
            showMobileStickyCta: true,
            mobileStickyText: '🛒 অর্ডার করুন — COD',
            mobileStickyBg: '#ffffff',
            themeColor: '#166534',
            labelColor: '#4b5563', inputBorderColor: '#d1d5db', inputBgColor: '#fdfbf7',
        }),
    },
};