// resources/js/Features/PageBuilder/Templates/AjwaDatesTemplate.js
import { node, container } from './helpers';

export const AJWA_DATES_TEMPLATE = {
    ROOT: container({ bgColor: '#fffdfa', bgType: 'color', gap: 0, paddingTop: 0, paddingBottom: 0 }, [
        'hero-ajwa',          // 1. Hero Section
        'problem-ajwa',       // 2. Problem Section (New)
        'product-ajwa',       // 3. Product Intro
        'breakdown-ajwa',     // 4. Breakdown Section (New)
        'benefits-ajwa',      // 5. Benefits
        'why-us-ajwa',        // Existing Extra
        'testimonials-ajwa',  // 6. Social Proof
        'countdown-ajwa',     // 7. Offer + Urgency (New)
        'checkout-ajwa',      // 8. Checkout
    ]),

    'hero-ajwa': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#fffdfa',
            bgGradientTo: '#fef3c7',
            bgGradientDirection: 145,
            minHeight: 580,
            paddingTop: 100, paddingBottom: 100, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center', contentMaxWidth: 820, contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '🌿 সিজন ফ্রেশ',
            badgeColor: '#b45309', badgeBgColor: '#fef3c7',
            title: 'মদিনার বরকতময়\nআজওয়া খেজুর',
            titleSize: 58, titleWeight: '900', titleColor: '#451a03',
            titleLineHeight: 1.1, titleLetterSpacing: -0.02,
            subtitle: 'সঠিক তাপমাত্রায় সংরক্ষিত ও প্রিজারভেটিভ মুক্ত সম্পূর্ণ ন্যাচারাল আজওয়া খেজুর।',
            subtitleSize: 18, subtitleColor: '#78350f', subtitleMaxWidth: 600, subtitleLineHeight: 1.65,
            showPrimaryBtn: true,
            primaryBtnText: '🛒 অর্ডার করতে ক্লিক করুন',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#b45309', primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#b45309', primaryBtnBorderRadius: 50, primaryBtnSize: 'lg',
            showSecondaryBtn: false,
            showStats: true,
            stats: [
                { value: '৫০,০০০', label: 'গ্রাহক',  show: true },
                { value: '৯৮%',   label: 'পজিটিভ রিভিউ',     show: true },
                { value: '১০০%', label: 'অরিজিনাল', show: true },
                { value: '৭ বছর', label: 'গ্রাহক সেবায়', show: true },
            ],
            decorShape: 'blob-tr', decorColor: '#fde68a', decorOpacity: 30,
            animation: 'slideUp', animationDelay: '0',
        }),
    },

    'problem-ajwa': {
        ...node('FeaturesWidget', {
            sectionTitle: 'বাজারের আজওয়া খেজুর নিয়ে চিন্তিত?',
            sectionSubtitle: 'আমাদের দেশে আসল আজওয়া খেজুর পাওয়া দিন দিন কঠিন হয়ে যাচ্ছে।',
            titleColor: '#dc2626', subtitleColor: '#451a03',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fff1f2',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fecdd3', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fee2e2', iconColor: '#dc2626', iconSize: 'md',
            itemTitleColor: '#451a03', itemDescColor: '#78350f',
            itemTitleSize: 16, itemDescSize: 15,
            showNumbers: false,
            items: [
                { title: 'নকল ও মিক্সড খেজুর', description: 'আজওয়ার নামে কমদামি ও সাধারণ খেজুর মিক্স করে বিক্রি করা হয়।', icon: '❌', iconBg: '', iconColor: '' },
                { title: 'কেমিক্যাল ও প্রিজারভেটিভ', description: 'দীর্ঘদিন ভালো রাখতে ক্ষতিকর রাসায়নিক মেশানো হয়।', icon: '❌', iconBg: '', iconColor: '' },
                { title: 'শুকনো ও পোকা খাওয়া', description: 'সঠিক সংরক্ষণের অভাবে খেজুর শক্ত হয়ে যায় বা পোকা ধরে।', icon: '❌', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    'product-ajwa': {
        ...node('ProductWidget', {
            layout: 'side-by-side', maxWidth: 1000,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            imageRatio: '4:3', imageBorderRadius: 20, imageShadow: 'lg',
            showGallery: true,
            showBadge: true, badgeText: 'সেরা মানের আজওয়া', badgeBg: '#b45309', badgeColor: '#ffffff',
            showTitle: true, titleSize: 34, titleWeight: '800', titleColor: '#451a03', titleLineHeight: 1.25,
            showPrice: true, priceColor: '#b45309', priceSize: 38, priceWeight: '900',
            showOriginalPrice: false, showDiscountBadge: false, currencySymbol: '৳',
            showRating: true, ratingValue: 4.9, reviewCount: 1540, starColor: '#b45309',
            showDescription: true, descriptionSize: 16, descriptionColor: '#78350f', descriptionLines: 5,
            descriptionText: 'রাসুলুল্লাহ (সা.) বলেন, “যে ব্যক্তি প্রতিদিন সকালে সাতটি আজওয়া খেজুর খাবে, সেদিন কোনো বিষ বা জাদু তার ক্ষতি করতে পারবে না।”\n(সহীহ বুখারী)',
            showSpecs: true,
            specs: [
                { icon: '🌴', label: 'উৎস',    value: 'মদিনার বাগান থেকে সংগৃহীত', show: true },
                { icon: '❄️', label: 'সংরক্ষণ', value: 'সঠিক তাপমাত্রায় সংরক্ষিত', show: true },
                { icon: '🚫', label: 'উপাদান', value: 'প্রিজারভেটিভ মুক্ত', show: true },
                { icon: '⚖️', label: 'পরিমাণ', value: '১ কেজি', show: true },
            ],
            showTrust: true,
            trustItems: [
                { icon: '🌿', text: '১০০% অরিজিনাল', bg: '#f0fdf4', color: '#16a34a', show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি', bg: '#fff7ed', color: '#ea580c', show: true },
                { icon: '↩️', text: 'সহজ রিটার্ন পলিসি', bg: '#fef2f2', color: '#dc2626', show: true },
            ],
            showStock: false,
            showCta: true,
            ctaText: '🛒 অর্ডার করতে ক্লিক করুন',
            ctaUrl: '#checkout', ctaBg: '#b45309', ctaTextColor: '#ffffff',
            ctaRadius: 50, ctaSize: 'lg',
            ctaSubText: 'মূল্য ১,৭০০ টাকা প্রতি কেজি',
            animation: 'fadeUp',
        }),
    },

    'breakdown-ajwa': {
        ...node('FeaturesWidget', {
            sectionTitle: 'আমাদের আজওয়া ভিআইপি গ্রেডের বৈশিষ্ট্য',
            sectionSubtitle: 'কেন আমাদের খেজুর প্রিমিয়াম কোয়ালিটির?',
            titleColor: '#451a03', subtitleColor: '#78350f',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fefaf5',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fde68a', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fef3c7', iconColor: '#b45309', iconSize: 'xl',
            itemTitleColor: '#451a03', itemDescColor: '#78350f',
            itemTitleSize: 18, itemDescSize: 14,
            showNumbers: false,
            items: [
                { title: 'বড় ও মাংসল সাইজ', description: 'বাছাইকৃত সবচেয়ে বড় এবং মাংসল সাইজের আজওয়া খেজুর।', icon: '📏', iconBg: '', iconColor: '' },
                { title: 'নরম ও ফ্রেশ টেক্সচার', description: 'শুকনো বা শক্ত নয়, চিবিয়ে খেতে অত্যন্ত মোলায়েম ও ফ্রেশ।', icon: '🌿', iconBg: '', iconColor: '' },
                { title: 'পরিমিত প্রাকৃতিক মিষ্টি', description: 'অরিজিনাল আজওয়ার বৈশিষ্ট্য অনুযায়ী হালকা ও পরিমিত মিষ্টি।', icon: '🍯', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    'benefits-ajwa': {
        ...node('FeaturesWidget', {
            sectionTitle: 'আজওয়া খেজুরের উপকারিতা',
            sectionSubtitle: 'নিয়মিত আজওয়া খেজুর খাওয়ার স্বাস্থ্যগত গুণাগুণ',
            titleColor: '#451a03', subtitleColor: '#78350f',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fffdfa',
            paddingTop: 80, paddingBottom: 40, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fef3c7', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 28,
            iconShape: 'circle', iconBg: '#fef3c7', iconColor: '#b45309', iconSize: 'md',
            itemTitleColor: '#451a03', itemDescColor: '#78350f',
            itemTitleSize: 16, itemDescSize: 14,
            showNumbers: false,
            items: [
                { title: 'হৃদরোগের ঝুঁকি কমায়', description: 'হার্ট সুস্থ রাখতে কার্যকরী সাহায্য করে।', icon: '❤️', iconBg: '', iconColor: '' },
                { title: 'রোগ প্রতিরোধ ক্ষমতা বাড়ায়', description: 'শরীরের ইমিউন সিস্টেমকে শক্তিশালী করে।', icon: '🛡️', iconBg: '', iconColor: '' },
                { title: 'হজমশক্তি বৃদ্ধি', description: 'হজমশক্তি বাড়ায় ও কোষ্ঠকাঠিন্য দূর করে।', icon: '⚡', iconBg: '', iconColor: '' },
                { title: 'লিভার ও ক্যানসার প্রতিরোধে', description: 'মারাত্মক রোগ প্রতিরোধে সাহায্য করে।', icon: '🩺', iconBg: '', iconColor: '' },
                { title: 'হাড় ও দাঁত মজবুত করে', description: 'ক্যালসিয়ামের অভাব পূরণে সহায়ক।', icon: '🦴', iconBg: '', iconColor: '' },
                { title: 'মা ও শিশুর স্বাস্থ্য রক্ষায়', description: 'গর্ভবতী মা ও শিশুর স্বাস্থ্য সুরক্ষায় ভূমিকা রাখে।', icon: '👩‍👧', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    'why-us-ajwa': {
        ...node('FeaturesWidget', {
            sectionTitle: 'আমাদের থেকেই কেন কিনবেন?',
            sectionSubtitle: 'আমাদের পণ্যের মান ও সেবার নিশ্চয়তা',
            titleColor: '#451a03', subtitleColor: '#78350f',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            columns: 2, layout: 'horizontal', gap: 20,
            bgType: 'color', bgColor: '#fefaf5',
            paddingTop: 40, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fef3c7', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 28,
            iconShape: 'circle', iconBg: '#fef3c7', iconColor: '#b45309', iconSize: 'md',
            itemTitleColor: '#451a03', itemDescColor: '#78350f',
            itemTitleSize: 16, itemDescSize: 14,
            showNumbers: true,
            items: [
                { title: '১০০% অরিজিনাল', description: 'মদিনার বাগান থেকে সংগৃহীত ১০০% অরিজিনাল আজওয়া খেজুর।', icon: '🌴', iconBg: '', iconColor: '' },
                { title: 'সঠিক সংরক্ষণ', description: 'সঠিক তাপমাত্রায় সংরক্ষিত, ফলে মান সবসময় বজায় থাকে।', icon: '❄️', iconBg: '', iconColor: '' },
                { title: 'সম্পূর্ণ ন্যাচারাল', description: 'কোনো কৃত্রিম মিষ্টি বা প্রিজারভেটিভ ছাড়াই সম্পূর্ণ ন্যাচারাল।', icon: '🌿', iconBg: '', iconColor: '' },
                { title: 'গ্রাহকের আস্থা', description: '৭ বছরে বেশি সময় ধরে লক্ষাধিক কাস্টমারের আস্থা।', icon: '🤝', iconBg: '', iconColor: '' },
                { title: 'সহজ পলিসি', description: 'সহজ রিটার্ন, রিফান্ড এবং এক্সচেঞ্জ পলিসি।', icon: '↩️', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    'testimonials-ajwa': {
        ...node('TestimonialWidget', {
            title: 'আমাদের সন্তুষ্ট গ্রাহকদের মতামত',
            subtitle: 'যাঁরা আমাদের আজওয়া খেজুর কিনেছেন তাঁদের অভিজ্ঞতা।',
            bgColor: '#ffffff', padding: 60,
            layout: '2col', cardStyle: 'shadow',
            starColor: '#b45309', showVerified: true,
            reviews: [
                { name: 'মোহাম্মদ সাইফুল ইসলাম', role: 'চট্টগ্রাম', text: 'আমি এই নিয়ে ৩ বার অর্ডার করলাম। খেজুরগুলো খুবই সুস্বাদু এবং কোয়ালিটি অসাধারণ। হারামাইন স্টোর আরব থেকে খেজুর আমদানি করে—এটা নিশ্চিতভাবে বলতে পারি। আমরা যারা মক্কা-মদিনায় উমরাহ করেছি, তারা জানি সুক্কারী খেজুর কতটা পরিচিত ও স্বাদে অনন্য। এই খেজুর খাওয়ার সময় আরবের অনুভূতি চলে আসে। আল্লাহ তায়ালা ব্যবসায় আরও বরকত দান করুন—এই দোয়া করি।', stars: 5, avatar: '' },
                { name: 'আব্দুল্লাহ আল মামুন', role: 'সিলেট', text: 'আচ্ছালামু আলাইকুম। আপনাদের কাছ থেকে নেওয়া খেজুরটি আজ খেয়ে দেখলাম—আলহামদুলিল্লাহ, মান ও স্বাদে মুগ্ধ হয়েছি। আগে অন্য কয়েকটি পেজ থেকে সুক্কারী, মেজদুল ও আজওয়া খেজুর কিনেছিলাম, কিন্তু হারামাইন স্টোরের খেজুর খাওয়ার পর পার্থক্য স্পষ্ট বুঝেছি। দাম হয়তো কিছুটা বেশি, কিন্তু কোয়ালিটি ও বিশ্বাসযোগ্যতার জন্য আমি সবসময় হারামাইন স্টোর থেকেই খেজুর অর্ডার করবো।', stars: 5, avatar: '' },
            ],
        }),
    },

    'countdown-ajwa': {
        ...node('CountdownWidget', {
            mode: 'daily',
            showDays: false,
            showHeadline: true,
            headline: '🎁 আজকের স্পেশাল অফার!',
            headlineSize: 28, headlineColor: '#dc2626', headlineWeight: '800',
            showSubtitle: true,
            subtitle: 'আসল আজওয়া খেজুরের এই অফার মিস করবেন না!',
            subtitleColor: '#451a03', subtitleSize: 18,
            expiredMessage: '⚠️ আজকের অফারটি শেষ হয়েছে।',
            displayStyle: 'card', boxSize: 'md',
            boxBg: '#ffffff', boxTextColor: '#b45309',
            labelColor: '#78350f', boxRadius: 16, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '📦 স্টক খুব দ্রুত শেষ হয়ে যাচ্ছে।',
            urgencyBarBg: '#fee2e2', urgencyBarText: '#dc2626',
            bgType: 'color', bgColor: '#fffdfa',
            paddingTop: 40, paddingBottom: 40, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
        }),
    },

    'checkout-ajwa': {
        ...node('CheckoutWidget', {
            maxWidth: 560, bgColor: '#ffffff', padding: 32, borderRadius: 20,
            shadow: 'md', borderWidth: 1, borderColor: '#fde68a',
            showHeader: true, headerText: '🛒 অর্ডার করুন',
            headerBgColor: '#fef3c7', headerTextColor: '#b45309', headerSize: 20,
            showProductSummary: true, summaryLayout: 'row',
            showRating: true, ratingValue: 5, reviewCount: 1540,
            showMultiProduct: false,
            showQuantity: true, showAddress: true, showDistrict: true, showNote: true,
            nameLabel: 'আপনার নাম', phoneLabel: 'ফোন নম্বর',
            addressLabel: 'ডেলিভারি ঠিকানা', districtLabel: 'জেলা',
            noteLabel: 'বিশেষ নির্দেশ', quantityLabel: 'পরিমাণ (কেজি)',
            formLayout: 'two-col',
            unitLabel: 'কেজি', presetQuantities: '1, 2, 3, 5', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true,
            bundles: [
                { qty: 1, price: 1700 },
                { qty: 2, price: 3400 },
                { qty: 5, price: 8500 },
            ],
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার করতে ক্লিক করুন',
            buttonBgColor: '#b45309', buttonTextColor: '#ffffff',
            buttonBorderRadius: 50, buttonSize: 'lg', buttonFullWidth: true,
            buttonIcon: '🛒', buttonSubText: 'ক্যাশ অন ডেলিভারিতে অর্ডার করুন',
            showTrustBadges: true,
            trustBadges: [
                { icon: '🌿', text: '১০০% অরিজিনাল',         show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি',   show: true },
                { icon: '↩️', text: 'সহজ রিটার্ন',    show: true },
            ],
            showUrgency: false,
            showSocialProof: true,
            socialProofText: 'গত ১ ঘণ্টায় অনেকে অর্ডার করেছেন',
            socialProofIcon: '🔥',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true,
            mobileStickyText: '🛒 অর্ডার করুন (১,৭০০ ৳)',
            mobileStickyBg: '#ffffff',
            themeColor: '#b45309',
            labelColor: '#78350f', inputBorderColor: '#fde68a', inputBgColor: '#fffdfa',
        }),
    },
};