// resources/js/Features/PageBuilder/Templates/AlAdabulMufradTemplate.js
import { node, container } from './helpers';

export const AL_ADABUL_MUFRAD_TEMPLATE = {
    ROOT: container({ 
        bgColor: '#f8fafc', 
        bgType: 'color', 
        gap: 0, 
        paddingTop: 0, 
        paddingBottom: 0 
    }, [
        'hero-adab', 
        'product-adab', 
        'reflection-adab',
        'content-adab',
        'why-buy-adab',
        'testimonials-adab',
        'checkout-adab',
    ]),

    'hero-adab': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#1e3a8a', // Royal Blue (Matched from cover)
            bgGradientTo: '#172554',   // Deep Navy Blue
            bgGradientDirection: 180,
            bgImage: '',
            overlayColor: '#000000',
            overlayOpacity: 20,
            minHeight: 650,
            paddingTop: 120,
            paddingBottom: 100,
            paddingLeft: 24,
            paddingRight: 24,
            contentAlign: 'center',
            contentMaxWidth: 900,
            contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '🌿 আদর্শ জীবন ও সুন্দর চরিত্র গঠনের গাইডলাইন',
            badgeColor: '#1e3a8a',
            badgeBgColor: '#fef08a', // Gold badge
            title: 'আল-আদাবুল মুফরাদ\nশিষ্টাচার ও সুন্নাহর অমূল্য ভাণ্ডার',
            titleSize: 52,
            titleWeight: '900',
            titleColor: '#ffffff',
            titleLineHeight: 1.2,
            titleLetterSpacing: -0.02,
            subtitle: '⚖️ কিয়ামতের দিন মীযানের পাল্লায় সবচেয়ে ভারি আমল কী জানেন? নবী ﷺ বলেছেন— "কিয়ামতের দিন মুমিনের আমলের পাল্লায় সবচেয়ে ভারি হবে তার উত্তম চরিত্র।"',
            subtitleSize: 20,
            subtitleColor: '#dbeafe',
            subtitleMaxWidth: 750,
            subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '📖 বইটি সংগ্রহ করুন',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#eab308', // Gold Button (Matched from cover text)
            primaryBtnTextColor: '#1e3a8a', // Blue text on Gold button
            primaryBtnBorderColor: '#eab308',
            primaryBtnBorderRadius: 8,
            primaryBtnSize: 'xl',
            showSecondaryBtn: true,
            secondaryBtnText: 'বইটিতে কী আছে দেখুন',
            secondaryBtnUrl: '#content',
            secondaryBtnStyle: 'outline',
            secondaryBtnBgColor: 'transparent',
            secondaryBtnTextColor: '#ffffff',
            secondaryBtnBorderColor: '#ffffff',
            secondaryBtnBorderRadius: 8,
            secondaryBtnSize: 'xl',
            showStats: false,
            decorShape: 'dots',
            decorColor: '#ffffff',
            decorOpacity: 10,
            animation: 'slideUp',
            animationDelay: '0',
        }),
    },

    'product-adab': {
        ...node('BookWidget', {
            showTitle: true, showGallery: true, showDescription: true,
            showMeta: true, showWriter: true, showPublication: false,
            showPages: true, showLanguage: true,
            showPrice: true, showRating: true, showCta: true,
            titleOverride: 'আল‑আদাবুল মুফরাদ (হার্ডকভার)',
            writerName: 'ইমাম মুহাম্মদ ইবনে ইসমাইল আল‑বুখারী (রহ.)',
            publicationName: '',
            totalPages: '৫০০+',
            language: 'বাংলা অনুবাদ',
            descriptionOverride: 'এই অমূল্য গ্রন্থটি সংকলন করেছেন মহান মুহাদ্দিস ইমাম বুখারী (রহ.)। এটি শুধু একটি হাদিস গ্রন্থ নয়— বরং একটি সুন্দর পরিবার ও আদর্শ সমাজ গড়ার বাস্তব নির্দেশিকা। যে ব্যক্তি নিজের ও পরিবারের চরিত্রকে নবী ﷺ-এর সুন্নাহ অনুযায়ী সুন্দর করতে চান, তার ঘরে বইটি অবশ্যই থাকা উচিত।',
            shortDescLength: 350,
            ratingValue: 5.0,
            reviewCount: 850,
            starColor: '#eab308',
            currencySymbol: '৳',
            layout: 'row',
            maxWidth: 1060,
            metaStyle: 'grid', 
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            imageBorderRadius: 12, imageShadow: '2xl',
            titleSize: 36, titleWeight: '800', titleColor: '#1e3a8a',
            metaLabelColor: '#64748b', metaValueColor: '#0f172a',
            descColor: '#334155', descSize: 16, descLineHeight: 1.8,
            priceColor: '#b45309', priceSize: 42,
            ctaText: '🛒 ক্যাশ অন ডেলিভারিতে অর্ডার করুন',
            ctaUrl: '#checkout',
            ctaBg: '#1e3a8a', ctaTextColor: '#ffffff', ctaRadius: 8,
            ctaFullWidth: true,
        }),
    },

    'reflection-adab': {
        ...node('FeaturesWidget', {
            sectionTitle: 'একটু ভেবে দেখুন—',
            sectionSubtitle: 'ইবাদত যতই হোক, আখলাক বা চরিত্র সুন্দর না হলে কিয়ামতের দিন সফল হওয়া কঠিন।',
            titleColor: '#1e3a8a', subtitleColor: '#b45309',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 2, layout: 'horizontal', gap: 24,
            bgType: 'color', bgColor: '#eff6ff', // Soft light blue
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#dbeafe', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'sm', cardPadding: 30,
            iconShape: 'circle', iconBg: '#fefce8', iconColor: '#eab308', iconSize: 'lg',
            itemTitleColor: '#172554', itemDescColor: '#475569',
            itemTitleSize: 18, itemDescSize: 15, itemDescLineHeight: 1.6,
            showNumbers: false,
            items: [
                { title: 'সামান্য কথায় কি আমরা রেগে যাই?', description: 'আমরা অনেকেই নামাজ পড়ি, রোজা রাখি, কিন্তু রাগ নিয়ন্ত্রণ করতে পারি না।', icon: '🤔', iconBg: '', iconColor: '' },
                { title: 'পরিবারের সাথে আচরণ কেমন?', description: 'স্ত্রী বা সন্তানের সাথে আমরা কি সুন্নাহ অনুযায়ী কোমল আচরণ করছি?', icon: '🏡', iconBg: '', iconColor: '' },
                { title: 'আত্মীয়দের সাথে সম্পর্ক কেমন?', description: 'পিতা-মাতা ও আত্মীয়দের সাথে আমাদের আচরণ কি সত্যিই সুন্দর?', icon: '👨‍👩‍👦', iconBg: '', iconColor: '' },
                { title: 'প্রতিবেশীর হক আদায় হচ্ছে তো?', description: 'আমাদের কথা বা কাজে প্রতিবেশী কষ্ট পাচ্ছে না তো?', icon: '🤝', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'content-adab': {
        ...node('FeaturesWidget', {
            sectionTitle: '📘 ‘আল-আদাবুল মুফরাদ’ বইটিতে কী আছে?',
            sectionSubtitle: 'আপনার দৈনন্দিন জীবনে সুন্দর শিষ্টাচার গঠনের এক অনন্য নির্দেশিকা।',
            titleColor: '#1e3a8a', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 32,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#f8fafc', cardBorderColor: '#e2e8f0', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'none', cardPadding: 40,
            iconShape: 'soft-square', iconBg: '#dbeafe', iconColor: '#1e3a8a', iconSize: 'xl',
            itemTitleColor: '#172554', itemDescColor: '#475569',
            itemTitleSize: 18, itemDescSize: 15, itemDescLineHeight: 1.6,
            showNumbers: false,
            items: [
                { title: 'পিতা-মাতা ও আত্মীয়দের হক', description: 'পিতা-মাতা ও আত্মীয়-স্বজনের সাথে আচরণের সঠিক দিকনির্দেশনা।', icon: '🤲', iconBg: '', iconColor: '' },
                { title: 'প্রতিবেশী ও মেহমানের অধিকার', description: 'প্রতিবেশী, এতিম ও মেহমানের অধিকার কীভাবে আদায় করবেন তার বিবরণ।', icon: '🍽️', iconBg: '', iconColor: '' },
                { title: 'সালাম ও শিষ্টাচার', description: 'সালামের সঠিক আদব ও মানুষের সাথে কথা বলার ইসলামী শিষ্টাচার।', icon: '💬', iconBg: '', iconColor: '' },
                { title: 'রাগ নিয়ন্ত্রণের পদ্ধতি', description: 'অতিরিক্ত রাগ নিয়ন্ত্রণের নববী পদ্ধতি ও এর সুফল।', icon: '🌿', iconBg: '', iconColor: '' },
                { title: 'দৈনন্দিন জীবনের সুন্নাহ', description: 'প্রতিদিনের জীবনের শত শত সুন্নাহ ও আদব যা আমাদের অজানা।', icon: '✨', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'why-buy-adab': {
        ...node('FeaturesWidget', {
            sectionTitle: '🌙 কেন এই বইটি আপনার ঘরে থাকা উচিত?',
            sectionSubtitle: 'নিজের জন্য এবং প্রিয়জনের জন্য সেরা একটি উপহার।',
            titleColor: '#1e3a8a', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 2, layout: 'horizontal', gap: 24,
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 60, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#e2e8f0', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#dbeafe', iconColor: '#1e3a8a', iconSize: 'md',
            itemTitleColor: '#172554', itemDescColor: '#475569',
            itemTitleSize: 18, itemDescSize: 15, itemDescLineHeight: 1.5,
            showNumbers: false,
            items: [
                { title: 'নিজের চরিত্র গঠন', description: 'নিজের আখলাক ও চরিত্রকে সুন্নাহ অনুযায়ী গড়ে তুলতে সাহায্য করবে।', icon: '✅', iconBg: '', iconColor: '' },
                { title: 'পারিবারিক পরিবেশ', description: 'পরিবারে একটি সুন্দর ও শান্তিপূর্ণ ইসলামী পরিবেশ তৈরি করতে।', icon: '✅', iconBg: '', iconColor: '' },
                { title: 'সন্তানদের তরবিয়ত', description: 'সন্তানদের সঠিক আদব ও আখলাক শেখানোর জন্য সেরা গাইড।', icon: '✅', iconBg: '', iconColor: '' },
                { title: 'আদর্শ সমাজ গঠন', description: 'আশপাশের মানুষের সাথে সদ্ব্যবহারের মাধ্যমে সুন্দর সমাজ গঠনে ভূমিকা রাখতে।', icon: '✅', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'testimonials-adab': {
        ...node('TestimonialWidget', {
            title: 'পাঠকদের অনুভূতি',
            subtitle: 'বইটি পড়ার পর পাঠকদের জীবনের কিছু সুন্দর পরিবর্তন।',
            bgColor: '#eff6ff', padding: 80,
            layout: 'grid', columns: 3, cardStyle: 'modern',
            starColor: '#eab308', showVerified: true,
            cardRadius: 16, cardShadow: 'sm',
            reviews: [
                { name: 'শরিফুল ইসলাম', role: 'ব্যবসায়ী', text: 'বইটি পড়ার পর বুঝতে পেরেছি নিজের আচরণের কোথায় কোথায় ভুল ছিল। বিশেষ করে রাগ নিয়ন্ত্রণের হাদিসগুলো আমার খুব উপকারে এসেছে।', stars: 5, avatar: '' },
                { name: 'আয়েশা সিদ্দিকা', role: 'গৃহিণী', text: 'পরিবারের সবার সাথে কেমন আচরণ করতে হবে তার এত সুন্দর বর্ণনা অন্য কোথাও পাইনি। সন্তানদের আদব শেখানোর জন্য বইটি প্রতিদিন একটু একটু করে পড়ি।', stars: 5, avatar: '' },
                { name: 'মাহমুদ হাসান', role: 'শিক্ষক', text: 'বাবা-মাকে উপহার দিয়েছিলাম। উনারা খুবই খুশি হয়েছেন। প্রতিটি মুসলিমের ঘরে অন্তত একবার হলেও বইটি পড়া উচিত।', stars: 5, avatar: '' },
            ],
        }),
    },

    'checkout-adab': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 40, borderRadius: 16,
            shadow: '2xl', borderWidth: 1, borderColor: '#e2e8f0',
            showHeader: true, headerText: '📚 বইটি আজই সংগ্রহ করুন',
            headerBgColor: '#eff6ff', headerTextColor: '#1e3a8a', headerSize: 22,
            showProductSummary: true, summaryLayout: 'card', 
            showRating: true, ratingValue: 5, reviewCount: 850,
            showMultiProduct: false, multiProductLabel: '',
            showQuantity: true, showAddress: true, showDistrict: true, showNote: true,
            nameLabel: 'আপনার নাম', phoneLabel: 'মোবাইল নাম্বার',
            addressLabel: 'সম্পূর্ণ ঠিকানা', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'অতিরিক্ত নির্দেশনা (যদি থাকে)', quantityLabel: 'কপি সংখ্যা',
            formLayout: 'two-col',
            unitLabel: 'কপি', presetQuantities: '1, 2, 5', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true, 
            bundles: [
                { qty: 2, discountText: 'প্রিয়জনকে উপহার দিন (ডেলিভারি ফ্রি)' },
            ],
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার কনফার্ম করুন — ক্যাশ অন ডেলিভারি',
            buttonBgColor: '#1e3a8a', buttonTextColor: '#ffffff',
            buttonBorderRadius: 8, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '🚀', buttonSubText: 'নিজের আখেরাত ও পরিবারের জন্য সেরা বিনিয়োগ',
            showTrustBadges: true,
            trustBadges: [
                { icon: '📦', text: 'ক্যাশ অন ডেলিভারি', show: true },
                { icon: '🚚', text: 'সারা দেশে হোম ডেলিভারি', show: true },
                { icon: '💯', text: 'অরিজিনাল প্রিন্ট', show: true },
            ],
            showUrgency: false, 
            showSocialProof: true,
            socialProofText: 'এই সপ্তাহে ১২৪ জন বইটি অর্ডার করেছেন',
            socialProofIcon: '🌟',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true, 
            mobileStickyText: '📖 অর্ডার করুন',
            mobileStickyBg: '#ffffff',
            themeColor: '#1e3a8a',
            labelColor: '#334155', inputBorderColor: '#cbd5e1', inputBgColor: '#f8fafc', inputRadius: 8,
        }),
    },
};