// resources/js/Features/PageBuilder/Templates/BookTemplate.js
import { node, container } from './helpers';

export const BOOK_TEMPLATE = {
    ROOT: container({ 
        bgColor: '#fcfbf9', // Slightly warmer, premium white
        bgType: 'color', 
        gap: 0, 
        paddingTop: 0, 
        paddingBottom: 0 
    }, [
        'hero-book', 
        'product-book', 
        'features-book', 
        'video-book', // Added a video section for modern storytelling
        'testimonials-book',
        'countdown-book', 
        'faq-book', 
        'checkout-book',
    ]),

    'hero-book': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#fcfbf9',
            bgGradientTo: '#f4f0e6',
            bgGradientDirection: 180,
            bgImage: '',
            overlayColor: '#ffffff',
            overlayOpacity: 0,
            minHeight: 600,
            paddingTop: 120,
            paddingBottom: 100,
            paddingLeft: 24,
            paddingRight: 24,
            contentAlign: 'center',
            contentMaxWidth: 900,
            contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '🏆 Best Seller 2025 — Limited Edition',
            badgeColor: '#9a3412',
            badgeBgColor: '#ffedd5',
            title: 'The Book That Will Change\nHow You See Everything',
            titleSize: 64,
            titleWeight: '900',
            titleColor: '#1c1917',
            titleLineHeight: 1.1,
            titleLetterSpacing: -0.03,
            subtitle: 'A masterpiece of storytelling that has sold over 500,000 copies across South Asia. Readers call it "life-changing" — grab your copy before the current print run sells out.',
            subtitleSize: 20,
            subtitleColor: '#44403c',
            subtitleMaxWidth: 680,
            subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '📖 Order Now — Cash on Delivery',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#b45309',
            primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#b45309',
            primaryBtnBorderRadius: 8, // Modern rounded corners
            primaryBtnSize: 'xl',
            showSecondaryBtn: true,
            secondaryBtnText: 'Read an Excerpt',
            secondaryBtnUrl: '#features',
            secondaryBtnStyle: 'outline',
            secondaryBtnBgColor: 'transparent',
            secondaryBtnTextColor: '#b45309',
            secondaryBtnBorderColor: '#b45309',
            secondaryBtnBorderRadius: 8,
            secondaryBtnSize: 'xl',
            showStats: true,
            stats: [
                { value: '5,00,000+', label: 'Copies Sold', show: true },
                { value: '4.9/5 ★',    label: 'Reader Rating', show: true },
                { value: 'National', label: 'Award Winner', show: true },
            ],
            decorShape: 'dots',
            decorColor: '#b45309',
            decorOpacity: 10,
            animation: 'slideUp',
            animationDelay: '0',
        }),
    },

    'product-book': {
        ...node('BookWidget', {
            showTitle: true, showGallery: true, showDescription: true,
            showMeta: true, showWriter: true, showPublication: true,
            showPages: true, showLanguage: true,
            showPrice: true, showRating: true, showCta: true,
            titleOverride: '',
            writerName: 'লেখকের নাম',
            publicationName: 'অন্যপ্রকাশ',
            totalPages: '256',
            language: 'বাংলা',
            descriptionOverride: '',
            shortDescLength: 350,
            ratingValue: 4.9,
            reviewCount: 1247,
            starColor: '#f59e0b',
            currencySymbol: '৳',
            layout: 'row',
            maxWidth: 1060,
            metaStyle: 'grid', // Modernized from 'table' to 'grid'
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 100, paddingBottom: 100, paddingLeft: 24, paddingRight: 24,
            imageBorderRadius: 12, imageShadow: '2xl',
            titleSize: 36, titleWeight: '800', titleColor: '#1c1917',
            metaLabelColor: '#78716c', metaValueColor: '#1c1917',
            descColor: '#57534e', descSize: 16, descLineHeight: 1.8,
            priceColor: '#b45309', priceSize: 42,
            ctaText: '🛒 অর্ডার করুন — ক্যাশ অন ডেলিভারি',
            ctaUrl: '#checkout',
            ctaBg: '#b45309', ctaTextColor: '#ffffff', ctaRadius: 8,
            ctaFullWidth: true,
        }),
    },

    'features-book': {
        ...node('FeaturesWidget', {
            sectionTitle: 'কেন এই বইটি আপনার পড়া উচিত?',
            sectionSubtitle: 'হাজার হাজার পাঠক যারা এই বই পড়েছেন তারা বলছেন এটি তাদের চিন্তা করার ধরন বদলে দিয়েছে।',
            titleColor: '#1c1917', subtitleColor: '#57534e',
            titleSize: 36, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 32,
            bgType: 'color', bgColor: '#fcfbf9',
            paddingTop: 100, paddingBottom: 100, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#e7e5e4', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'md', cardPadding: 40,
            iconShape: 'soft-square', iconBg: '#ffedd5', iconColor: '#b45309', iconSize: 'xl',
            itemTitleColor: '#1c1917', itemDescColor: '#57534e',
            itemTitleSize: 20, itemDescSize: 15, itemDescLineHeight: 1.6,
            showNumbers: false,
            items: [
                { title: 'অনন্য গল্পকথন',    description: 'প্রতিটি পৃষ্ঠা আপনাকে আরো পড়তে বাধ্য করবে। লেখকের ভাষা অসাধারণ প্রাণবন্ত ও বাস্তবসম্মত।',  icon: '✍️', iconBg: '', iconColor: '' },
                { title: 'জীবন পরিবর্তনকারী', description: '৫ লক্ষেরও বেশি পাঠক বলেছেন এই বই তাদের চিন্তাভাবনা ও লক্ষ্য সম্পূর্ণ বদলে দিয়েছে।',  icon: '🌟', iconBg: '', iconColor: '' },
                { title: 'সহজলভ্য ভাষা',      description: 'জটিল মনস্তাত্ত্বিক বিষয়গুলোকে সহজ ও প্রাঞ্জল ভাষায় চমৎকারভাবে উপস্থাপন করা হয়েছে।',              icon: '🧠', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'video-book': {
        ...node('VideoWidget', {
            sectionTitle: 'বইটি সম্পর্কে লেখকের কথা',
            sectionSubtitle: 'কেন তিনি এই বইটি লিখেছেন এবং এটি কাদের জন্য।',
            titleColor: '#1c1917', subtitleColor: '#57534e',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', // Placeholder
            platform: 'youtube',
            layout: 'center',
            maxWidth: 800,
            aspectRatio: '16/9',
            borderRadius: 16,
            shadow: '2xl',
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            showControls: true, autoplay: false, loop: false, muted: false,
        }),
    },

    'testimonials-book': {
        ...node('TestimonialWidget', {
            title: 'পাঠকরা কী বলছেন',
            subtitle: 'সারা দেশের হাজারো পাঠকদের অকপট ও বাস্তব মতামত।',
            bgColor: '#f4f0e6', padding: 80,
            layout: 'masonry', cardStyle: 'modern', // Updated to masonry layout for a modern feel
            starColor: '#f59e0b', showVerified: true,
            cardRadius: 16, cardShadow: 'sm',
            reviews: [
                { name: 'রাফিউল ইসলাম', role: 'ঢাকা বিশ্ববিদ্যালয়', text: 'এই বইটি আমার জীবনে দেখা সেরা বাংলা সাহিত্য। একবার পড়া শুরু করলে শেষ না করে উঠতে পারবেন না! চরিত্রগুলো এত জীবন্ত মনে হয়।', stars: 5, avatar: '' },
                { name: 'সুমাইয়া আক্তার', role: 'শিক্ষক, চট্টগ্রাম',  text: 'লেখকের ভাষা এত সুন্দর যে মনে হয় স্বপ্নের জগতে ঘুরছি। আমার জীবনের সেরা বিনিয়োগ। ছাত্র-ছাত্রীদেরও পড়তে বলেছি।', stars: 5, avatar: '' },
                { name: 'কামরুল হাসান',  role: 'ব্যবসায়ী, সিলেট',    text: 'বইটি পেয়ে খুবই খুশি। ডেলিভারিও ছিল অত্যন্ত দ্রুত। কাজের ফাঁকে পড়তে বসলে সময় কোথায় চলে যায় টের পাই না।', stars: 5, avatar: '' },
                { name: 'আফসানা মিমি',  role: 'চাকরিজীবী, খুলনা',    text: 'জীবনের একটা কঠিন সময়ে বইটি আমার হাতে আসে। এটি আমাকে নতুন করে বাঁচার প্রেরণা জুগিয়েছে।', stars: 5, avatar: '' },
            ],
        }),
    },

    'countdown-book': {
        ...node('CountdownWidget', {
            mode: 'evergreen', durationHours: 24,
            showDays: false,
            showHeadline: true,
            headline: '⏳ প্রি-অর্ডার স্পেশাল মূল্য ছাড় শেষ হচ্ছে!',
            headlineSize: 30, headlineColor: '#1c1917', headlineWeight: '900',
            showSubtitle: true,
            subtitle: 'এই মূল্যে আর কখনো পাবেন না। স্টক ফুরিয়ে যাওয়ার আগেই নিশ্চিত করুন।',
            subtitleColor: '#57534e', subtitleSize: 16,
            expiredMessage: '⚠️ অফার শেষ হয়ে গেছে।',
            displayStyle: 'modern', boxSize: 'lg', // Modernized style
            boxBg: '#ffffff', boxTextColor: '#b45309',
            labelColor: '#57534e', boxRadius: 12, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '🔥 সীমিত সময়ের অফার — স্টক শেষ হলেই দাম বাড়বে!',
            urgencyBarBg: '#ffedd5', urgencyBarText: '#9a3412',
            bgType: 'color', bgColor: '#fcfbf9',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
            shadow: 'md',
        }),
    },

    'faq-book': {
        ...node('FaqWidget', {
            title: 'সাধারণ প্রশ্নোত্তর (FAQ)',
            subtitle: 'অর্ডার করার আগে আপনার মনের কনফিউশন দূর করুন।',
            bgColor: '#ffffff', padding: 80,
            accentColor: '#b45309', iconStyle: 'chevron', layout: 'accordion', // Modern accordion style
            questions: [
                { q: 'বইটি কি আসল (Original)?',    a: 'হ্যাঁ, আমরা সরাসরি প্রকাশকের কাছ থেকে বই সংগ্রহ করি। ১০০% আসল ও ঝকঝকে প্রিন্টের গ্যারান্টি।' },
                { q: 'ডেলিভারি পেতে কতদিন সময় লাগবে?', a: 'অর্ডার কনফার্ম হওয়ার ২৪ ঘণ্টার মধ্যে শিপমেন্ট হয়। ঢাকার ভেতরে ১-২ দিন, ঢাকার বাইরে ২-৩ দিন সময় লাগে।' },
                { q: 'ক্যাশ অন ডেলিভারি (COD) আছে কি?', a: 'হ্যাঁ! বই হাতে পেয়ে চেক করে টাকা পেমেন্ট করার সুবিধা রয়েছে। কোনো অগ্রিম পেমেন্ট নেই।' },
                { q: 'বই ছেঁড়া বা নষ্ট থাকলে কী করবো?',  a: 'ডেলিভারি ম্যানের সামনে চেক করবেন। কোনো সমস্যা পেলে সাথে সাথে রিটার্ন করতে পারবেন, আমরা সম্পূর্ণ বিনামূল্যে নতুন বই পাঠাবো।' },
            ],
        }),
    },

    'checkout-book': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 40, borderRadius: 16,
            shadow: '2xl', borderWidth: 1, borderColor: '#e7e5e4',
            showHeader: true, headerText: '📖 এখনই অর্ডার করুন',
            headerBgColor: '#f4f0e6', headerTextColor: '#1c1917', headerSize: 22,
            showProductSummary: true, summaryLayout: 'card', // Better summary layout
            showRating: true, ratingValue: 5, reviewCount: 1247,
            showMultiProduct: false, multiProductLabel: '',
            showQuantity: true, showAddress: true, showDistrict: true, showNote: true,
            nameLabel: 'আপনার পূর্ণ নাম', phoneLabel: 'সচল ফোন নম্বর',
            addressLabel: 'বিস্তারিত ডেলিভারি ঠিকানা', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'অতিরিক্ত নির্দেশনা (যদি থাকে)', quantityLabel: 'কপি সংখ্যা',
            formLayout: 'two-col',
            unitLabel: 'কপি', presetQuantities: '1, 2, 3, 5', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true, // Upselling feature
            bundles: [
                { qty: 2, discountText: 'ফ্রি ডেলিভারি' },
                { qty: 3, discountText: '১০% ছাড় + ফ্রি ডেলিভারি' },
            ],
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার নিশ্চিত করুন — ক্যাশ অন ডেলিভারি',
            buttonBgColor: '#b45309', buttonTextColor: '#ffffff',
            buttonBorderRadius: 8, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '🚀', buttonSubText: 'কোনো হিডেন চার্জ নেই • ১০০% নিরাপদ',
            showTrustBadges: true,
            trustBadges: [
                { icon: '📚', text: '১০০% অরিজিনাল',  show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি', show: true },
                { icon: '🚚', text: 'ফাস্ট ডেলিভারি', show: true },
                { icon: '↩️', text: 'সহজ রিটার্ন', show: true },
            ],
            showUrgency: true, urgencyText: '🔥 মাত্র কয়েক কপি স্টকে অবশিষ্ট আছে!',
            urgencyBgColor: '#ffedd5', urgencyTextColor: '#9a3412',
            showSocialProof: true,
            socialProofText: 'গত ২৪ ঘণ্টায় ৩৪২ জন এই বইটি অর্ডার করেছেন',
            socialProofIcon: '🔥',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true,
            mobileStickyText: '📖 অর্ডার করুন — COD',
            mobileStickyBg: '#ffffff',
            themeColor: '#b45309',
            labelColor: '#44403c', inputBorderColor: '#d6d3d1', inputBgColor: '#fcfbf9', inputRadius: 8,
        }),
    },
};