// resources/js/Features/PageBuilder/Templates/FashionTemplate.js
import { node, container } from './helpers';

export const FASHION_TEMPLATE = {
    ROOT: container({ bgColor: '#fdf8fa', bgType: 'color', gap: 0 }, [
        'hero-fashion', 'product-fashion', 'features-fashion',
        'testimonials-fashion', 'countdown-fashion', 'faq-fashion', 'checkout-fashion',
    ]),

    'hero-fashion': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#fdf8fa',
            bgGradientTo: '#fce7f3',
            bgGradientDirection: 180,
            minHeight: 620,
            paddingTop: 120, paddingBottom: 120, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center', contentMaxWidth: 800, contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '✨ Eid Collection 2025',
            badgeColor: '#be185d', badgeBgColor: '#fbcfe8',
            title: 'আপনার সৌন্দর্যের\nনতুন সংজ্ঞা লিখুন',
            titleSize: 64, titleWeight: '900', titleColor: '#271c19',
            titleLineHeight: 1.05, titleLetterSpacing: -0.025,
            subtitle: 'হাতে বোনা সুতা, ঐতিহ্যবাহী ডিজাইন, আধুনিক কাটিং — ঈদের জন্য পোশাক যা আপনাকে করবে অনন্য।',
            subtitleSize: 18, subtitleColor: '#70595d', subtitleMaxWidth: 580, subtitleLineHeight: 1.7,
            showPrimaryBtn: true,
            primaryBtnText: '🛍️ এখনই কিনুন',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#be185d', primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#be185d', primaryBtnBorderRadius: 2, primaryBtnSize: 'lg',
            showSecondaryBtn: false,
            showStats: true,
            stats: [
                { value: '50,000+',    label: 'সন্তুষ্ট গ্রাহক', show: true },
                { value: '500+ ডিজাইন', label: 'এক্সক্লুসিভ কালেকশন', show: true },
                { value: 'হাতে তৈরি', label: 'প্রতিটি পোশাক', show: true },
            ],
            decorShape: 'none',
            animation: 'fade', animationDelay: '0',
        }),
    },

    'product-fashion': {
        ...node('ProductWidget', {
            layout: 'side-by-side', maxWidth: 1060,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            imageRatio: '3:4', imageBorderRadius: 0, imageShadow: 'lg',
            showGallery: true,
            showBadge: true, badgeText: '✨ Eid Special', badgeBg: '#be185d', badgeColor: '#ffffff',
            showTitle: true, titleSize: 32, titleWeight: '800', titleColor: '#271c19', titleLineHeight: 1.2,
            showPrice: true, priceColor: '#be185d', priceSize: 40, priceWeight: '900',
            showOriginalPrice: true, showDiscountBadge: true, currencySymbol: '৳',
            showRating: true, ratingValue: 4.9, reviewCount: 2847, starColor: '#be185d',
            showDescription: true, descriptionSize: 15, descriptionColor: '#70595d', descriptionLines: 4,
            showSpecs: true,
            specs: [
                { icon: '🧵', label: 'কাপড়',        value: '১০০% প্রিমিয়াম কটন',        show: true },
                { icon: '🎨', label: 'রং',           value: 'ফেড-প্রুফ ন্যাচারাল ডাই',   show: true },
                { icon: '📐', label: 'সাইজ',         value: 'S / M / L / XL / XXL',     show: true },
                { icon: '🧺', label: 'পরিচর্যা',      value: 'হাতে ধুলে দীর্ঘস্থায়ী',     show: true },
                { icon: '🏭', label: 'তৈরি',         value: 'বাংলাদেশে হাতে বোনা',        show: true },
            ],
            showTrust: true,
            trustItems: [
                { icon: '💎', text: 'হাতে তৈরি',         bg: '#fdf2f8', color: '#be185d', show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি', bg: '#f0fdf4', color: '#16a34a', show: true },
                { icon: '↩️', text: '৭ দিনের রিটার্ন',   bg: '#fff1f2', color: '#e11d48', show: true },
                { icon: '✅', text: 'কোয়ালিটি গ্যারান্টি', bg: '#e0e7ff', color: '#4f46e5', show: true },
            ],
            showStock: true, stockText: '💫 এই কালেকশনের মাত্র ১৫টি বাকি আছে!',
            stockBg: '#fef2f2', stockColor: '#be185d',
            showCta: true,
            ctaText: '🛍️ এখনই অর্ডার করুন',
            ctaUrl: '#checkout', ctaBg: '#be185d', ctaTextColor: '#ffffff',
            ctaRadius: 2, ctaSize: 'lg',
            ctaSubText: 'ক্যাশ অন ডেলিভারি • ফ্রি এক্সচেঞ্জ',
            ctaBorderColor: '',
            animation: 'fadeUp',
        }),
    },

    'features-fashion': {
        ...node('FeaturesWidget', {
            sectionTitle: 'কেন আমাদের পোশাক আলাদা',
            sectionSubtitle: 'প্রতিটি পোশাক তৈরিতে আমরা কোনো আপোষ করি না।',
            titleColor: '#271c19', subtitleColor: '#70595d',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 24,
            bgType: 'color', bgColor: '#fdf8fa',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fbcfe8', cardBorderWidth: 1,
            cardRadius: 2, cardShadow: 'sm', cardPadding: 32,
            iconShape: 'none', iconBg: 'transparent', iconColor: '#be185d', iconSize: 'lg',
            itemTitleColor: '#271c19', itemDescColor: '#70595d',
            itemTitleSize: 17, itemDescSize: 14,
            showNumbers: false,
            items: [
                { title: 'হাতে বোনা কারুকাজ',   description: 'প্রতিটি পোশাক দক্ষ কারিগরের হাতে তৈরি। মেশিন-মেড পণ্যে যে সূক্ষ্মতা পাওয়া যায় না।', icon: '🧵', iconBg: '', iconColor: '' },
                { title: 'টেকসই কাপড়',          description: '১০০% প্রিমিয়াম কটন ব্যবহার করা হয়। বারবার ধুলেও রং ও গঠন অটুট থাকে।',               icon: '💎', iconBg: '', iconColor: '' },
                { title: 'এক্সক্লুসিভ ডিজাইন',  description: 'প্রতিটি ডিজাইন একটিমাত্র সিজনে লিমিটেড পরিমাণে তৈরি হয়। আপনি থাকবেন অনন্য।',       icon: '✨', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeIn', staggerDelay: '0.1',
        }),
    },

    'testimonials-fashion': {
        ...node('TestimonialWidget', {
            title: 'তারা কী বলছেন',
            subtitle: 'আমাদের ৫০,০০০ এরও বেশি সন্তুষ্ট গ্রাহকের কথা।',
            bgColor: '#ffffff', padding: 60,
            layout: 'grid', cardStyle: 'shadow',
            starColor: '#be185d', showVerified: true,
            reviews: [
                { name: 'নওশীন আক্তার',    role: 'ঢাকা, গুলশান',    text: 'ঈদের পোশাক কোথা থেকে নেবো চিন্তায় ছিলাম। এখানে অর্ডার করে পেয়ে এত সুন্দর কারুকাজ দেখে মন ভরে গেল। প্রতি বছর এখান থেকেই নেবো।', stars: 5, avatar: '' },
                { name: 'ফারিয়া রহমান',    role: 'চট্টগ্রাম',         text: 'কাপড়ের মান অসাধারণ। মেয়ের ঈদের পোশাক নিলাম, পরে দেখে মেয়ে এত খুশি হলো! ডেলিভারিও সময়মতো।',                                           stars: 5, avatar: '' },
                { name: 'সাবরিনা হোসেন',  role: 'সিলেট',             text: 'অনলাইনে পোশাক কিনতে ভয় লাগতো। কিন্তু এখানে ছবির মতোই পোশাক পেলাম। এখন আত্মীয়দেরও রেফার করছি।',                                         stars: 5, avatar: '' },
            ],
        }),
    },

    'countdown-fashion': {
        ...node('CountdownWidget', {
            mode: 'evergreen', durationHours: 72,
            showDays: true,
            showHeadline: true,
            headline: '💫 ঈদ স্পেশাল ছাড় শেষ হওয়ার আগেই নিন!',
            headlineSize: 24, headlineColor: '#271c19', headlineWeight: '800',
            showSubtitle: true,
            subtitle: 'এই মৌসুমে একবারই এই দামে পাবেন। স্টক সীমিত।',
            subtitleColor: '#70595d', subtitleSize: 15,
            expiredMessage: '⚠️ ঈদ অফার শেষ।',
            displayStyle: 'filled', boxSize: 'md',
            boxBg: '#ffffff', boxTextColor: '#be185d',
            labelColor: '#70595d', boxRadius: 2, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '✨ ঈদের আগে অর্ডার করুন — সময়মতো ডেলিভারি গ্যারান্টি!',
            urgencyBarBg: '#fce7f3', urgencyBarText: '#be185d',
            bgType: 'gradient', bgGradientFrom: '#fdf8fa', bgGradientTo: '#fce7f3', bgGradientDirection: 180,
            paddingTop: 56, paddingBottom: 56, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
        }),
    },

    'faq-fashion': {
        ...node('FaqWidget', {
            title: 'প্রশ্নোত্তর',
            subtitle: 'অর্ডার করার আগে যা জানা দরকার।',
            bgColor: '#fdf8fa', padding: 60,
            accentColor: '#be185d', iconStyle: 'plus', layout: 'default',
            questions: [
                { q: 'সাইজ না মিললে কী করবো?',      a: 'ডেলিভারির ৭ দিনের মধ্যে সাইজ এক্সচেঞ্জ করতে পারবেন। বিনামূল্যে পিক-আপ ও ডেলিভারি।' },
                { q: 'কাস্টম সাইজে পাওয়া যাবে?',    a: 'হ্যাঁ! অর্ডারের সময় নোটে আপনার মাপ দিন। কাস্টম সাইজের জন্য ৩-৫ কার্যদিবস বেশি সময় লাগে।' },
                { q: 'ঈদের আগে পাবো তো?',            a: 'ঈদের ৫ দিন আগে পর্যন্ত অর্ডার করলে সময়মতো ডেলিভারি গ্যারান্টি। এর পরে হলে নিশ্চিত করতে কল করুন।' },
                { q: 'কাপড় কি ছবির মতো হবে?',       a: 'অবশ্যই। আমরা আসল পণ্যের ছবি ব্যবহার করি। স্ক্রিনের কারণে সামান্য রং পার্থক্য হতে পারে।' },
            ],
        }),
    },

    'checkout-fashion': {
        ...node('CheckoutWidget', {
            maxWidth: 560, bgColor: '#ffffff', padding: 32, borderRadius: 2,
            shadow: 'md', borderWidth: 1, borderColor: '#fbcfe8',
            showHeader: true, headerText: '✨ আপনার অর্ডার দিন',
            headerBgColor: '#fce7f3', headerTextColor: '#be185d', headerSize: 20,
            showProductSummary: true, summaryLayout: 'row',
            showRating: true, ratingValue: 5, reviewCount: 2847,
            showMultiProduct: false,
            showQuantity: true, showAddress: true, showDistrict: true, showNote: false,
            nameLabel: 'আপনার নাম', phoneLabel: 'ফোন নম্বর',
            addressLabel: 'ডেলিভারি ঠিকানা', districtLabel: 'জেলা',
            noteLabel: 'কাস্টম নির্দেশনা', quantityLabel: 'পরিমাণ',
            formLayout: 'two-col',
            unitLabel: 'পিস', presetQuantities: '1, 2, 3', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true,
            bundles: [
                { qty: 2, price: 2800 },
                { qty: 3, price: 3900 },
            ],
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: true, variantLabel: 'সাইজ বেছে নিন',
            variantOptions: ['S', 'M', 'L', 'XL', 'XXL'],
            buttonText: 'অর্ডার নিশ্চিত করুন',
            buttonBgColor: '#be185d', buttonTextColor: '#ffffff',
            buttonBorderRadius: 2, buttonSize: 'lg', buttonFullWidth: true,
            buttonIcon: '🛍️', buttonSubText: 'ক্যাশ অন ডেলিভারি • ফ্রি সাইজ এক্সচেঞ্জ',
            showTrustBadges: true,
            trustBadges: [
                { icon: '💎', text: 'হাতে তৈরি কোয়ালিটি', show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি',    show: true },
                { icon: '🔄', text: 'ফ্রি সাইজ এক্সচেঞ্জ',  show: true },
                { icon: '🚚', text: 'সারা বাংলাদেশ ডেলিভারি', show: true },
            ],
            showUrgency: true, urgencyText: '✨ ঈদের আগে অর্ডার করুন — সীমিত স্টক!',
            urgencyBgColor: '#fce7f3', urgencyTextColor: '#be185d',
            showSocialProof: true,
            socialProofText: 'গত ২৪ ঘণ্টায় ৫৬৩ জন অর্ডার করেছেন',
            socialProofIcon: '✨',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true,
            mobileStickyText: '🛍️ অর্ডার করুন — COD',
            mobileStickyBg: '#ffffff',
            themeColor: '#be185d',
            labelColor: '#70595d', inputBorderColor: '#fbcfe8', inputBgColor: '#fdf8fa',
        }),
    },
};