// resources/js/Features/PageBuilder/Templates/FatawaHanafiaTemplate.js
import { node, container } from './helpers';

export const FATAWA_HANAFIA_TEMPLATE = {
    ROOT: container({ 
        bgColor: '#f8fafc', 
        bgType: 'color', 
        gap: 0, 
        paddingTop: 0, 
        paddingBottom: 0 
    }, [
        'hero-fatawa', 
        'problem-fatawa',
        'product-fatawa', 
        'features-fatawa',
        'extras-fatawa',
        'why-buy-fatawa',
        'countdown-fatawa',
        'checkout-fatawa',
    ]),

    'hero-fatawa': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#7f1d1d', // Deep Maroon/Crimson
            bgGradientTo: '#450a0a',
            bgGradientDirection: 180,
            bgImage: '',
            overlayColor: '#000000',
            overlayOpacity: 20,
            minHeight: 650,
            paddingTop: 120,
            paddingBottom: 100,
            paddingLeft: 24,
            paddingRight: 24,
            contentAlign: 'center',
            contentMaxWidth: 900,
            contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '🛑 অবিশ্বাস্য মূল্যছাড় — ২১০০ টাকার বই মাত্র ৭০০ টাকায়!',
            badgeColor: '#7f1d1d',
            badgeBgColor: '#fef08a',
            title: 'ফতোয়ায়ে হানাফিয়া\nআপনার ঘরের নির্ভরযোগ্য "মুফতী"',
            titleSize: 56,
            titleWeight: '900',
            titleColor: '#ffffff',
            titleLineHeight: 1.2,
            titleLetterSpacing: -0.02,
            subtitle: 'দৈনন্দিন জীবনের ৩৩২৪টিরও বেশি মাসআলার সহজ ও প্রমাণভিত্তিক সমাধান। যেকোনো সময় প্রয়োজনীয় মাসআলার সমাধান এখন আপনার হাতের নাগালে।',
            subtitleSize: 20,
            subtitleColor: '#fecaca',
            subtitleMaxWidth: 750,
            subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '📖 অর্ডার করুন — মাত্র ৭০০ ৳',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#d97706', // Gold/Amber
            primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#d97706',
            primaryBtnBorderRadius: 8,
            primaryBtnSize: 'xl',
            showSecondaryBtn: true,
            secondaryBtnText: 'বিস্তারিত জানুন',
            secondaryBtnUrl: '#problem',
            secondaryBtnStyle: 'outline',
            secondaryBtnBgColor: 'transparent',
            secondaryBtnTextColor: '#ffffff',
            secondaryBtnBorderColor: '#ffffff',
            secondaryBtnBorderRadius: 8,
            secondaryBtnSize: 'xl',
            showStats: true,
            stats: [
                { value: '৩৩২৪+', label: 'প্রয়োজনীয় মাসআলা', show: true, color: '#fde047' },
                { value: '২১০০ ৳', label: 'মুদ্রিত মূল্য', show: true, color: '#fde047' },
                { value: '৬৬%', label: 'বিশাল ছাড়', show: true, color: '#fde047' },
            ],
            decorShape: 'dots',
            decorColor: '#ffffff',
            decorOpacity: 10,
            animation: 'slideUp',
            animationDelay: '0',
        }),
    },

    'problem-fatawa': {
        ...node('FeaturesWidget', {
            sectionTitle: 'ভাবুন তো— রাত ৩টা, সেহরির সময়...',
            sectionSubtitle: 'হঠাৎ একটি মাসআলা জানার প্রয়োজন হলো, কিন্তু চারপাশে কোনো আলেম নেই, ফোন করারও উপায় নেই। এমন পরিস্থিতিতে কী করবেন?',
            titleColor: '#7f1d1d', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'horizontal', gap: 24,
            bgType: 'color', bgColor: '#fef2f2', // Very soft red/pink background
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fecaca', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'sm', cardPadding: 30,
            iconShape: 'circle', iconBg: '#fef2f2', iconColor: '#b91c1c', iconSize: 'lg',
            itemTitleColor: '#450a0a', itemDescColor: '#475569',
            itemTitleSize: 18, itemDescSize: 15, itemDescLineHeight: 1.6,
            showNumbers: false,
            items: [
                { title: 'দাঁত ব্রাশ করলে কি রোজা থাকবে?', description: '', icon: '🪥', iconBg: '', iconColor: '' },
                { title: 'ভুল করে পানি খেয়ে ফেললে কী হবে?', description: '', icon: '💧', iconBg: '', iconColor: '' },
                { title: 'ইনজেকশন নিলে কি রোজা ভেঙে যাবে?', description: '', icon: '💉', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'product-fatawa': {
        ...node('BookWidget', {
            showTitle: true, showGallery: true, showDescription: true,
            showMeta: true, showWriter: false, showPublication: false,
            showPages: false, showLanguage: true,
            showPrice: true, showRating: true, showCta: true,
            titleOverride: 'ফতোয়ায়ে হানাফিয়া (সম্পূর্ণ খণ্ড)',
            writerName: '',
            publicationName: '',
            totalPages: '',
            language: 'বাংলা অনুবাদ',
            descriptionOverride: 'সমাধান একটাই— আপনার নিজের ঘরেই রাখুন একজন নির্ভরযোগ্য "মুফতী"। ফতোয়ায়ে হানাফিয়া বইটি আপনার ব্যক্তিগত ইসলামী গাইডের মতো কাজ করবে। প্রতিটি মাসআলার সাথে রেফারেন্স ও দালিলিক ব্যাখ্যা দেওয়া আছে।',
            shortDescLength: 350,
            ratingValue: 5.0,
            reviewCount: 920,
            starColor: '#d97706',
            currencySymbol: '৳',
            layout: 'row',
            maxWidth: 1060,
            metaStyle: 'grid', 
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            imageBorderRadius: 12, imageShadow: '2xl',
            titleSize: 36, titleWeight: '800', titleColor: '#7f1d1d',
            metaLabelColor: '#64748b', metaValueColor: '#0f172a',
            descColor: '#334155', descSize: 16, descLineHeight: 1.8,
            priceColor: '#d97706', priceSize: 42,
            ctaText: '🛒 ক্যাশ অন ডেলিভারিতে অর্ডার করুন',
            ctaUrl: '#checkout',
            ctaBg: '#7f1d1d', ctaTextColor: '#ffffff', ctaRadius: 8,
            ctaFullWidth: true,
        }),
    },

    'features-fatawa': {
        ...node('FeaturesWidget', {
            sectionTitle: '📖 বইটির বিশেষ বৈশিষ্ট্য',
            sectionSubtitle: 'দৈনন্দিন জীবনের শত শত প্রয়োজনীয় মাসআলা ও তার সহজ সমাধান।',
            titleColor: '#7f1d1d', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 2, layout: 'vertical', gap: 32,
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 80, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#e2e8f0', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 32,
            iconShape: 'soft-square', iconBg: '#fee2e2', iconColor: '#7f1d1d', iconSize: 'xl',
            itemTitleColor: '#450a0a', itemDescColor: '#475569',
            itemTitleSize: 20, itemDescSize: 15, itemDescLineHeight: 1.6,
            showNumbers: false,
            items: [
                { title: 'ইবাদত সংক্রান্ত মাসআলা', description: 'নামাজ, রোজা, হজ, যাকাত সহ ইবাদতের যাবতীয় খুঁটিনাটি ও গুরুত্বপূর্ণ মাসআলা।', icon: '🕌', iconBg: '', iconColor: '' },
                { title: 'লেনদেন ও ব্যবসা-বাণিজ্য', description: 'হালাল-হারাম, ক্রয়-বিক্রয় এবং আধুনিক ব্যবসা-বাণিজ্যের শরয়ী বিধান।', icon: '⚖️', iconBg: '', iconColor: '' },
                { title: 'পারিবারিক ও সামাজিক সমস্যা', description: 'বিয়ে, তালাক, মিরাস (উত্তরাধিকার) এবং সামাজিক নানা সমস্যার সুস্পষ্ট সমাধান।', icon: '👨‍👩‍👧‍👦', iconBg: '', iconColor: '' },
                { title: 'দৈনন্দিন জীবনের বিধান', description: 'খাদ্য, পোশাক, চিকিৎসা এবং দৈনন্দিন জীবনে উদ্ভূত শত শত নতুন সমস্যার সমাধান।', icon: ' 생활', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'extras-fatawa': {
        ...node('FeaturesWidget', {
            sectionTitle: '📚 বইটিতে আরও যা পাবেন',
            sectionSubtitle: 'মাসআলার পাশাপাশি এই গ্রন্থে রয়েছে ইতিহাস ও জীবনী।',
            titleColor: '#7f1d1d', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 24,
            bgType: 'color', bgColor: '#ffffff', 
            paddingTop: 60, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#fffbeb', cardBorderColor: '#fde68a', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'none', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fef3c7', iconColor: '#d97706', iconSize: 'md',
            itemTitleColor: '#450a0a', itemDescColor: '#475569',
            itemTitleSize: 18, itemDescSize: 15, itemDescLineHeight: 1.5,
            showNumbers: false,
            items: [
                { title: 'ফিকহ শাস্ত্রের ইতিহাস', description: 'ইসলামী ফিকহ বা আইন শাস্ত্র কীভাবে সংকলিত হলো তার সংক্ষিপ্ত ও চমৎকার ইতিহাস।', icon: '📜', iconBg: '', iconColor: '' },
                { title: 'মহান ইমামদের জীবনী', description: 'ইমাম আবু হানিফা (রহ.) সহ ইসলামের চার মহান ইমামের জীবন, কর্ম ও অবদান।', icon: '✍️', iconBg: '', iconColor: '' },
                { title: 'রেফারেন্স ও দালিলিক ব্যাখ্যা', description: 'প্রতিটি মাসআলার শেষে নির্ভরযোগ্য কিতাবের রেফারেন্স ও দালিলিক ব্যাখ্যা যুক্ত করা হয়েছে।', icon: '📑', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'why-buy-fatawa': {
        ...node('FeaturesWidget', {
            sectionTitle: '🌙 কেন এই বইটি আপনার ঘরে থাকা প্রয়োজন?',
            sectionSubtitle: '',
            titleColor: '#7f1d1d', subtitleColor: '#475569',
            titleSize: 30, subtitleSize: 16, headerAlign: 'center',
            columns: 2, layout: 'horizontal', gap: 24,
            bgType: 'color', bgColor: '#fef2f2',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fecaca', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fee2e2', iconColor: '#b91c1c', iconSize: 'md',
            itemTitleColor: '#450a0a', itemDescColor: '#475569',
            itemTitleSize: 18, itemDescSize: 15, itemDescLineHeight: 1.5,
            showNumbers: false,
            items: [
                { title: 'যেকোনো সময় সমাধান', description: 'মুফতী সাহেবকে ফোনে না পেলেও যেকোনো সময় প্রয়োজনীয় মাসআলার সমাধান নিজে বের করতে পারবেন।', icon: '✅', iconBg: '', iconColor: '' },
                { title: 'পরিবারের ইসলামী জ্ঞান', description: 'পরিবারকে সঠিক ইসলামী জ্ঞান দেওয়ার এক দারুণ সুযোগ।', icon: '✅', iconBg: '', iconColor: '' },
                { title: 'ভুল থেকে বাঁচতে', description: 'না জানার কারণে দ্বীনের বিষয়ে যেসব ভুল হয়, তা থেকে বাঁচতে বইটি সহায়তা করবে।', icon: '✅', iconBg: '', iconColor: '' },
                { title: 'ব্যক্তিগত রেফারেন্স', description: 'এটি আপনার নিজের ও পরিবারের জন্য একটি স্থায়ী ব্যক্তিগত ইসলামী রেফারেন্স বই।', icon: '✅', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'countdown-fatawa': {
        ...node('CountdownWidget', {
            mode: 'evergreen', durationHours: 24,
            showDays: false,
            showHeadline: true,
            headline: '⏳ অবিশ্বাস্য মূল্যছাড়টি যেকোনো সময় শেষ হতে পারে!',
            headlineSize: 30, headlineColor: '#7f1d1d', headlineWeight: '900',
            showSubtitle: true,
            subtitle: '২১০০ টাকার ফতোয়ায়ে হানাফিয়া মাত্র ৭০০ টাকায় পেতে এখনি অর্ডার করুন।',
            subtitleColor: '#475569', subtitleSize: 16,
            expiredMessage: '⚠️ অফার শেষ হয়ে গেছে।',
            displayStyle: 'modern', boxSize: 'lg', 
            boxBg: '#ffffff', boxTextColor: '#7f1d1d',
            labelColor: '#475569', boxRadius: 12, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '🔥 খুবই সীমিত স্টক! স্টক শেষ হওয়ার আগেই অর্ডার করুন।',
            urgencyBarBg: '#fef2f2', urgencyBarText: '#991b1b',
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
            shadow: 'md',
        }),
    },

    'checkout-fatawa': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 40, borderRadius: 16,
            shadow: '2xl', borderWidth: 1, borderColor: '#e2e8f0',
            showHeader: true, headerText: '📖 এখনই অর্ডার করুন মাত্র ৭০০ টাকায়',
            headerBgColor: '#fef2f2', headerTextColor: '#7f1d1d', headerSize: 22,
            showProductSummary: true, summaryLayout: 'card', 
            showRating: true, ratingValue: 5, reviewCount: 920,
            showMultiProduct: false, multiProductLabel: '',
            showQuantity: true, showAddress: true, showDistrict: true, showNote: true,
            nameLabel: 'আপনার নাম', phoneLabel: 'মোবাইল নাম্বার',
            addressLabel: 'সম্পূর্ণ ঠিকানা', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'অতিরিক্ত নির্দেশনা (যদি থাকে)', quantityLabel: 'কপি সংখ্যা',
            formLayout: 'two-col',
            unitLabel: 'কপি', presetQuantities: '1, 2, 3', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: false, 
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার কনফার্ম করুন (ক্যাশ অন ডেলিভারি)',
            buttonBgColor: '#7f1d1d', buttonTextColor: '#ffffff',
            buttonBorderRadius: 8, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '🚀', buttonSubText: '২১০০ টাকার বই পাচ্ছেন মাত্র ৭০০ টাকায়',
            showTrustBadges: true,
            trustBadges: [
                { icon: '📦', text: 'ক্যাশ অন ডেলিভারি', show: true },
                { icon: '🚚', text: 'সারা দেশে হোম ডেলিভারি', show: true },
                { icon: '💯', text: 'অরিজিনাল বইয়ের গ্যারান্টি', show: true },
            ],
            showUrgency: true, urgencyText: '🔥 বিশাল ডিসকাউন্টে স্টক প্রায় শেষের দিকে!',
            urgencyBgColor: '#fef2f2', urgencyTextColor: '#991b1b',
            showSocialProof: true,
            socialProofText: 'গত ২৪ ঘণ্টায় ১১২ জন বইটি অর্ডার করেছেন',
            socialProofIcon: '🔥',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true, 
            mobileStickyText: '🛒 অর্ডার করুন — ৭০০ ৳',
            mobileStickyBg: '#ffffff',
            themeColor: '#7f1d1d',
            labelColor: '#334155', inputBorderColor: '#cbd5e1', inputBgColor: '#f8fafc', inputRadius: 8,
        }),
    },
};