// resources/js/Features/PageBuilder/Templates/FoodTemplate.js
import { node, container } from './helpers';

export const FOOD_TEMPLATE = {
    ROOT: container({ bgColor: '#fffdfa', bgType: 'color', gap: 0, paddingTop: 0, paddingBottom: 0 }, [
        'hero-food', 'product-food', 'features-food',
        'countdown-food', 'testimonials-food', 'faq-food', 'checkout-food',
    ]),

    'hero-food': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#fffdfa',
            bgGradientTo: '#fff7ed',
            bgGradientDirection: 145,
            minHeight: 580,
            paddingTop: 100, paddingBottom: 100, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center', contentMaxWidth: 820, contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '🔥 আজকের বিশেষ অফার',
            badgeColor: '#ea580c', badgeBgColor: '#ffedd5',
            title: 'এক কামড়েই প্রেমে পড়বেন\nআমাদের ঐতিহ্যবাহী রান্নায়',
            titleSize: 58, titleWeight: '900', titleColor: '#1c1917',
            titleLineHeight: 1.1, titleLetterSpacing: -0.02,
            subtitle: 'ঘরে বসে পান রেস্তোরাঁর স্বাদ। তাজা উপকরণ, হাতের রান্না, আপনার দরজায় গরম গরম পৌঁছে দেওয়া হবে।',
            subtitleSize: 18, subtitleColor: '#57534e', subtitleMaxWidth: 600, subtitleLineHeight: 1.65,
            showPrimaryBtn: true,
            primaryBtnText: '🛒 এখনই অর্ডার করুন',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#ea580c', primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#ea580c', primaryBtnBorderRadius: 50, primaryBtnSize: 'lg',
            showSecondaryBtn: false,
            showStats: true,
            stats: [
                { value: '10,000+', label: 'সন্তুষ্ট গ্রাহক',  show: true },
                { value: '4.8 ★',   label: 'গ্রাহক রেটিং',     show: true },
                { value: '60 মিনিট', label: 'সর্বোচ্চ ডেলিভারি', show: true },
            ],
            decorShape: 'blob-tr', decorColor: '#fdba74', decorOpacity: 30,
            animation: 'slideUp', animationDelay: '0',
        }),
    },

    'product-food': {
        ...node('ProductWidget', {
            layout: 'side-by-side', maxWidth: 1000,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            imageRatio: '4:3', imageBorderRadius: 20, imageShadow: 'lg',
            showGallery: true,
            showBadge: true, badgeText: 'Best Seller', badgeBg: '#ea580c', badgeColor: '#ffffff',
            showTitle: true, titleSize: 34, titleWeight: '800', titleColor: '#1c1917', titleLineHeight: 1.25,
            showPrice: true, priceColor: '#ea580c', priceSize: 38, priceWeight: '900',
            showOriginalPrice: true, showDiscountBadge: true, currencySymbol: '৳',
            showRating: true, ratingValue: 4.8, reviewCount: 892, starColor: '#ea580c',
            showDescription: true, descriptionSize: 15, descriptionColor: '#57534e', descriptionLines: 4,
            showSpecs: true,
            specs: [
                { icon: '🌿', label: 'উপকরণ',    value: '১০০% তাজা ও প্রাকৃতিক',       show: true },
                { icon: '🍳', label: 'রান্না',    value: 'প্রতিদিন সকালে তৈরি',          show: true },
                { icon: '📦', label: 'প্যাকেজিং', value: 'হাইজিনিক এয়ারটাইট প্যাক',     show: true },
                { icon: '🚚', label: 'ডেলিভারি',  value: 'ঢাকায় ৬০ মিনিট, বাইরে ২-৩ দিন', show: true },
                { icon: '💵', label: 'পেমেন্ট',   value: 'ক্যাশ অন ডেলিভারি',            show: true },
            ],
            showTrust: true,
            trustItems: [
                { icon: '🌿', text: '১০০% হালাল',       bg: '#f0fdf4', color: '#16a34a', show: true },
                { icon: '🧊', text: 'কোল্ড চেইন রক্ষিত', bg: '#f0f9ff', color: '#0284c7', show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি', bg: '#fff7ed', color: '#ea580c', show: true },
                { icon: '↩️', text: 'সমস্যায় রিফান্ড',  bg: '#fef2f2', color: '#dc2626', show: true },
            ],
            showStock: true, stockText: '🔥 আজকের জন্য মাত্র ৫০টি অর্ডার বাকি!',
            stockBg: '#ffedd5', stockColor: '#ea580c',
            showCta: true,
            ctaText: '🍽️ এখনই অর্ডার করুন',
            ctaUrl: '#checkout', ctaBg: '#ea580c', ctaTextColor: '#ffffff',
            ctaRadius: 50, ctaSize: 'lg',
            ctaSubText: 'অগ্রিম পেমেন্ট নেই • ডেলিভারিতে টাকা দিন',
            ctaBorderColor: '',
            animation: 'fadeUp',
        }),
    },

    'features-food': {
        ...node('FeaturesWidget', {
            sectionTitle: 'কেন আমাদের খাবার বেছে নেবেন?',
            sectionSubtitle: 'প্রতিটি খাবার তৈরিতে আমরা আপনার স্বাস্থ্য ও স্বাদ দুটোকেই সমান গুরুত্ব দিই।',
            titleColor: '#1c1917', subtitleColor: '#57534e',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            columns: 4, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fffdfa',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#ffedd5', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 28,
            iconShape: 'circle', iconBg: '#ffedd5', iconColor: '#ea580c', iconSize: 'md',
            itemTitleColor: '#1c1917', itemDescColor: '#57534e',
            itemTitleSize: 16, itemDescSize: 14,
            showNumbers: false,
            items: [
                { title: '১০০% তাজা',      description: 'প্রতিদিন সকালে তাজা উপকরণ দিয়ে রান্না শুরু হয়।', icon: '🌿', iconBg: '', iconColor: '' },
                { title: 'হাইজিনিক রান্না', description: 'সর্বোচ্চ পরিষ্কার-পরিচ্ছন্নতা নিশ্চিত করে প্রতিটি খাবার তৈরি।', icon: '✨', iconBg: '', iconColor: '' },
                { title: 'দ্রুত ডেলিভারি',  description: 'ঢাকায় ৬০ মিনিটের মধ্যে গরম খাবার আপনার দোরগোড়ায়।', icon: '🚀', iconBg: '', iconColor: '' },
                { title: 'সেরা স্বাদ',       description: 'আমাদের শেফরা বছরের পর বছর ধরে একই ঐতিহ্যবাহী রেসিপি ব্যবহার করেন।', icon: '🍽️', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    'countdown-food': {
        ...node('CountdownWidget', {
            mode: 'daily',
            showDays: false,
            showHeadline: true,
            headline: '⏰ আজকের অফার শেষ হওয়ার আগেই অর্ডার করুন!',
            headlineSize: 24, headlineColor: '#1c1917', headlineWeight: '800',
            showSubtitle: true,
            subtitle: 'প্রতিদিন রাত ১২টায় রিসেট হয়। আজকের বিশেষ ছাড় মিস করবেন না।',
            subtitleColor: '#57534e', subtitleSize: 15,
            expiredMessage: '⚠️ আজকের অফার শেষ। কাল আবার আসুন।',
            displayStyle: 'card', boxSize: 'md',
            boxBg: '#ffffff', boxTextColor: '#ea580c',
            labelColor: '#57534e', boxRadius: 50, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '🔥 আজ রাত পর্যন্ত বিনামূল্যে ডেলিভারি!',
            urgencyBarBg: '#ffedd5', urgencyBarText: '#ea580c',
            bgType: 'gradient', bgGradientFrom: '#fffdfa', bgGradientTo: '#fff7ed', bgGradientDirection: 135,
            paddingTop: 56, paddingBottom: 56, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
        }),
    },

    'testimonials-food': {
        ...node('TestimonialWidget', {
            title: 'গ্রাহকরা কী বলছেন',
            subtitle: 'আমাদের প্রতিদিনের গ্রাহকদের মতামত।',
            bgColor: '#ffffff', padding: 60,
            layout: '2col', cardStyle: 'shadow',
            starColor: '#ea580c', showVerified: true,
            reviews: [
                { name: 'তাহমিনা বেগম', role: 'গৃহিণী, ঢাকা',      text: 'ঘরে বসে এত ভালো খাবার পাওয়া সম্ভব জানতাম না! স্বাদ একদম ঘরের রান্নার মতো। প্রতি সপ্তাহে অর্ডার করি।', stars: 5, avatar: '' },
                { name: 'আরিফ হোসেন',   role: 'ব্যবসায়ী, উত্তরা',  text: 'অফিসে লাঞ্চের জন্য অর্ডার করি। সময়মতো ডেলিভারি আর অসাধারণ স্বাদ — দলের সবাই পছন্দ করে।',         stars: 5, avatar: '' },
            ],
        }),
    },

    'faq-food': {
        ...node('FaqWidget', {
            title: 'আপনার প্রশ্নের উত্তর',
            subtitle: 'অর্ডার করার আগে জেনে নিন।',
            bgColor: '#fffdfa', padding: 60,
            accentColor: '#ea580c', iconStyle: 'plus', layout: 'default',
            questions: [
                { q: 'খাবার কি গরম অবস্থায় পাবো?',    a: 'হ্যাঁ! আমরা থার্মো-ইন্সুলেটেড প্যাকেজিং ব্যবহার করি। ঢাকায় সর্বোচ্চ ৬০ মিনিটে ডেলিভারি নিশ্চিত।' },
                { q: 'উপকরণ কি হালাল?',               a: 'অবশ্যই। আমাদের সকল উপকরণ সার্টিফাইড হালাল সাপ্লায়ার থেকে সংগ্রহ করা হয়।' },
                { q: 'কত দূর পর্যন্ত ডেলিভারি করো?',  a: 'সারা বাংলাদেশে ডেলিভারি করি। ঢাকায় একই দিন, অন্য জেলায় ২-৩ কার্যদিবস।' },
                { q: 'সমস্যা হলে কী করবো?',           a: 'ডেলিভারি পেয়েই যদি সমস্যা পান, আমাদের ২৪/৭ হেল্পলাইনে কল করুন। পূর্ণ রিফান্ড নিশ্চিত।' },
            ],
        }),
    },

    'checkout-food': {
        ...node('CheckoutWidget', {
            maxWidth: 560, bgColor: '#ffffff', padding: 32, borderRadius: 20,
            shadow: 'md', borderWidth: 1, borderColor: '#fdba74',
            showHeader: true, headerText: '🍽️ অর্ডার দিন — আজই পান',
            headerBgColor: '#ffedd5', headerTextColor: '#ea580c', headerSize: 20,
            showProductSummary: true, summaryLayout: 'row',
            showRating: true, ratingValue: 5, reviewCount: 892,
            showMultiProduct: false,
            showQuantity: true, showAddress: true, showDistrict: true, showNote: true,
            nameLabel: 'আপনার নাম', phoneLabel: 'ফোন নম্বর',
            addressLabel: 'ডেলিভারি ঠিকানা', districtLabel: 'জেলা',
            noteLabel: 'বিশেষ নির্দেশ (ঝাল কম/বেশি ইত্যাদি)', quantityLabel: 'পরিমাণ',
            formLayout: 'two-col',
            unitLabel: 'পিস', presetQuantities: '1, 2, 3, 5', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true,
            bundles: [
                { qty: 2, price: 499 },
                { qty: 3, price: 699 },
                { qty: 5, price: 999 },
            ],
            showDeliveryInfo: true, insideDhakaCharge: 0, outsideDhakaCharge: 80, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার নিশ্চিত করুন',
            buttonBgColor: '#ea580c', buttonTextColor: '#ffffff',
            buttonBorderRadius: 50, buttonSize: 'lg', buttonFullWidth: true,
            buttonIcon: '🍽️', buttonSubText: 'ঢাকায় আজই ডেলিভারি • ক্যাশ অন ডেলিভারি',
            showTrustBadges: true,
            trustBadges: [
                { icon: '🌿', text: '১০০% হালাল',         show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি',   show: true },
                { icon: '🚀', text: '৬০ মিনিট ডেলিভারি',  show: true },
                { icon: '↩️', text: 'সমস্যায় রিফান্ড',    show: true },
            ],
            showUrgency: true, urgencyText: '🔥 আজ রাত পর্যন্ত ফ্রি ডেলিভারি!',
            urgencyBgColor: '#ffedd5', urgencyTextColor: '#ea580c',
            showSocialProof: true,
            socialProofText: 'গত ১ ঘণ্টায় ৪৭ জন অর্ডার করেছেন',
            socialProofIcon: '🍽️',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true,
            mobileStickyText: '🍽️ এখনই অর্ডার করুন',
            mobileStickyBg: '#ffffff',
            themeColor: '#ea580c',
            labelColor: '#57534e', inputBorderColor: '#fdba74', inputBgColor: '#fffdfa',
        }),
    },
};