// resources/js/Features/PageBuilder/Templates/GadgetTemplate.js
import { node, container } from './helpers';

export const GADGET_TEMPLATE = {
    ROOT: container({ bgColor: '#f8fafc', bgType: 'color', gap: 0 }, [
        'hero-gadget', 'product-gadget', 'features-gadget',
        'countdown-gadget', 'testimonials-gadget', 'faq-gadget', 'checkout-gadget',
    ]),

    'hero-gadget': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#f8fafc',
            bgGradientTo: '#f1f5f9',
            bgGradientDirection: 160,
            minHeight: 600,
            paddingTop: 110, paddingBottom: 110, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center', contentMaxWidth: 900, contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '⚡ নতুন লঞ্চ — Pre-Order চলছে',
            badgeColor: '#0284c7', badgeBgColor: '#e0f2fe',
            title: 'প্রযুক্তির নতুন দিগন্ত\nআপনার হাতের মুঠোয়',
            titleSize: 62, titleWeight: '900', titleColor: '#0f172a',
            titleLineHeight: 1.08, titleLetterSpacing: -0.03,
            subtitle: 'সর্বাধুনিক প্রযুক্তি, অপ্রতিম পারফরম্যান্স এবং অতুলনীয় ডিজাইন — একটি গ্যাজেটে। এখন বাংলাদেশেও পাওয়া যাচ্ছে।',
            subtitleSize: 18, subtitleColor: '#475569', subtitleMaxWidth: 640, subtitleLineHeight: 1.65,
            showPrimaryBtn: true,
            primaryBtnText: '⚡ Pre-Order করুন',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#0284c7', primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#0284c7', primaryBtnBorderRadius: 6, primaryBtnSize: 'lg',
            showSecondaryBtn: true,
            secondaryBtnText: 'স্পেসিফিকেশন দেখুন',
            secondaryBtnUrl: '#features',
            secondaryBtnStyle: 'outline',
            secondaryBtnBgColor: '#0284c7',
            secondaryBtnTextColor: '#0284c7',
            secondaryBtnBorderColor: '#0284c7',
            secondaryBtnBorderRadius: 6, secondaryBtnSize: 'lg',
            showStats: true,
            stats: [
                { value: '10,000 mAh', label: 'ব্যাটারি ক্যাপাসিটি', show: true },
                { value: '65W',        label: 'ফাস্ট চার্জিং',        show: true },
                { value: '1 বছর',      label: 'ওয়ারেন্টি',            show: true },
            ],
            decorShape: 'grid', decorColor: '#38bdf8', decorOpacity: 20,
            animation: 'slideUp', animationDelay: '0',
        }),
    },

    'product-gadget': {
        ...node('ProductWidget', {
            layout: 'image-right', maxWidth: 1060,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            imageRatio: '1:1', imageBorderRadius: 16, imageShadow: 'lg',
            showGallery: true,
            showBadge: true, badgeText: 'NEW', badgeBg: '#0284c7', badgeColor: '#ffffff',
            showTitle: true, titleSize: 36, titleWeight: '800', titleColor: '#0f172a', titleLineHeight: 1.2,
            showPrice: true, priceColor: '#0284c7', priceSize: 40, priceWeight: '900',
            showOriginalPrice: true, showDiscountBadge: true, currencySymbol: '৳',
            showRating: true, ratingValue: 4.9, reviewCount: 3421, starColor: '#0284c7',
            showDescription: true, descriptionSize: 15, descriptionColor: '#475569', descriptionLines: 4,
            showSpecs: true,
            specs: [
                { icon: '📱', label: 'ডিসপ্লে',     value: '6.7" AMOLED 120Hz',              show: true },
                { icon: '🔋', label: 'ব্যাটারি',     value: '10,000 mAh + 65W Fast Charge',   show: true },
                { icon: '📸', label: 'ক্যামেরা',     value: '200MP AI Triple Camera',          show: true },
                { icon: '💾', label: 'স্টোরেজ',      value: '12GB RAM + 256GB ROM',           show: true },
                { icon: '🛡️', label: 'ওয়ারেন্টি',   value: '১ বছর অফিসিয়াল ওয়ারেন্টি',    show: true },
            ],
            showTrust: true,
            trustItems: [
                { icon: '✅', text: 'অফিসিয়াল ওয়ারেন্টি', bg: '#f0f9ff', color: '#0284c7', show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি',   bg: '#f0fdf4', color: '#16a34a', show: true },
                { icon: '↩️', text: '১৪ দিনের রিটার্ন',    bg: '#faf5ff', color: '#9333ea', show: true },
                { icon: '🔒', text: 'সিকিউর পেমেন্ট',       bg: '#fefce8', color: '#ca8a04', show: true },
            ],
            showStock: true, stockText: '⚡ মাত্র ২৩টি স্টকে বাকি!',
            stockBg: '#fffbeb', stockColor: '#d97706',
            showCta: true,
            ctaText: '⚡ এখনই অর্ডার করুন',
            ctaUrl: '#checkout', ctaBg: '#0284c7', ctaTextColor: '#ffffff',
            ctaRadius: 6, ctaSize: 'lg',
            ctaSubText: 'ক্যাশ অন ডেলিভারি • ১ বছর ওয়ারেন্টি',
            ctaBorderColor: '',
            animation: 'fadeUp',
        }),
    },

    'features-gadget': {
        ...node('FeaturesWidget', {
            sectionTitle: 'যা আপনি অন্য কোথাও পাবেন না',
            sectionSubtitle: 'প্রতিটি ফিচার ডিজাইন করা হয়েছে আপনার দৈনন্দিন জীবনকে আরো সহজ করার জন্য।',
            titleColor: '#0f172a', subtitleColor: '#475569',
            titleSize: 34, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'horizontal', gap: 20,
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#e2e8f0', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'sm', cardPadding: 28,
            iconShape: 'rounded', iconBg: '#e0f2fe', iconColor: '#0284c7', iconSize: 'md',
            itemTitleColor: '#0f172a', itemDescColor: '#475569',
            itemTitleSize: 16, itemDescSize: 14,
            showNumbers: false,
            items: [
                { title: '120Hz AMOLED ডিসপ্লে', description: 'সিনেমার মতো স্মুথ স্ক্রোলিং ও ভাইব্র্যান্ট কালার।', icon: '🖥️', iconBg: '', iconColor: '' },
                { title: '65W ফাস্ট চার্জিং',    description: 'মাত্র ৪০ মিনিটে ০ থেকে ১০০% চার্জ।',                icon: '⚡', iconBg: '', iconColor: '' },
                { title: '200MP AI ক্যামেরা',     description: 'রাতের অন্ধকারেও ক্রিস্টাল ক্লিয়ার ছবি।',           icon: '📸', iconBg: '', iconColor: '' },
                { title: 'IP68 ওয়াটারপ্রুফ',     description: '১.৫ মিটার গভীরতায় ৩০ মিনিট পানিরোধী।',              icon: '💧', iconBg: '', iconColor: '' },
                { title: 'AI পারফরম্যান্স চিপ',   description: 'সর্বাধুনিক প্রসেসর, গেমিং থেকে মাল্টিটাস্কিং।',    icon: '🧠', iconBg: '', iconColor: '' },
                { title: '১ বছর ওয়ারেন্টি',       description: 'অফিসিয়াল সার্ভিস সেন্টারে সম্পূর্ণ কভারেজ।',      icon: '🛡️', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.07',
        }),
    },

    'countdown-gadget': {
        ...node('CountdownWidget', {
            mode: 'fixed', targetDate: '',
            showDays: true,
            showHeadline: true,
            headline: '⚡ Pre-Order অফার শেষ হওয়ার আগেই বুক করুন!',
            headlineSize: 24, headlineColor: '#0f172a', headlineWeight: '800',
            showSubtitle: true,
            subtitle: 'Pre-Order করলে পাচ্ছেন এক্সক্লুসিভ লঞ্চ প্রাইস + ফ্রি ডেলিভারি।',
            subtitleColor: '#475569', subtitleSize: 15,
            expiredMessage: '⚠️ Pre-Order অফার শেষ।',
            displayStyle: 'card', boxSize: 'md',
            boxBg: '#ffffff', boxTextColor: '#0284c7',
            labelColor: '#475569', boxRadius: 8, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '🔥 Pre-Order করলে পাচ্ছেন ৩,০০০ টাকা ছাড় + ফ্রি ডেলিভারি!',
            urgencyBarBg: '#e0f2fe', urgencyBarText: '#0284c7',
            bgType: 'gradient', bgGradientFrom: '#f8fafc', bgGradientTo: '#f1f5f9', bgGradientDirection: 160,
            paddingTop: 56, paddingBottom: 56, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
        }),
    },

    'testimonials-gadget': {
        ...node('TestimonialWidget', {
            title: 'Early Adopters বলছেন',
            subtitle: 'যারা আগে অর্ডার করেছেন তাদের অভিজ্ঞতা।',
            bgColor: '#ffffff', padding: 60,
            layout: 'grid', cardStyle: 'bordered',
            starColor: '#0284c7', showVerified: true,
            reviews: [
                { name: 'তানভীর আহমেদ',    role: 'Software Engineer, ঢাকা', text: 'ফোনটা হাতে পেয়ে মুগ্ধ হয়ে গেলাম। ক্যামেরার কোয়ালিটি অবিশ্বাস্য। ব্যাটারি ২ দিন ব্যবহারের পরও শেষ হয় ক্যাম না!',               stars: 5, avatar: '' },
                { name: 'মাহমুদুল হক',      role: 'Content Creator, চট্টগ্রাম', text: 'ইউটিউবের জন্য ভিডিও করি। এই ফোনের সাথে আলাদা ক্যামেরা লাগে মহাশয়। ৪K ভিডিও অসাধারণ হচ্ছে।',                           stars: 5, avatar: '' },
                { name: 'সানজিদা ইসলাম',    role: 'Student, রাজশাহী',         text: 'দাম একটু বেশি মনে হয়েছিল কিন্তু এত ফিচার পেয়ে মনে হচ্ছে পয়সা উসুল। ডেলিভারিও ছিল দ্রুত।',                               stars: 5, avatar: '' },
            ],
        }),
    },

    'faq-gadget': {
        ...node('FaqWidget', {
            title: 'প্রশ্নোত্তর',
            subtitle: '',
            bgColor: '#f8fafc', padding: 60,
            accentColor: '#0284c7', iconStyle: 'arrow', layout: 'default',
            questions: [
                { q: 'ওয়ারেন্টি কীভাবে পাবো?',         a: 'আমাদের কাছ থেকে কেনার সাথে সাথে ১ বছরের অফিসিয়াল ওয়ারেন্টি কার্ড দেওয়া হবে। যেকোনো অথরাইজড সার্ভিস সেন্টারে ব্যবহারযোগ্য।' },
                { q: 'ইন্টারন্যাশনাল ভার্সন নাকি?',    a: 'না, এটি সম্পূর্ণ বাংলাদেশ অফিসিয়াল ভার্সন। বাংলাদেশ ব্যান্ড সাপোর্ট ও BTRC অ্যাপ্রুভড।' },
                { q: 'কত দিনে ডেলিভারি পাবো?',         a: 'ঢাকায় ১-২ কার্যদিবস, বাইরে ২-৪ কার্যদিবস। Pre-Order হলে নির্ধারিত লঞ্চ তারিখে ডেলিভারি।' },
                { q: 'পণ্যে সমস্যা হলে কী করবো?',      a: '১৪ দিনের মধ্যে যেকোনো সমস্যায় বিনামূল্যে রিপ্লেসমেন্ট বা রিফান্ড পাবেন।' },
                { q: 'EMI বা কিস্তিতে কেনার সুযোগ আছে কি?', a: 'ক্যাশ অন ডেলিভারি ছাড়াও bKash, Nagad ও ব্যাংক কার্ডে পেমেন্ট করা যাবে। EMI অপশন শীঘ্রই আসছে।' },
            ],
        }),
    },

    'checkout-gadget': {
        ...node('CheckoutWidget', {
            maxWidth: 560, bgColor: '#ffffff', padding: 32, borderRadius: 12,
            shadow: 'md', borderWidth: 1, borderColor: '#cbd5e1',
            showHeader: true, headerText: '⚡ অর্ডার ফর্ম',
            headerBgColor: '#e0f2fe', headerTextColor: '#0284c7', headerSize: 20,
            showProductSummary: true, summaryLayout: 'row',
            showRating: true, ratingValue: 5, reviewCount: 3421,
            showMultiProduct: false,
            showQuantity: true, showAddress: true, showDistrict: true, showNote: false,
            nameLabel: 'পূর্ণ নাম', phoneLabel: 'ফোন নম্বর',
            addressLabel: 'ডেলিভারি ঠিকানা', districtLabel: 'জেলা',
            noteLabel: 'বিশেষ নির্দেশ', quantityLabel: 'পরিমাণ',
            formLayout: 'two-col',
            unitLabel: 'পিস', presetQuantities: '1', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: false,
            showDeliveryInfo: true, insideDhakaCharge: 0, outsideDhakaCharge: 100, showDeliveryBreakdown: true,
            showVariants: true, variantLabel: 'কালার বেছে নিন',
            variantOptions: ['Midnight Black', 'Ocean Blue', 'Polar White'],
            buttonText: 'Pre-Order নিশ্চিত করুন',
            buttonBgColor: '#0284c7', buttonTextColor: '#ffffff',
            buttonBorderRadius: 6, buttonSize: 'lg', buttonFullWidth: true,
            buttonIcon: '⚡', buttonSubText: 'ক্যাশ অন ডেলিভারি • ১ বছর ওয়ারেন্টি • ফ্রি ডেলিভারি',
            showTrustBadges: true,
            trustBadges: [
                { icon: '✅', text: 'অফিসিয়াল ওয়ারেন্টি', show: true },
                { icon: '💵', text: 'COD সুবিধা',           show: true },
                { icon: '↩️', text: '১৪ দিনের রিটার্ন',    show: true },
                { icon: '🚚', text: 'ফ্রি ডেলিভারি',        show: true },
            ],
            showUrgency: true, urgencyText: '⚡ Pre-Order করলে ৩,০০০ টাকা বাঁচান!',
            urgencyBgColor: '#e0f2fe', urgencyTextColor: '#0284c7',
            showSocialProof: true,
            socialProofText: 'গত ২৪ ঘণ্টায় ৮৭৬ জন Pre-Order করেছেন',
            socialProofIcon: '⚡',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true,
            mobileStickyText: '⚡ Pre-Order করুন — COD',
            mobileStickyBg: '#ffffff',
            themeColor: '#0284c7',
            labelColor: '#475569', inputBorderColor: '#cbd5e1', inputBgColor: '#f8fafc',
        }),
    },
};