// resources/js/Features/PageBuilder/Templates/HealthTemplate.js
import { node, container } from './helpers';

export const HEALTH_TEMPLATE = {
    ROOT: container({ bgColor: '#faf9f6', bgType: 'color', gap: 0 }, [
        'hero-health', 'product-health', 'features-health',
        'testimonials-health', 'countdown-health', 'faq-health', 'checkout-health',
    ]),

    'hero-health': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#e8f5ec',
            bgGradientTo: '#faf9f6',
            bgGradientDirection: 145,
            minHeight: 560,
            paddingTop: 100, paddingBottom: 100, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center', contentMaxWidth: 800, contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '🌿 ১০০% প্রাকৃতিক • ডার্মাটোলজিস্ট অ্যাপ্রুভড',
            badgeColor: '#2d5240', badgeBgColor: '#d1eade',
            title: 'আপনার ত্বকের যত্নে\nপ্রকৃতির সেরা উপহার',
            titleSize: 58, titleWeight: '900', titleColor: '#1e3a2f',
            titleLineHeight: 1.1, titleLetterSpacing: -0.02,
            subtitle: 'রাসায়নিক মুক্ত, হার্বাল ফর্মুলায় তৈরি স্কিনকেয়ার প্রোডাক্ট। ৯০ দিনে দৃশ্যমান পরিবর্তন না হলে পূর্ণ রিফান্ড।',
            subtitleSize: 18, subtitleColor: '#4a7060', subtitleMaxWidth: 600, subtitleLineHeight: 1.7,
            showPrimaryBtn: true,
            primaryBtnText: '🌿 আজই শুরু করুন',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#2d5240', primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#2d5240', primaryBtnBorderRadius: 50, primaryBtnSize: 'lg',
            showSecondaryBtn: false,
            showStats: true,
            stats: [
                { value: '30,000+',  label: 'সন্তুষ্ট গ্রাহক',       show: true },
                { value: '৯০ দিন',   label: 'রিফান্ড গ্যারান্টি',     show: true },
                { value: '০টি',      label: 'ক্ষতিকর রাসায়নিক',     show: true },
            ],
            decorShape: 'blob-bl', decorColor: '#a8e6c0', decorOpacity: 30,
            animation: 'slideUp', animationDelay: '0',
        }),
    },

    'product-health': {
        ...node('ProductWidget', {
            layout: 'side-by-side', maxWidth: 1000,
            bgType: 'color', bgColor: '#faf9f6',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            imageRatio: '1:1', imageBorderRadius: 24, imageShadow: 'md',
            showGallery: true,
            showBadge: true, badgeText: '🌿 ন্যাচারাল', badgeBg: '#d1eade', badgeColor: '#1e3a2f',
            showTitle: true, titleSize: 30, titleWeight: '800', titleColor: '#1e3a2f', titleLineHeight: 1.25,
            showPrice: true, priceColor: '#2d5240', priceSize: 36, priceWeight: '800',
            showOriginalPrice: true, showDiscountBadge: true, currencySymbol: '৳',
            showRating: true, ratingValue: 4.9, reviewCount: 4128, starColor: '#2d5240',
            showDescription: true, descriptionSize: 15, descriptionColor: '#4a7060', descriptionLines: 4,
            showSpecs: true,
            specs: [
                { icon: '🌿', label: 'উপাদান',      value: '১০০% হার্বাল, প্যারাবেন ফ্রি',      show: true },
                { icon: '🔬', label: 'পরীক্ষিত',    value: 'ডার্মাটোলজিস্ট টেস্টেড',           show: true },
                { icon: '🧴', label: 'উপযুক্ত',     value: 'সব ধরনের ত্বকের জন্য',              show: true },
                { icon: '⏱️', label: 'ফলাফল',       value: '২-৪ সপ্তাহে দৃশ্যমান পরিবর্তন',    show: true },
                { icon: '🔒', label: 'গ্যারান্টি',   value: '৯০ দিনের মানি-ব্যাক গ্যারান্টি',  show: true },
            ],
            showTrust: true,
            trustItems: [
                { icon: '🌿', text: 'হার্বাল সার্টিফাইড',     bg: '#e8f5ec', color: '#2d5240', show: true },
                { icon: '🔬', text: 'ডার্মাটোলজিস্ট অ্যাপ্রুভড', bg: '#e8f0f5', color: '#1e3a5f', show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি',       bg: '#fff8e8', color: '#92400e', show: true },
                { icon: '↩️', text: '৯০ দিনের রিফান্ড',        bg: '#fdecea', color: '#991b1b', show: true },
            ],
            showStock: true, stockText: '🌿 এই সপ্তাহে মাত্র ৩০টি অর্ডার নেওয়া হবে',
            stockBg: '#e8f5ec', stockColor: '#2d5240',
            showCta: true,
            ctaText: '🌿 আজই অর্ডার করুন',
            ctaUrl: '#checkout', ctaBg: '#2d5240', ctaTextColor: '#ffffff',
            ctaRadius: 50, ctaSize: 'lg',
            ctaSubText: 'ক্যাশ অন ডেলিভারি • ৯০ দিনের মানি-ব্যাক গ্যারান্টি',
            ctaBorderColor: '',
            animation: 'fadeUp',
        }),
    },

    'features-health': {
        ...node('FeaturesWidget', {
            sectionTitle: 'কেন হাজার হাজার মানুষ বেছে নিচ্ছেন',
            sectionSubtitle: 'আমাদের পণ্য শুধু ত্বক উজ্জ্বল করে না — আপনার আত্মবিশ্বাসও বাড়ায়।',
            titleColor: '#1e3a2f', subtitleColor: '#4a7060',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 24,
            bgType: 'gradient', bgGradientFrom: '#faf9f6', bgGradientTo: '#e8f5ec', bgGradientDirection: 180,
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#a8e6c050', cardBorderWidth: 1,
            cardRadius: 20, cardShadow: 'sm', cardPadding: 32,
            iconShape: 'circle', iconBg: '#e8f5ec', iconColor: '#2d5240', iconSize: 'md',
            itemTitleColor: '#1e3a2f', itemDescColor: '#4a7060',
            itemTitleSize: 17, itemDescSize: 14,
            showNumbers: false,
            items: [
                { title: '১০০% প্রাকৃতিক',     description: 'কোনো ক্ষতিকর রাসায়নিক নেই। শুধু প্রকৃতির সেরা উপাদান।',           icon: '🌿', iconBg: '', iconColor: '' },
                { title: 'দ্রুত ফলাফল',         description: '৯৮% ব্যবহারকারী ২ সপ্তাহের মধ্যে উন্নতি দেখেছেন।',                icon: '⚡', iconBg: '', iconColor: '' },
                { title: 'সব ত্বকের জন্য',       description: 'শুষ্ক, তৈলাক্ত, সংবেদনশীল — সব ধরনের ত্বকে নিরাপদে ব্যবহারযোগ্য।', icon: '✨', iconBg: '', iconColor: '' },
                { title: 'ডার্মাটোলজিস্ট পরীক্ষিত', description: 'বিশেষজ্ঞ চর্মরোগ বিশেষজ্ঞ দ্বারা পরীক্ষিত ও অনুমোদিত।',       icon: '🔬', iconBg: '', iconColor: '' },
                { title: 'হালাল সার্টিফাইড',     description: 'সম্পূর্ণ হালাল উপাদানে তৈরি, মুসলিম ক্রেতাদের জন্য নিরাপদ।',     icon: '☪️', iconBg: '', iconColor: '' },
                { title: '৯০ দিনের গ্যারান্টি',  description: 'সন্তুষ্ট না হলে পূর্ণ রিফান্ড। কোনো প্রশ্ন নেই।',               icon: '🛡️', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.07',
        }),
    },

    'testimonials-health': {
        ...node('TestimonialWidget', {
            title: 'বাস্তব ফলাফল, বাস্তব মানুষ',
            subtitle: 'আমাদের গ্রাহকদের নিজেদের কথায়।',
            bgColor: '#faf9f6', padding: 60,
            layout: 'grid', cardStyle: 'bordered',
            starColor: '#2d5240', showVerified: true,
            reviews: [
                { name: 'রুবিনা পারভীন',  role: 'ঢাকা, বারিধারা',  text: '৩ সপ্তাহ ব্যবহারের পর মুখের দাগ অনেকটা কমে গেছে। কোনো পার্শ্বপ্রতিক্রিয়া নেই, ত্বক মসৃণ লাগছে।',   stars: 5, avatar: '' },
                { name: 'নাদিয়া ইসলাম',  role: 'রাজশাহী',          text: 'বিয়ের আগে দিয়ে অর্ডার করেছিলাম। ২ মাস ব্যবহারে ত্বকের উজ্জ্বলতা এত বেড়েছে যে সবাই জিজ্ঞেস করছে কী করছি!', stars: 5, avatar: '' },
                { name: 'শামীমা বেগম',    role: 'চট্টগ্রাম',         text: 'অনেক পণ্য ব্যবহার করেছি কিন্তু এটা সত্যিই আলাদা। ত্বক এখন অনেক টানটান আর উজ্জ্বল।',                stars: 5, avatar: '' },
            ],
        }),
    },

    'countdown-health': {
        ...node('CountdownWidget', {
            mode: 'evergreen', durationHours: 48,
            showDays: false,
            showHeadline: true,
            headline: '🌿 বিশেষ অফার — সীমিত সময়ের জন্য',
            headlineSize: 24, headlineColor: '#1e3a2f', headlineWeight: '800',
            showSubtitle: true,
            subtitle: 'এখন অর্ডার করলে পাচ্ছেন ফ্রি শিপিং + ফ্রি স্কিন কেয়ার গাইড।',
            subtitleColor: '#4a7060', subtitleSize: 15,
            expiredMessage: '⚠️ এই অফার শেষ হয়ে গেছে।',
            displayStyle: 'card', boxSize: 'md',
            boxBg: '#ffffff', boxTextColor: '#2d5240',
            labelColor: '#4a7060', boxRadius: 12, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '🌿 আজকের অর্ডারে পাচ্ছেন ফ্রি স্কিনকেয়ার বই!',
            urgencyBarBg: '#d1eade', urgencyBarText: '#1e3a2f',
            bgType: 'gradient', bgGradientFrom: '#faf9f6', bgGradientTo: '#e8f5ec', bgGradientDirection: 145,
            paddingTop: 56, paddingBottom: 56, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
        }),
    },

    'faq-health': {
        ...node('FaqWidget', {
            title: 'প্রশ্নোত্তর',
            subtitle: 'আপনার মনের প্রশ্নের উত্তর।',
            bgColor: '#e8f5ec', padding: 60,
            accentColor: '#2d5240', iconStyle: 'plus', layout: 'default',
            questions: [
                { q: 'পার্শ্বপ্রতিক্রিয়া কি আছে?',        a: 'আমাদের পণ্য ১০০% হার্বাল ও ডার্মাটোলজিস্ট পরীক্ষিত। সংবেদনশীল ত্বকেও নিরাপদে ব্যবহারযোগ্য।' },
                { q: 'কতদিনে ফলাফল দেখবো?',              a: '৯৮% ব্যবহারকারী ২ সপ্তাহের মধ্যে পরিবর্তন দেখেন। পূর্ণ ফলাফলের জন্য ৪-৮ সপ্তাহ নিয়মিত ব্যবহার করুন।' },
                { q: '৯০ দিনের গ্যারান্টি কীভাবে কাজ করে?', a: 'সন্তুষ্ট না হলে ৯০ দিনের মধ্যে আমাদের যোগাযোগ করুন। কোনো প্রশ্ন ছাড়াই পূর্ণ অর্থ ফেরত দেওয়া হবে।' },
                { q: 'গর্ভাবস্থায় ব্যবহার করা যাবে?',       a: 'গর্ভাবস্থায় ব্যবহারের আগে চিকিৎসকের পরামর্শ নিন। আমাদের বেশিরভাগ পণ্য সেফ কিন্তু নিশ্চিত হওয়া ভালো।' },
            ],
        }),
    },

    'checkout-health': {
        ...node('CheckoutWidget', {
            maxWidth: 560, bgColor: '#ffffff', padding: 32, borderRadius: 20,
            shadow: 'md', borderWidth: 1, borderColor: '#a8e6c050',
            showHeader: true, headerText: '🌿 আপনার স্কিনকেয়ার যাত্রা শুরু করুন',
            headerBgColor: '#e8f5ec', headerTextColor: '#2d5240', headerSize: 18,
            showProductSummary: true, summaryLayout: 'row',
            showRating: true, ratingValue: 5, reviewCount: 4128,
            showMultiProduct: false,
            showQuantity: true, showAddress: true, showDistrict: true, showNote: false,
            nameLabel: 'আপনার নাম', phoneLabel: 'ফোন নম্বর',
            addressLabel: 'ডেলিভারি ঠিকানা', districtLabel: 'জেলা',
            noteLabel: 'বিশেষ নির্দেশ', quantityLabel: 'পরিমাণ',
            formLayout: 'two-col',
            unitLabel: 'পিস', presetQuantities: '1, 2, 3', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true,
            bundles: [
                { qty: 2, price: 1400 },
                { qty: 3, price: 1950 },
            ],
            showDeliveryInfo: true, insideDhakaCharge: 0, outsideDhakaCharge: 60, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার করুন — ক্যাশ অন ডেলিভারি',
            buttonBgColor: '#2d5240', buttonTextColor: '#ffffff',
            buttonBorderRadius: 50, buttonSize: 'lg', buttonFullWidth: true,
            buttonIcon: '🌿', buttonSubText: '৯০ দিনের মানি-ব্যাক গ্যারান্টি • ফ্রি শিপিং',
            showTrustBadges: true,
            trustBadges: [
                { icon: '🌿', text: '১০০% হার্বাল',       show: true },
                { icon: '🔬', text: 'ডার্ম. অ্যাপ্রুভড',  show: true },
                { icon: '🛡️', text: '৯০ দিনের গ্যারান্টি', show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি',   show: true },
            ],
            showUrgency: false,
            showSocialProof: true,
            socialProofText: 'গত সপ্তাহে ১,২৩৪ জন অর্ডার করেছেন',
            socialProofIcon: '🌿',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true,
            mobileStickyText: '🌿 অর্ডার করুন — COD',
            mobileStickyBg: '#ffffff',
            themeColor: '#2d5240',
            labelColor: '#4a7060', inputBorderColor: '#a8e6c050', inputBgColor: '#faf9f6',
        }),
    },
};