// resources/js/Features/PageBuilder/Templates/IslamicPackageTemplate.js
import { node, container } from './helpers';

export const ISLAMIC_PACKAGE_TEMPLATE = {
    ROOT: container({ 
        bgColor: '#f8fafc', 
        bgType: 'color', 
        gap: 0, 
        paddingTop: 0, 
        paddingBottom: 0 
    }, [
        'hero-pkg', 
        'product-pkg', 
        'books-details-pkg',
        'gifts-pkg',
        'why-buy-pkg',
        'video-pkg',
        'testimonials-pkg',
        'countdown-pkg', 
        'faq-pkg', 
        'checkout-pkg',
    ]),

    'hero-pkg': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#064e3b', // Deep Emerald
            bgGradientTo: '#022c22',
            bgGradientDirection: 180,
            bgImage: '',
            overlayColor: '#000000',
            overlayOpacity: 20,
            minHeight: 650,
            paddingTop: 120,
            paddingBottom: 100,
            paddingLeft: 24,
            paddingRight: 24,
            contentAlign: 'center',
            contentMaxWidth: 900,
            contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '🔥 ধামাকা অফার — সাথে ১৪টি এক্সক্লুসিভ উপহার সম্পূর্ণ ফ্রি!',
            badgeColor: '#78350f',
            badgeBgColor: '#fef3c7',
            title: 'ইসলামিক মেগা বই প্যাকেজ\n৩০৫০ টাকার প্যাকেজ মাত্র ১২৫০ টাকায়!',
            titleSize: 52,
            titleWeight: '900',
            titleColor: '#ffffff',
            titleLineHeight: 1.2,
            titleLetterSpacing: -0.02,
            subtitle: 'আপনার এবং আপনার পরিবারের দ্বীনি জীবনকে সমৃদ্ধ করার জন্য সবচেয়ে প্রয়োজনীয় ৩টি বেস্টসেলার ইসলামিক বই এবং ১৪টি সুন্নতি উপহার এখন একসাথে পাচ্ছেন অবিশ্বাস্য দামে।',
            subtitleSize: 20,
            subtitleColor: '#d1fae5',
            subtitleMaxWidth: 750,
            subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '🛒 অর্ডার করুন — মাত্র ১২৫০ ৳',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#d97706', // Gold/Amber
            primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#d97706',
            primaryBtnBorderRadius: 8,
            primaryBtnSize: 'xl',
            showSecondaryBtn: true,
            secondaryBtnText: 'প্যাকেজে কী কী থাকছে দেখুন',
            secondaryBtnUrl: '#books',
            secondaryBtnStyle: 'outline',
            secondaryBtnBgColor: 'transparent',
            secondaryBtnTextColor: '#ffffff',
            secondaryBtnBorderColor: '#ffffff',
            secondaryBtnBorderRadius: 8,
            secondaryBtnSize: 'xl',
            showStats: true,
            stats: [
                { value: '৩টি', label: 'মূল্যবান বই', show: true, color: '#fcd34d' },
                { value: '১৪টি', label: 'ফ্রি উপহার', show: true, color: '#fcd34d' },
                { value: '৬০%+', label: 'বিশাল ছাড়', show: true, color: '#fcd34d' },
            ],
            decorShape: 'dots',
            decorColor: '#ffffff',
            decorOpacity: 10,
            animation: 'slideUp',
            animationDelay: '0',
        }),
    },

    'product-pkg': {
        ...node('BookWidget', {
            showTitle: true, showGallery: true, showDescription: true,
            showMeta: true, showWriter: false, showPublication: false,
            showPages: false, showLanguage: false,
            showPrice: true, showRating: true, showCta: true,
            titleOverride: 'মেগা ইসলামিক স্টার্টার প্যাক',
            writerName: '',
            publicationName: '',
            totalPages: '',
            language: '',
            descriptionOverride: 'একটি প্যাকেজেই পাচ্ছেন কালার কোডেড সহজ কুরআন, আর রাহীকুল মাখতূম এবং হিসনুল মুসলিম। সাথে ১৪টি সুন্নতি ও এক্সক্লুসিভ উপহার একেবারে ফ্রি! দ্বীনি জ্ঞান অর্জন শুরু করার জন্য এর চেয়ে দারুণ প্যাকেজ আর হতেই পারে না।',
            shortDescLength: 350,
            ratingValue: 5.0,
            reviewCount: 2450,
            starColor: '#d97706',
            currencySymbol: '৳',
            layout: 'row',
            maxWidth: 1060,
            metaStyle: 'grid', 
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            imageBorderRadius: 12, imageShadow: '2xl',
            titleSize: 36, titleWeight: '800', titleColor: '#064e3b',
            metaLabelColor: '#64748b', metaValueColor: '#0f172a',
            descColor: '#334155', descSize: 16, descLineHeight: 1.8,
            priceColor: '#d97706', priceSize: 42,
            ctaText: '🛍️ অফার মূল্যে অর্ডার করুন',
            ctaUrl: '#checkout',
            ctaBg: '#064e3b', ctaTextColor: '#ffffff', ctaRadius: 8,
            ctaFullWidth: true,
        }),
    },

    'books-details-pkg': {
        ...node('FeaturesWidget', {
            sectionTitle: 'প্যাকেজে যে ৩টি মূল্যবান বই থাকছে',
            sectionSubtitle: 'আপনার দৈনন্দিন জীবনের প্রতিটি ক্ষেত্রে এই বইগুলো সঠিক পথ দেখাবে।',
            titleColor: '#064e3b', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 32,
            bgType: 'color', bgColor: '#ecfdf5', // Very light emerald
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#a7f3d0', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'md', cardPadding: 40,
            iconShape: 'soft-square', iconBg: '#d1fae5', iconColor: '#064e3b', iconSize: 'xl',
            itemTitleColor: '#064e3b', itemDescColor: '#475569',
            itemTitleSize: 22, itemDescSize: 15, itemDescLineHeight: 1.6,
            showNumbers: false,
            items: [
                { title: '📖 কালার কোডেড সহজ কুরআন', description: 'কালার কোডেড তাজবীদ, বাংলা উচ্চারণ, বাংলা অনুবাদ এবং তিলাওয়াত শোনার জন্য মোবাইল QR স্ক্যানার সুবিধা সম্বলিত।', icon: '📖', iconBg: '', iconColor: '' },
                { title: '📘 আর রাহীকুল মাখতূম', description: 'নবীজির জন্ম থেকে ইন্তেকাল, মক্কা ও মদিনার দাওয়াতি সংগ্রাম এবং ইসলামের ইতিহাসের গুরুত্বপূর্ণ ঘটনাবহুল বিশ্ববিখ্যাত সিরাত গ্রন্থ।', icon: '🕌', iconBg: '', iconColor: '' },
                { title: '📗 হিসনুল মুসলিম', description: 'সকাল-সন্ধ্যা, ঘুম, খাবার, সফরসহ দৈনন্দিন জীবনের সবচেয়ে প্রয়োজনীয় দোয়া ও যিকিরের সহীহ হাদিস থেকে সংকলন।', icon: '🤲', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'gifts-pkg': {
        ...node('FeaturesWidget', {
            sectionTitle: '🎁 সাথে পাচ্ছেন ১৪টি এক্সক্লুসিভ উপহার (সম্পূর্ণ ফ্রি)',
            sectionSubtitle: 'এই প্যাকেজের সাথে দ্বীনি পরিবেশ গড়ার জন্য পাচ্ছেন দারুণ কিছু সুন্নতি উপহার।',
            titleColor: '#78350f', subtitleColor: '#78350f',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 5, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fef3c7', // Warm amber/gold bg
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fde68a', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fef3c7', iconColor: '#d97706', iconSize: 'lg',
            itemTitleColor: '#92400e', itemDescColor: '#475569',
            itemTitleSize: 16, itemDescSize: 14, itemDescLineHeight: 1.5,
            showNumbers: false,
            items: [
                { title: '১০টি সাহাবীদের জীবনী', description: 'সংক্ষিপ্ত পকেট সাইজ বই', icon: '📚', iconBg: '', iconColor: '' },
                { title: '১টি সুগন্ধি আতর', description: 'অ্যালকোহল মুক্ত', icon: '✨', iconBg: '', iconColor: '' },
                { title: '১টি সুন্নতি মেসওয়াক', description: 'অরিজিনাল জয়তুন', icon: '🌿', iconBg: '', iconColor: '' },
                { title: '১টি নামাজের টুপি', description: 'প্রিমিয়াম কোয়ালিটি', icon: '📿', iconBg: '', iconColor: '' },
                { title: '১টি কাঠের তসবিহ', description: 'যিকিরের জন্য', icon: '📿', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'why-buy-pkg': {
        ...node('FeaturesWidget', {
            sectionTitle: 'কেন এই প্যাকেজটি আপনার নেওয়া উচিত?',
            sectionSubtitle: '',
            titleColor: '#064e3b', subtitleColor: '#475569',
            titleSize: 30, subtitleSize: 16, headerAlign: 'center',
            columns: 2, layout: 'horizontal', gap: 24,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#f8fafc', cardBorderColor: '#e2e8f0', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'none', cardPadding: 24,
            iconShape: 'soft-square', iconBg: '#ecfdf5', iconColor: '#059669', iconSize: 'md',
            itemTitleColor: '#0f172a', itemDescColor: '#475569',
            itemTitleSize: 18, itemDescSize: 15, itemDescLineHeight: 1.5,
            showNumbers: false,
            items: [
                { title: 'পূর্ণাঙ্গ স্টার্টার প্যাক', description: 'দ্বীনি জ্ঞান অর্জনের জন্য সবচেয়ে দরকারি বইগুলোর কালেকশন।', icon: '✅', iconBg: '', iconColor: '' },
                { title: 'পারিবারিক শিক্ষা', description: 'পরিবার ও সন্তানদের ইসলামী শিক্ষার জন্য অত্যন্ত উপকারী।', icon: '✅', iconBg: '', iconColor: '' },
                { title: 'বিশাল ডিসকাউন্ট', description: '৩০৫০ টাকার প্যাকেজ পাচ্ছেন অর্ধেকের চেয়েও কম মূল্যে।', icon: '✅', iconBg: '', iconColor: '' },
                { title: 'বই + সুন্নতি উপহার', description: 'একই বক্সে বইয়ের পাশাপাশি জীবনের জন্য প্রয়োজনীয় সুন্নতি সামগ্রী।', icon: '✅', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'video-pkg': {
        ...node('VideoWidget', {
            sectionTitle: 'প্যাকেজের আনবক্সিং ভিডিও দেখে নিন',
            sectionSubtitle: 'অর্ডার করার আগে দেখে নিন প্যাকেজের ভেতর কী কী থাকছে এবং বইয়ের কোয়ালিটি কেমন।',
            titleColor: '#064e3b', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 
            platform: 'youtube',
            layout: 'center',
            maxWidth: 800,
            aspectRatio: '16/9',
            borderRadius: 16,
            shadow: '2xl',
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 60, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            showControls: true, autoplay: false, loop: false, muted: false,
        }),
    },

    'testimonials-pkg': {
        ...node('TestimonialWidget', {
            title: 'গ্রাহকদের রিভিউ',
            subtitle: 'যারা আমাদের থেকে এই প্যাকেজটি নিয়েছেন তাদের মতামত।',
            bgColor: '#ecfdf5', padding: 80,
            layout: 'grid', columns: 3, cardStyle: 'modern',
            starColor: '#d97706', showVerified: true,
            cardRadius: 16, cardShadow: 'sm',
            reviews: [
                { name: 'আব্দুর রহমান', role: 'ঢাকা', text: 'অসাধারণ একটি প্যাকেজ! মাত্র ১২৫০ টাকায় এতগুলো বই আর উপহার পাবো ভাবতেই পারিনি। আতরের ঘ্রাণটা খুব সুন্দর।', stars: 5, avatar: '' },
                { name: 'উম্মে হাবিবা', role: 'রাজশাহী', text: 'কুরআন শরীফের প্রিন্ট অনেক ঝকঝকে আর কিউআর কোড স্ক্যান করে তিলাওয়াত শোনার সিস্টেমটা খুব ভালো লেগেছে। পরিবারের সবাইকে উপহার দেওয়ার মতো।', stars: 5, avatar: '' },
                { name: 'মাহমুদুল হাসান', role: 'সিলেট', text: 'প্যাকেজিং খুবই ভালো ছিল। বইয়ের বাঁধাই উন্নতমানের। হিসনুল মুসলিম বইটি এখন আমার পকেটেই থাকে। জাযাকাল্লাহু খাইরান।', stars: 5, avatar: '' },
            ],
        }),
    },

    'countdown-pkg': {
        ...node('CountdownWidget', {
            mode: 'evergreen', durationHours: 24,
            showDays: false,
            showHeadline: true,
            headline: '⏳ মেগা অফারটি দ্রুত শেষ হয়ে যাচ্ছে!',
            headlineSize: 30, headlineColor: '#064e3b', headlineWeight: '900',
            showSubtitle: true,
            subtitle: '৩০৫০ টাকার প্যাকেজটি ১২৫০ টাকায় পেতে এখনি অর্ডার করুন।',
            subtitleColor: '#475569', subtitleSize: 16,
            expiredMessage: '⚠️ অফার শেষ হয়ে গেছে।',
            displayStyle: 'modern', boxSize: 'lg', 
            boxBg: '#ffffff', boxTextColor: '#064e3b',
            labelColor: '#475569', boxRadius: 12, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '🔥 খুবই সীমিত স্টক! স্টক শেষ হওয়ার আগেই অর্ডার করুন।',
            urgencyBarBg: '#fef2f2', urgencyBarText: '#991b1b',
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
            shadow: 'md',
        }),
    },

    'faq-pkg': {
        ...node('FaqWidget', {
            title: 'সাধারণ প্রশ্নোত্তর (FAQ)',
            subtitle: 'অর্ডার করার আগে আপনার মনের কনফিউশন দূর করুন।',
            bgColor: '#f8fafc', padding: 80,
            accentColor: '#064e3b', iconStyle: 'chevron', layout: 'accordion', 
            questions: [
                { q: 'প্যাকেজে মোট কয়টি বই থাকবে?', a: 'প্যাকেজে ৩টি মূল বই (কুরআন, আর রাহীকুল মাখতূম, হিসনুল মুসলিম) এবং ১০টি ছোট সাহাবীদের জীবনী বই সহ মোট ১৩টি বই থাকবে।' },
                { q: 'ডেলিভারি চার্জ কত এবং কয়দিন লাগে?', a: 'ঢাকার ভেতরে ডেলিভারি চার্জ ৬০ টাকা (১-২ দিন) এবং ঢাকার বাইরে ১২০ টাকা (২-৩ দিন)।' },
                { q: 'বই হাতে পেয়ে টাকা দেওয়ার সুযোগ আছে কি?', a: 'হ্যাঁ! ১০০% ক্যাশ অন ডেলিভারি। ডেলিভারিম্যানের কাছ থেকে পার্সেল বুঝে পেয়ে তারপর পেমেন্ট করবেন।' },
                { q: 'কুরআন মজিদ এর সাইজ কেমন?', a: 'এটি রেগুলার সাইজ যা সহজে হাতে নিয়ে পড়া যায় এবং কালার কোডেড তাজবীদ দেওয়া আছে।' },
            ],
        }),
    },

    'checkout-pkg': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 40, borderRadius: 16,
            shadow: '2xl', borderWidth: 1, borderColor: '#e2e8f0',
            showHeader: true, headerText: '🛍️ এখনই অর্ডার করুন',
            headerBgColor: '#ecfdf5', headerTextColor: '#064e3b', headerSize: 22,
            showProductSummary: true, summaryLayout: 'card', 
            showRating: true, ratingValue: 5, reviewCount: 2450,
            showMultiProduct: false, multiProductLabel: '',
            showQuantity: true, showAddress: true, showDistrict: true, showNote: true,
            nameLabel: 'আপনার নাম', phoneLabel: 'মোবাইল নাম্বার',
            addressLabel: 'সম্পূর্ণ ঠিকানা', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'অতিরিক্ত নির্দেশনা (যদি থাকে)', quantityLabel: 'প্যাকেজ সংখ্যা',
            formLayout: 'two-col',
            unitLabel: 'প্যাকেজ', presetQuantities: '1, 2, 3', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: false, 
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার কনফার্ম করুন (১২৫০ ৳)',
            buttonBgColor: '#064e3b', buttonTextColor: '#ffffff',
            buttonBorderRadius: 8, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '🚀', buttonSubText: '৩০৫০ টাকার প্যাকেজ পাচ্ছেন মাত্র ১২৫০ টাকায়',
            showTrustBadges: true,
            trustBadges: [
                { icon: '📦', text: 'ক্যাশ অন ডেলিভারি', show: true },
                { icon: '🚚', text: 'সারা দেশে হোম ডেলিভারি', show: true },
                { icon: '💯', text: 'অরিজিনাল প্রোডাক্ট', show: true },
            ],
            showUrgency: true, urgencyText: '🔥 স্টক শেষ হওয়ার আগেই অর্ডার করে ফেলুন!',
            urgencyBgColor: '#fef2f2', urgencyTextColor: '#991b1b',
            showSocialProof: true,
            socialProofText: 'আজকে ৪৭ জন এই প্যাকেজটি অর্ডার করেছেন',
            socialProofIcon: '🔥',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true, 
            mobileStickyText: '🛒 অর্ডার করুন — ১২৫০ ৳',
            mobileStickyBg: '#ffffff',
            themeColor: '#064e3b',
            labelColor: '#334155', inputBorderColor: '#cbd5e1', inputBgColor: '#f8fafc', inputRadius: 8,
        }),
    },
};