// resources/js/Features/PageBuilder/Templates/KalmiMaryamTemplate.js
import { node, container } from './helpers';

export const KALMI_MARYAM_TEMPLATE = {
    ROOT: container({ bgColor: '#fefce8', bgType: 'color', gap: 0, paddingTop: 0, paddingBottom: 0 }, [
        'hero-kalmi', 
        'problem-kalmi', 
        'product-kalmi', 
        'breakdown-kalmi', 
        'benefits-kalmi', 
        'why-us-kalmi',
        'testimonials-kalmi', 
        'countdown-kalmi', 
        'checkout-kalmi',
    ]),

    // 1️⃣ Hero Section
    'hero-kalmi': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#fefce8',
            bgGradientTo: '#fef3c7',
            bgGradientDirection: 145,
            minHeight: 520,
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center', contentMaxWidth: 850, contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '⭐ প্রিমিয়াম গ্রেড',
            badgeColor: '#78350f', badgeBgColor: '#fde68a',
            title: 'অরিজিনাল সৌদি\nকলমি মরিয়ম খেজুর',
            titleSize: 52, titleWeight: '900', titleColor: '#451a03',
            titleLineHeight: 1.15, titleLetterSpacing: -0.02,
            subtitle: 'গাঢ় কালচে বাদামী রঙের, পুষ্টিতে ভরপুর এবং চিবিয়ে খাওয়ার মতো মজাদার অরিজিনাল কলমি মরিয়ম (সাফাউই) খেজুর।',
            subtitleSize: 18, subtitleColor: '#78350f', subtitleMaxWidth: 700, subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '🛒 অফার মূল্যে অর্ডার করুন',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#78350f', primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#78350f', primaryBtnBorderRadius: 50, primaryBtnSize: 'xl',
            showSecondaryBtn: false,
            showStats: true,
            stats: [
                { value: '১০০%', label: 'অরিজিনাল সৌদি পণ্য',  show: true },
                { value: 'ফ্রেশ', label: 'চিবিয়ে খাওয়ার মজা',     show: true },
                { value: 'ন্যাচারাল', label: 'কোনো প্রিজারভেটিভ নেই', show: true },
            ],
            decorShape: 'blob-tr', decorColor: '#fde68a', decorOpacity: 40,
            animation: 'slideUp', animationDelay: '0',
        }),
    },

    // 2️⃣ Problem Section
    'problem-kalmi': {
        ...node('FeaturesWidget', {
            sectionTitle: 'সস্তা ও নিম্নমানের খেজুর কিনে ঠকছেন?',
            sectionSubtitle: 'বাজারের সাধারণ কলমি খেজুর কিনে যেসব সাধারণ সমস্যার সম্মুখীন হতে হয়:',
            titleColor: '#dc2626', subtitleColor: '#78350f',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#fff1f2', cardBorderColor: '#ffe4e6', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#ffe4e6', iconColor: '#dc2626', iconSize: 'md',
            itemTitleColor: '#451a03', itemDescColor: '#78350f',
            itemTitleSize: 16, itemDescSize: 15,
            showNumbers: false,
            items: [
                { title: 'নকল ও মিক্সড খেজুর', description: 'আসল কলমির বদলে কমদামি কালো খেজুর মিক্স করে বিক্রি করা হয় অহরহ।', icon: '❌', iconBg: '', iconColor: '' },
                { title: 'অতিরিক্ত শক্ত', description: 'অনেক দিনের পুরোনো খেজুরগুলো শুকিয়ে শক্ত কাঠের মতো হয়ে যায়, যা খাওয়া কঠিন।', icon: '❌', iconBg: '', iconColor: '' },
                { title: 'প্রিজারভেটিভ যুক্ত', description: 'খেজুর দীর্ঘদিন কালচে ও চকচকে রাখতে ক্ষতিকর রাসায়নিক ব্যবহার করা হয়।', icon: '❌', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    // 3️⃣ Product Intro
    'product-kalmi': {
        ...node('ProductWidget', {
            layout: 'side-by-side', maxWidth: 1000,
            bgType: 'color', bgColor: '#fefce8',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            imageRatio: '4:3', imageBorderRadius: 20, imageShadow: 'lg',
            showGallery: true,
            showBadge: true, badgeText: '৩৫০ টাকা ছাড়!', badgeBg: '#dc2626', badgeColor: '#ffffff',
            showTitle: true, titleSize: 32, titleWeight: '800', titleColor: '#451a03', titleLineHeight: 1.25,
            showPrice: true, priceColor: '#78350f', priceSize: 42, priceWeight: '900',
            showOriginalPrice: true, originalPrice: 1300, showDiscountBadge: true, currencySymbol: '৳',
            showRating: true, ratingValue: 4.8, reviewCount: 1120, starColor: '#f59e0b',
            showDescription: true, descriptionSize: 16, descriptionColor: '#78350f', descriptionLines: 6,
            descriptionText: 'কলমি মরিয়ম বা সাফাউই (Safawi) খেজুর সৌদি আরবের মদিনায় উৎপাদিত অন্যতম জনপ্রিয় একটি খেজুর। এর রঙ গাঢ় কালচে বাদামী এবং এটি সাইজে বেশ বড় ও মাংসল হয়।\n\nএটি খুব বেশি নরম নয়, বরং এর আঁশযুক্ত টেক্সচারের কারণে চিবিয়ে খেতে দারুণ লাগে। এর মিষ্টি স্বাদও একদম পারফেক্ট, যা সহজেই এনার্জি বুস্ট করতে সাহায্য করে।',
            showSpecs: true,
            specs: [
                { icon: '🌴', label: 'উৎস',    value: 'সৌদি আরব (মদিনা)', show: true },
                { icon: '⚖️', label: 'পরিমাণ', value: '১ কেজি (নেট ওজন)', show: true },
                { icon: '✨', label: 'গ্রেড', value: 'ভিআইপি গ্রেড', show: true },
            ],
            showTrust: true,
            trustItems: [
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি', bg: '#fff7ed', color: '#ea580c', show: true },
                { icon: '🔍', text: 'প্যাকেট খুলে চেক করার সুযোগ', bg: '#f0fdf4', color: '#16a34a', show: true },
            ],
            showStock: true, stockText: '📦 স্টক সীমিত! দ্রুত অর্ডার করুন', stockBg: '#fee2e2', stockColor: '#dc2626',
            showCta: true,
            ctaText: '🛒 ৯৫০ টাকায় অর্ডার করুন',
            ctaUrl: '#checkout', ctaBg: '#78350f', ctaTextColor: '#ffffff',
            ctaRadius: 50, ctaSize: 'lg',
            ctaSubText: 'রেগুলার প্রাইস: ১৩০০৳ | আজকের অফার: ৯৫০৳',
            animation: 'fadeUp',
        }),
    },

    // 4️⃣ Breakdown Section
    'breakdown-kalmi': {
        ...node('FeaturesWidget', {
            sectionTitle: 'কলমি খেজুরের বিশেষত্ব',
            sectionSubtitle: 'কেন এটি সবার এতো পছন্দের?',
            titleColor: '#451a03', subtitleColor: '#78350f',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#fefce8', cardBorderColor: '#fde68a', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fef3c7', iconColor: '#78350f', iconSize: 'xl',
            itemTitleColor: '#451a03', itemDescColor: '#78350f',
            itemTitleSize: 18, itemDescSize: 14,
            showNumbers: false,
            items: [
                { title: 'গাঢ় কালচে রঙ', description: 'এর আকর্ষণীয় গাঢ় কালচে বাদামী রঙ একে অন্যান্য খেজুর থেকে সহজেই আলাদা করে।', icon: '🎨', iconBg: '', iconColor: '' },
                { title: 'চিবিয়ে খাওয়ার মজা', description: 'কলমি খেজুরের মাংসল অংশটি বেশ আঁশযুক্ত, তাই এটি চিবিয়ে খেতে অসাধারণ লাগে।', icon: '🤤', iconBg: '', iconColor: '' },
                { title: 'দারুণ মিষ্টি স্বাদ', description: 'যাঁরা মাঝারি ও পরিমিত মিষ্টি পছন্দ করেন, কলমি খেজুর তাঁদের জন্য সেরা একটি পছন্দ।', icon: '🍯', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    // 5️⃣ Benefits Section
    'benefits-kalmi': {
        ...node('FeaturesWidget', {
            sectionTitle: 'কলমি খেজুরের স্বাস্থ্য উপকারিতা',
            sectionSubtitle: 'প্রতিদিন কলমি খেজুর খেলে কী কী উপকার পাবেন?',
            titleColor: '#451a03', subtitleColor: '#78350f',
            titleSize: 28, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fefce8',
            paddingTop: 60, paddingBottom: 40, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fde68a', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fef3c7', iconColor: '#78350f', iconSize: 'lg',
            itemTitleColor: '#451a03', itemDescColor: '#78350f',
            itemTitleSize: 18, itemDescSize: 15,
            showNumbers: false,
            items: [
                { title: 'রক্তশূন্যতা দূর করে', description: 'এতে প্রচুর পরিমাণে আয়রন থাকে, যা শরীরের রক্তশূন্যতা দূর করতে সহায়তা করে।', icon: '🩸', iconBg: '', iconColor: '' },
                { title: 'হজম শক্তি বাড়ায়', description: 'ফাইবার সমৃদ্ধ হওয়ায় এটি পেটের সমস্যা ও কোষ্ঠকাঠিন্য দূর করতে দারুণ কাজ করে।', icon: '🌿', iconBg: '', iconColor: '' },
                { title: 'ইনস্ট্যান্ট এনার্জি', description: 'সারাদিনের ক্লান্তি শেষে নিমিষেই শরীরে এনার্জি ফিরিয়ে আনতে সাহায্য করে।', icon: '⚡', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    // Extra: Why Us
    'why-us-kalmi': {
        ...node('FeaturesWidget', {
            sectionTitle: 'আমাদের থেকে কেন নিবেন?',
            sectionSubtitle: '১০০% অরিজিনাল সৌদি খেজুরের নিশ্চয়তা',
            titleColor: '#451a03', subtitleColor: '#78350f',
            titleSize: 28, subtitleSize: 16, headerAlign: 'center',
            columns: 2, layout: 'horizontal', gap: 20,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 40, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#fefce8', cardBorderColor: '#fde68a', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fef3c7', iconColor: '#78350f', iconSize: 'md',
            itemTitleColor: '#451a03', itemDescColor: '#78350f',
            itemTitleSize: 16, itemDescSize: 14,
            showNumbers: true,
            items: [
                { title: 'সরাসরি আমদানি', description: 'আমরা কোনো থার্ড পার্টি ছাড়া সরাসরি সৌদি আরব থেকে খেজুর ইম্পোর্ট করি।', icon: '🇸🇦', iconBg: '', iconColor: '' },
                { title: 'চেক করে পেমেন্ট', description: 'ডেলিভারি ম্যানের সামনে প্যাকেট খুলে খেজুরের মান চেক করে রিসিভ করতে পারবেন।', icon: '🔍', iconBg: '', iconColor: '' },
                { title: 'কেমিক্যাল মুক্ত', description: 'দীর্ঘদিন সংরক্ষণের জন্য আমরা কোনো প্রকার ক্ষতিকর রাসায়নিক ব্যবহার করি না।', icon: '🛡️', iconBg: '', iconColor: '' },
                { title: 'মানি ব্যাক গ্যারান্টি', description: 'খেজুরের কোয়ালিটি নিয়ে কোনো অভিযোগ থাকলে সাথে সাথে ফেরত দিতে পারবেন।', icon: '↩️', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    // 6️⃣ Social Proof Section
    'testimonials-kalmi': {
        ...node('TestimonialWidget', {
            title: 'গ্রাহকদের রিভিউ',
            subtitle: 'যাঁরা আমাদের কলমি মরিয়ম কিনেছেন তাঁদের অভিজ্ঞতা',
            bgColor: '#fefce8', padding: 60,
            layout: 'grid', columns: 2, cardStyle: 'border', borderColor: '#fde68a',
            starColor: '#f59e0b', showVerified: true,
            reviews: [
                { name: 'মাহমুদ হাসান', role: 'ঢাকা', text: 'কলমি খেজুর আমার সবসময়ই পছন্দ। কিন্তু অনেক জায়গায় কিনে দেখেছি সেগুলো বেশ শক্ত থাকে। আপনাদের খেজুরগুলো একদম পারফেক্ট, চিবিয়ে খেতে দারুণ মজা লেগেছে।', stars: 5, avatar: '' },
                { name: 'সাদিয়া আফরিন', role: 'সিলেট', text: 'আগে অন্য পেজ থেকে কিনে প্রতারিত হয়েছিলাম। আপনাদের প্যাকেজিং এবং খেজুরের কালার দেখেই বোঝা যায় এটা একদম অরিজিনাল। অনেক অনেক ধন্যবাদ।', stars: 5, avatar: '' },
            ],
        }),
    },

    // 7️⃣ Offer + Urgency Section
    'countdown-kalmi': {
        ...node('CountdownWidget', {
            mode: 'daily',
            showDays: false,
            showHeadline: true,
            headline: '🎁 আজকের স্পেশাল অফার!',
            headlineSize: 28, headlineColor: '#dc2626', headlineWeight: '800',
            showSubtitle: true,
            subtitle: 'অরিজিনাল কলমি মরিয়ম - Regular Price: 1300৳ | Today Price: 950৳',
            subtitleColor: '#451a03', subtitleSize: 18,
            expiredMessage: '⚠️ আজকের স্পেশাল অফার শেষ হয়েছে।',
            displayStyle: 'card', boxSize: 'md',
            boxBg: '#ffffff', boxTextColor: '#78350f',
            labelColor: '#78350f', boxRadius: 16, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '📦 স্টক খুব দ্রুত শেষ হয়ে যাচ্ছে। এখনই অর্ডার করুন!',
            urgencyBarBg: '#fee2e2', urgencyBarText: '#dc2626',
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 40, paddingBottom: 40, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
        }),
    },

    // 8️⃣ Checkout Section
    'checkout-kalmi': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 32, borderRadius: 20,
            shadow: '2xl', borderWidth: 2, borderColor: '#78350f', 
            showHeader: true, headerText: '🛒 অফার মূল্যে অর্ডার কনফার্ম করুন',
            headerBgColor: '#fef3c7', headerTextColor: '#78350f', headerSize: 22,
            showProductSummary: true, summaryLayout: 'row',
            showRating: true, ratingValue: 4.8, reviewCount: 1120,
            showMultiProduct: false,
            showQuantity: true, showAddress: true, showDistrict: true, showNote: false,
            nameLabel: 'আপনার নাম', phoneLabel: 'মোবাইল নাম্বার',
            addressLabel: 'সম্পূর্ণ ঠিকানা', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'বিশেষ নির্দেশ', quantityLabel: 'পরিমাণ (কেজি)',
            formLayout: 'two-col',
            unitLabel: 'কেজি', presetQuantities: '1, 2, 3, 5', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true,
            bundles: [
                { qty: 1, price: 950, highlight: false, badge: '' }, 
                { qty: 2, price: 1850, highlight: true, badge: 'জনপ্রিয় অফার' }, 
                { qty: 5, price: 4600, highlight: false, badge: 'সুপার সেভার' },
            ],
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার কনফার্ম করুন ৳৯৫০',
            buttonBgColor: '#78350f', buttonTextColor: '#ffffff',
            buttonBorderRadius: 50, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '✅', buttonSubText: 'সারা বাংলাদেশে ক্যাশ অন ডেলিভারি',
            showTrustBadges: true,
            trustBadges: [
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি',   show: true },
                { icon: '🔍', text: 'চেক করে নেওয়ার সুযোগ', show: true },
            ],
            showUrgency: true, urgencyText: '⚡ দ্রুত আপনার নাম ও ঠিকানা লিখে অর্ডার কনফার্ম করুন!',
            urgencyBgColor: '#fef3c7', urgencyTextColor: '#b45309',
            showSocialProof: true,
            socialProofText: 'গত ১ ঘণ্টায় ২৫ জন অর্ডার কনফার্ম করেছেন',
            socialProofIcon: '🔥',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true, 
            mobileStickyText: '🛒 অর্ডার করুন (৳৯৫০)',
            mobileStickyBg: '#ffffff',
            themeColor: '#78350f',
            labelColor: '#451a03', inputBorderColor: '#fde68a', inputBgColor: '#fefce8',
        }),
    },
};