// resources/js/Features/PageBuilder/Templates/MabroomMaryamTemplate.js
import { node, container } from './helpers';

export const MABROOM_MARYAM_TEMPLATE = {
    ROOT: container({ bgColor: '#fdf8f6', bgType: 'color', gap: 0, paddingTop: 0, paddingBottom: 0 }, [
        'hero-mabroom', 
        'problem-mabroom', 
        'product-mabroom', 
        'breakdown-mabroom', 
        'benefits-mabroom', 
        'why-us-mabroom',
        'testimonials-mabroom', 
        'countdown-mabroom', 
        'checkout-mabroom',
    ]),

    // 1️⃣ Hero Section
    'hero-mabroom': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#fdf8f6',
            bgGradientTo: '#fee2e2',
            bgGradientDirection: 145,
            minHeight: 520,
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center', contentMaxWidth: 850, contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '✨ প্রিমিয়াম কোয়ালিটি',
            badgeColor: '#991b1b', badgeBgColor: '#fecdd3',
            title: 'অরিজিনাল সৌদি\nমাবরুম মরিয়ম খেজুর',
            titleSize: 52, titleWeight: '900', titleColor: '#450a0a',
            titleLineHeight: 1.15, titleLetterSpacing: -0.02,
            subtitle: 'লম্বাটে, মাংসল এবং চিবিয়ে খাওয়ার মতো অসাধারণ স্বাদের প্রিমিয়াম খেজুর। যারা অতিরিক্ত মিষ্টি অপছন্দ করেন, তাদের জন্য সেরা পছন্দ।',
            subtitleSize: 18, subtitleColor: '#7f1d1d', subtitleMaxWidth: 700, subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '🛒 অফার মূল্যে অর্ডার করুন',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#991b1b', primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#991b1b', primaryBtnBorderRadius: 50, primaryBtnSize: 'xl',
            showSecondaryBtn: false,
            showStats: true,
            stats: [
                { value: '১০০%', label: 'অরিজিনাল সৌদি পণ্য',  show: true },
                { value: 'পরিমিত', label: 'প্রাকৃতিক মিষ্টি',     show: true },
                { value: 'ফ্রেশ', label: 'কোয়ালিটি গ্যারান্টি', show: true },
            ],
            decorShape: 'blob-tr', decorColor: '#fca5a5', decorOpacity: 30,
            animation: 'slideUp', animationDelay: '0',
        }),
    },

    // 2️⃣ Problem Section
    'problem-mabroom': {
        ...node('FeaturesWidget', {
            sectionTitle: 'অতিরিক্ত মিষ্টি খেজুর খেতে পারেন না?',
            sectionSubtitle: 'বাজারের সাধারণ মরিয়ম খেজুর নিয়ে যেসব সমস্যায় পড়েন:',
            titleColor: '#dc2626', subtitleColor: '#7f1d1d',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fff1f2',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fecdd3', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fee2e2', iconColor: '#dc2626', iconSize: 'md',
            itemTitleColor: '#450a0a', itemDescColor: '#7f1d1d',
            itemTitleSize: 16, itemDescSize: 15,
            showNumbers: false,
            items: [
                { title: 'অতিরিক্ত কড়া মিষ্টি', description: 'অনেকেই অতিরিক্ত মিষ্টি খেজুর খেতে পারেন না বা স্বাস্থ্যের জন্য এড়িয়ে চলেন।', icon: '❌', iconBg: '', iconColor: '' },
                { title: 'নকল মরিয়ম খেজুর', description: 'আসল মাবরুম মরিয়মের নামে সাধারণ লম্বা খেজুর বিক্রি হয় অহরহ।', icon: '❌', iconBg: '', iconColor: '' },
                { title: 'শুকনো ও শক্ত', description: 'দীর্ঘদিন ফেলে রাখা খেজুর শক্ত হয়ে যায়, যা চিবিয়ে খাওয়া কষ্টকর।', icon: '❌', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    // 3️⃣ Product Intro
    'product-mabroom': {
        ...node('ProductWidget', {
            layout: 'side-by-side', maxWidth: 1000,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            imageRatio: '4:3', imageBorderRadius: 20, imageShadow: 'lg',
            showGallery: true,
            showBadge: true, badgeText: '৩০০ টাকা ছাড়!', badgeBg: '#dc2626', badgeColor: '#ffffff',
            showTitle: true, titleSize: 32, titleWeight: '800', titleColor: '#450a0a', titleLineHeight: 1.25,
            showPrice: true, priceColor: '#991b1b', priceSize: 42, priceWeight: '900',
            showOriginalPrice: true, originalPrice: 1500, showDiscountBadge: true, currencySymbol: '৳',
            showRating: true, ratingValue: 4.9, reviewCount: 940, starColor: '#f59e0b',
            showDescription: true, descriptionSize: 16, descriptionColor: '#7f1d1d', descriptionLines: 6,
            descriptionText: 'মাবরুম (Mabroom) খেজুর সৌদি আরবের অন্যতম জনপ্রিয় এবং প্রিমিয়াম একটি খেজুর। এর রঙ গাঢ় লালচে বাদামী, সাইজে লম্বা এবং দেখতে অত্যন্ত আকর্ষণীয়।\n\nএটি চিবিয়ে খেতে দারুণ মজা। যারা অতিরিক্ত কড়া মিষ্টি পছন্দ করেন না, তাদের জন্য মাবরুম খেজুর সেরা একটি এনার্জি সোর্স।',
            showSpecs: true,
            specs: [
                { icon: '🌴', label: 'উৎস',    value: 'সৌদি আরব (মদিনা)', show: true },
                { icon: '⚖️', label: 'পরিমাণ', value: '১ কেজি (নেট ওজন)', show: true },
                { icon: '✨', label: 'গ্রেড', value: 'ভিআইপি (বড় সাইজ)', show: true },
            ],
            showTrust: true,
            trustItems: [
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি', bg: '#fff7ed', color: '#ea580c', show: true },
                { icon: '🔍', text: 'প্যাকেট খুলে চেক করার সুযোগ', bg: '#f0fdf4', color: '#16a34a', show: true },
            ],
            showStock: true, stockText: '📦 স্টক সীমিত! দ্রুত অর্ডার করুন', stockBg: '#fee2e2', stockColor: '#dc2626',
            showCta: true,
            ctaText: '🛒 ১২০০ টাকায় অর্ডার করুন',
            ctaUrl: '#checkout', ctaBg: '#991b1b', ctaTextColor: '#ffffff',
            ctaRadius: 50, ctaSize: 'lg',
            ctaSubText: 'রেগুলার প্রাইস: ১৫০০৳ | আজকের অফার: ১২০০৳',
            animation: 'fadeUp',
        }),
    },

    // 4️⃣ Breakdown Section
    'breakdown-mabroom': {
        ...node('FeaturesWidget', {
            sectionTitle: 'মাবরুম মরিয়ম খেজুরের বিশেষত্ব',
            sectionSubtitle: 'কেন এটি অন্যান্য খেজুর থেকে আলাদা?',
            titleColor: '#450a0a', subtitleColor: '#7f1d1d',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fdf8f6',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fecdd3', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fee2e2', iconColor: '#991b1b', iconSize: 'xl',
            itemTitleColor: '#450a0a', itemDescColor: '#7f1d1d',
            itemTitleSize: 18, itemDescSize: 14,
            showNumbers: false,
            items: [
                { title: 'লম্বা ও মাংসল সাইজ', description: 'দেখতে বেশ লম্বাটে এবং ভেতরে প্রচুর মাংসল অংশ থাকে যা খেতে তৃপ্তিদায়ক।', icon: '📏', iconBg: '', iconColor: '' },
                { title: 'চিবিয়ে খাওয়ার মজা', description: 'এর বাইরের স্কিন কিছুটা শক্ত হলেও ভেতরটা নরম, তাই চিবিয়ে খেতে দারুণ লাগে।', icon: '🤤', iconBg: '', iconColor: '' },
                { title: 'পরিমিত মিষ্টি স্বাদ', description: 'সুক্কারি বা অন্যান্য খেজুরের মতো কড়া মিষ্টি নয়, বরং সহনীয় ও মজাদার মিষ্টি।', icon: '🍯', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    // 5️⃣ Benefits Section
    'benefits-mabroom': {
        ...node('FeaturesWidget', {
            sectionTitle: 'মাবরুম খেজুরের স্বাস্থ্য উপকারিতা',
            sectionSubtitle: 'প্রতিদিন মাবরুম খেজুর খেলে কী কী উপকার পাবেন?',
            titleColor: '#450a0a', subtitleColor: '#7f1d1d',
            titleSize: 28, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 60, paddingBottom: 40, paddingLeft: 24, paddingRight: 24,
            cardBg: '#fff1f2', cardBorderColor: '#fecdd3', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fee2e2', iconColor: '#991b1b', iconSize: 'lg',
            itemTitleColor: '#450a0a', itemDescColor: '#7f1d1d',
            itemTitleSize: 18, itemDescSize: 15,
            showNumbers: false,
            items: [
                { title: 'দীর্ঘস্থায়ী এনার্জি', description: 'সারাদিন কাজের জন্য শরীরে দীর্ঘস্থায়ী শক্তি যোগাতে সাহায্য করে।', icon: '⚡', iconBg: '', iconColor: '' },
                { title: 'অ্যান্টিঅক্সিডেন্ট সমৃদ্ধ', description: 'প্রচুর অ্যান্টিঅক্সিডেন্ট থাকায় রোগ প্রতিরোধ ক্ষমতা কয়েকগুণ বাড়িয়ে দেয়।', icon: '🛡️', iconBg: '', iconColor: '' },
                { title: 'কোষ্ঠকাঠিন্য দূর করে', description: 'উচ্চ মাত্রার ফাইবার থাকায় হজম শক্তি বাড়ায় ও পেট পরিষ্কার রাখে।', icon: '🌿', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    // Extra: Why Us
    'why-us-mabroom': {
        ...node('FeaturesWidget', {
            sectionTitle: 'আমাদের থেকে কেন নিবেন?',
            sectionSubtitle: '১০০% অরিজিনাল মাবরুম খেজুরের নিশ্চয়তা',
            titleColor: '#450a0a', subtitleColor: '#7f1d1d',
            titleSize: 28, subtitleSize: 16, headerAlign: 'center',
            columns: 2, layout: 'horizontal', gap: 20,
            bgType: 'color', bgColor: '#fdf8f6',
            paddingTop: 40, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fecdd3', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fee2e2', iconColor: '#991b1b', iconSize: 'md',
            itemTitleColor: '#450a0a', itemDescColor: '#7f1d1d',
            itemTitleSize: 16, itemDescSize: 14,
            showNumbers: true,
            items: [
                { title: 'সরাসরি সৌদি ইম্পোর্টেড', description: 'আমরা থার্ড পার্টি ছাড়া সরাসরি সৌদি আরব থেকে অরিজিনাল খেজুর ইম্পোর্ট করি।', icon: '🇸🇦', iconBg: '', iconColor: '' },
                { title: 'চেক করে নেওয়ার সুযোগ', description: 'ডেলিভারি ম্যানের সামনে প্যাকেট খুলে চেক করে রিসিভ করতে পারবেন।', icon: '🔍', iconBg: '', iconColor: '' },
                { title: 'ফ্রেশ প্যাকেজিং', description: 'ধুলাবালি মুক্ত পরিবেশে স্বাস্থ্যসম্মত উপায়ে সুন্দর বক্সে প্যাকেজিং করা হয়।', icon: '📦', iconBg: '', iconColor: '' },
                { title: 'সহজ রিটার্ন', description: 'খেজুরের কোয়ালিটি পছন্দ না হলে ডেলিভারি ম্যানকে সাথে সাথে ফেরত দিতে পারবেন।', icon: '↩️', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    // 6️⃣ Social Proof Section
    'testimonials-mabroom': {
        ...node('TestimonialWidget', {
            title: 'গ্রাহকরা যা বলছেন',
            subtitle: 'যাঁরা আমাদের মাবরুম মরিয়ম খেজুর কিনেছেন তাঁদের অভিজ্ঞতা',
            bgColor: '#ffffff', padding: 60,
            layout: 'grid', columns: 2, cardStyle: 'border', borderColor: '#fca5a5',
            starColor: '#f59e0b', showVerified: true,
            reviews: [
                { name: 'তাসনিয়া রহমান', role: 'ঢাকা', text: 'মাবরুম খেজুরটা অসাধারণ! আমার আম্মু ডায়াবেটিসের কারণে কড়া মিষ্টি খেতে পারেন না, এই খেজুরের পরিমিত মিষ্টি উনার খুব পছন্দ হয়েছে।', stars: 5, avatar: '' },
                { name: 'আশরাফুল আলম', role: 'খুলনা', text: 'অরিজিনাল মাবরুম চেনার সবচেয়ে বড় উপায় হলো চিবিয়ে খাওয়ার ফিলটা। আপনাদের খেজুর খেয়ে বুঝতে পেরেছি এটা একদম অরিজিনাল। সাইজও মাশাআল্লাহ বেশ বড়।', stars: 5, avatar: '' },
            ],
        }),
    },

    // 7️⃣ Offer + Urgency Section
    'countdown-mabroom': {
        ...node('CountdownWidget', {
            mode: 'daily',
            showDays: false,
            showHeadline: true,
            headline: '🎁 আজকের স্পেশাল অফার!',
            headlineSize: 28, headlineColor: '#dc2626', headlineWeight: '800',
            showSubtitle: true,
            subtitle: 'অরিজিনাল মাবরুম খেজুর - Regular Price: 1500৳ | Today Price: 1200৳',
            subtitleColor: '#450a0a', subtitleSize: 18,
            expiredMessage: '⚠️ আজকের স্পেশাল অফার শেষ হয়েছে।',
            displayStyle: 'card', boxSize: 'md',
            boxBg: '#ffffff', boxTextColor: '#991b1b',
            labelColor: '#7f1d1d', boxRadius: 16, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '📦 স্টক খুব দ্রুত শেষ হয়ে যাচ্ছে। এখনই অর্ডার করুন!',
            urgencyBarBg: '#fee2e2', urgencyBarText: '#dc2626',
            bgType: 'color', bgColor: '#fdf8f6',
            paddingTop: 40, paddingBottom: 40, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
        }),
    },

    // 8️⃣ Checkout Section
    'checkout-mabroom': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 32, borderRadius: 20,
            shadow: '2xl', borderWidth: 2, borderColor: '#991b1b', 
            showHeader: true, headerText: '🛒 অফার মূল্যে অর্ডার কনফার্ম করুন',
            headerBgColor: '#fee2e2', headerTextColor: '#991b1b', headerSize: 22,
            showProductSummary: true, summaryLayout: 'row',
            showRating: true, ratingValue: 4.9, reviewCount: 940,
            showMultiProduct: false,
            showQuantity: true, showAddress: true, showDistrict: true, showNote: false,
            nameLabel: 'আপনার নাম', phoneLabel: 'মোবাইল নাম্বার',
            addressLabel: 'সম্পূর্ণ ঠিকানা', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'বিশেষ নির্দেশ', quantityLabel: 'পরিমাণ (কেজি)',
            formLayout: 'two-col',
            unitLabel: 'কেজি', presetQuantities: '1, 2, 3, 5', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true,
            bundles: [
                { qty: 1, price: 1200, highlight: false, badge: '' }, 
                { qty: 2, price: 2350, highlight: true, badge: 'জনপ্রিয় অফার' }, 
                { qty: 5, price: 5800, highlight: false, badge: 'সুপার সেভার' },
            ],
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার কনফার্ম করুন ৳১২০০',
            buttonBgColor: '#991b1b', buttonTextColor: '#ffffff',
            buttonBorderRadius: 50, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '✅', buttonSubText: 'সারা বাংলাদেশে ক্যাশ অন ডেলিভারি',
            showTrustBadges: true,
            trustBadges: [
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি',   show: true },
                { icon: '🔍', text: 'চেক করে নেওয়ার সুযোগ', show: true },
            ],
            showUrgency: true, urgencyText: '⚡ দ্রুত আপনার নাম ও ঠিকানা লিখে অর্ডার কনফার্ম করুন!',
            urgencyBgColor: '#fee2e2', urgencyTextColor: '#dc2626',
            showSocialProof: true,
            socialProofText: 'গত ১ ঘণ্টায় ২৭ জন অর্ডার কনফার্ম করেছেন',
            socialProofIcon: '🔥',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true, 
            mobileStickyText: '🛒 অর্ডার করুন (৳১২০০)',
            mobileStickyBg: '#ffffff',
            themeColor: '#991b1b',
            labelColor: '#450a0a', inputBorderColor: '#fca5a5', inputBgColor: '#fdf8f6',
        }),
    },
};