// resources/js/Features/PageBuilder/Templates/MashrookMaryamTemplate.js
import { node, container } from './helpers';

export const MASHROOK_MARYAM_TEMPLATE = {
    ROOT: container({ bgColor: '#fff1f2', bgType: 'color', gap: 0, paddingTop: 0, paddingBottom: 0 }, [
        'hero-mashrook', 
        'problem-mashrook', 
        'product-mashrook', 
        'breakdown-mashrook', 
        'benefits-mashrook', 
        'why-us-mashrook',
        'testimonials-mashrook', 
        'countdown-mashrook', 
        'checkout-mashrook',
    ]),

    // 1️⃣ Hero Section
    'hero-mashrook': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#fff1f2',
            bgGradientTo: '#ffe4e6',
            bgGradientDirection: 145,
            minHeight: 520,
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center', contentMaxWidth: 850, contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '👑 রয়্যাল কোয়ালিটি',
            badgeColor: '#881337', badgeBgColor: '#fecdd3',
            title: 'অরিজিনাল সৌদি\nমাশরুক মরিয়ম খেজুর',
            titleSize: 52, titleWeight: '900', titleColor: '#4c0519',
            titleLineHeight: 1.15, titleLetterSpacing: -0.02,
            subtitle: 'স্বাদে ও পুষ্টিতে ভরপুর, চিবিয়ে খাওয়ার মতো মজাদার আধা-শুকনো (Semi-dry) প্রিমিয়াম মাশরুক মরিয়ম। পরিবার ও মেহমানদারির জন্য সেরা পছন্দ।',
            subtitleSize: 18, subtitleColor: '#881337', subtitleMaxWidth: 700, subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '🛒 অফার মূল্যে অর্ডার করুন',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#9f1239', primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#9f1239', primaryBtnBorderRadius: 50, primaryBtnSize: 'xl',
            showSecondaryBtn: false,
            showStats: true,
            stats: [
                { value: '১০০%', label: 'অরিজিনাল সৌদি পণ্য',  show: true },
                { value: 'ফ্রেশ', label: 'আধা-শুকনো টেক্সচার',     show: true },
                { value: 'ন্যাচারাল', label: 'কোনো প্রিজারভেটিভ নেই', show: true },
            ],
            decorShape: 'blob-tr', decorColor: '#fecdd3', decorOpacity: 40,
            animation: 'slideUp', animationDelay: '0',
        }),
    },

    // 2️⃣ Problem Section
    'problem-mashrook': {
        ...node('FeaturesWidget', {
            sectionTitle: 'আসল মরিয়ম খেজুর চিনতে হিমশিম খাচ্ছেন?',
            sectionSubtitle: 'বাজারের সাধারণ খেজুর কিনে প্রতারিত হওয়ার কিছু সাধারণ কারণ:',
            titleColor: '#e11d48', subtitleColor: '#881337',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#fff1f2', cardBorderColor: '#ffe4e6', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#ffe4e6', iconColor: '#e11d48', iconSize: 'md',
            itemTitleColor: '#4c0519', itemDescColor: '#881337',
            itemTitleSize: 16, itemDescSize: 15,
            showNumbers: false,
            items: [
                { title: 'নকল মরিয়ম', description: 'আসল মাশরুক মরিয়মের নামে সাধারণ লম্বা ও সস্তা খেজুর ধরিয়ে দেওয়া হয়।', icon: '❌', iconBg: '', iconColor: '' },
                { title: 'অতিরিক্ত শক্ত', description: 'দীর্ঘদিন ফেলে রাখার কারণে খেজুর শক্ত কাঠের মতো হয়ে যায় যা খাওয়া কষ্টকর।', icon: '❌', iconBg: '', iconColor: '' },
                { title: 'স্বাদহীন ও শুষ্ক', description: 'সঠিক সংরক্ষণের অভাবে খেজুরের ভেতরের রসালো ভাব ও স্বাদ নষ্ট হয়ে যায়।', icon: '❌', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    // 3️⃣ Product Intro
    'product-mashrook': {
        ...node('ProductWidget', {
            layout: 'side-by-side', maxWidth: 1000,
            bgType: 'color', bgColor: '#fff1f2',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            imageRatio: '4:3', imageBorderRadius: 20, imageShadow: 'lg',
            showGallery: true,
            showBadge: true, badgeText: '৩০০ টাকা ছাড়!', badgeBg: '#e11d48', badgeColor: '#ffffff',
            showTitle: true, titleSize: 32, titleWeight: '800', titleColor: '#4c0519', titleLineHeight: 1.25,
            showPrice: true, priceColor: '#9f1239', priceSize: 42, priceWeight: '900',
            showOriginalPrice: true, originalPrice: 1400, showDiscountBadge: true, currencySymbol: '৳',
            showRating: true, ratingValue: 4.8, reviewCount: 820, starColor: '#f59e0b',
            showDescription: true, descriptionSize: 16, descriptionColor: '#881337', descriptionLines: 6,
            descriptionText: 'মাশরুক মরিয়ম (Mashrook Maryam) খেজুর দেখতে কিছুটা মাবরুমের মতো হলেও এর স্বাদ এবং টেক্সচার অনন্য। এর রঙ কালচে লাল বা রুবি কালারের মতো হয়ে থাকে।\n\nএটি আধা-শুকনো (Semi-dry) প্রকৃতির, তাই এর বাইরের অংশ কিছুটা ড্রাই হলেও ভেতরটা বেশ নরম ও মাংসল। এর মিষ্টি স্বাদ খুবই পরিমিত, যা সবারই পছন্দ হবে।',
            showSpecs: true,
            specs: [
                { icon: '🌴', label: 'উৎস',    value: 'সৌদি আরব (মদিনা)', show: true },
                { icon: '⚖️', label: 'পরিমাণ', value: '১ কেজি (নেট ওজন)', show: true },
                { icon: '✨', label: 'ধরণ', value: 'আধা-শুকনো (Semi-dry)', show: true },
            ],
            showTrust: true,
            trustItems: [
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি', bg: '#fff7ed', color: '#ea580c', show: true },
                { icon: '🔍', text: 'প্যাকেট খুলে চেক করার সুযোগ', bg: '#f0fdf4', color: '#16a34a', show: true },
            ],
            showStock: true, stockText: '📦 স্টক সীমিত! দ্রুত অর্ডার করুন', stockBg: '#ffe4e6', stockColor: '#e11d48',
            showCta: true,
            ctaText: '🛒 ১১০০ টাকায় অর্ডার করুন',
            ctaUrl: '#checkout', ctaBg: '#9f1239', ctaTextColor: '#ffffff',
            ctaRadius: 50, ctaSize: 'lg',
            ctaSubText: 'রেগুলার প্রাইস: ১৪০০৳ | আজকের অফার: ১১০০৳',
            animation: 'fadeUp',
        }),
    },

    // 4️⃣ Breakdown Section
    'breakdown-mashrook': {
        ...node('FeaturesWidget', {
            sectionTitle: 'মাশরুক খেজুরের বিশেষত্ব',
            sectionSubtitle: 'কেন এই খেজুরটি আপনার খাদ্যতালিকায় রাখবেন?',
            titleColor: '#4c0519', subtitleColor: '#881337',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#fff1f2', cardBorderColor: '#ffe4e6', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#ffe4e6', iconColor: '#9f1239', iconSize: 'xl',
            itemTitleColor: '#4c0519', itemDescColor: '#881337',
            itemTitleSize: 18, itemDescSize: 14,
            showNumbers: false,
            items: [
                { title: 'আকর্ষণীয় কালচে লাল রঙ', description: 'মাশরুকের রুবি বা কালচে লাল রঙ একে অন্যান্য খেজুর থেকে আলাদা ও আকর্ষণীয় করে তোলে।', icon: '🎨', iconBg: '', iconColor: '' },
                { title: 'আধা-শুকনো টেক্সচার', description: 'এটি খুব বেশি নরমও নয়, আবার খুব বেশি শক্তও নয়। চিবিয়ে খাওয়ার জন্য একদম পারফেক্ট।', icon: '🤤', iconBg: '', iconColor: '' },
                { title: 'উন্নত স্বাদ ও মান', description: 'এর ভেতরে থাকা মাংসল অংশটি খুবই সুস্বাদু এবং এর মিষ্টিভাব সহজে বিরক্তি আনে না।', icon: '🍯', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    // 5️⃣ Benefits Section
    'benefits-mashrook': {
        ...node('FeaturesWidget', {
            sectionTitle: 'মাশরুক খেজুরের স্বাস্থ্য উপকারিতা',
            sectionSubtitle: 'সুস্থ ও সতেজ থাকতে প্রতিদিন খেজুর খাওয়ার প্রয়োজনীয়তা',
            titleColor: '#4c0519', subtitleColor: '#881337',
            titleSize: 28, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fff1f2',
            paddingTop: 60, paddingBottom: 40, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#ffe4e6', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#ffe4e6', iconColor: '#9f1239', iconSize: 'lg',
            itemTitleColor: '#4c0519', itemDescColor: '#881337',
            itemTitleSize: 18, itemDescSize: 15,
            showNumbers: false,
            items: [
                { title: 'ইনস্ট্যান্ট এনার্জি', description: 'শরীরে তাৎক্ষণিক শক্তি যোগাতে এবং ক্লান্তি দূর করতে দারুণ কার্যকরী।', icon: '⚡', iconBg: '', iconColor: '' },
                { title: 'হাড় মজবুত করে', description: 'এতে থাকা ক্যালসিয়াম ও মিনারেল শরীরের হাড় ও দাঁতকে শক্তিশালী রাখে।', icon: '🦴', iconBg: '', iconColor: '' },
                { title: 'হজম শক্তি বাড়ায়', description: 'পর্যাপ্ত ডায়াটারি ফাইবার থাকায় হজম প্রক্রিয়া সহজ করে ও কোষ্ঠকাঠিন্য দূর করে।', icon: '🌿', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    // Extra: Why Us
    'why-us-mashrook': {
        ...node('FeaturesWidget', {
            sectionTitle: 'আমাদের থেকে কেন নিবেন?',
            sectionSubtitle: '১০০% অরিজিনাল সৌদি খেজুরের নিশ্চয়তা',
            titleColor: '#4c0519', subtitleColor: '#881337',
            titleSize: 28, subtitleSize: 16, headerAlign: 'center',
            columns: 2, layout: 'horizontal', gap: 20,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 40, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#fff1f2', cardBorderColor: '#ffe4e6', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#ffe4e6', iconColor: '#9f1239', iconSize: 'md',
            itemTitleColor: '#4c0519', itemDescColor: '#881337',
            itemTitleSize: 16, itemDescSize: 14,
            showNumbers: true,
            items: [
                { title: 'সরাসরি আমদানি', description: 'আমরা কোনো থার্ড পার্টি ছাড়া সরাসরি সৌদি আরব থেকে খেজুর ইম্পোর্ট করি।', icon: '🇸🇦', iconBg: '', iconColor: '' },
                { title: 'চেক করে পেমেন্ট', description: 'ডেলিভারি ম্যানের সামনে প্যাকেট খুলে খেজুরের মান চেক করে রিসিভ করতে পারবেন।', icon: '🔍', iconBg: '', iconColor: '' },
                { title: 'কোল্ড স্টোরেজ সংরক্ষণ', description: 'খেজুরের সতেজতা ও পুষ্টিগুণ অটুট রাখতে আমরা সঠিক তাপমাত্রায় সংরক্ষণ করি।', icon: '❄️', iconBg: '', iconColor: '' },
                { title: 'মানি ব্যাক গ্যারান্টি', description: 'খেজুরের কোয়ালিটি নিয়ে কোনো অভিযোগ থাকলে সাথে সাথে ফেরত দিতে পারবেন।', icon: '↩️', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    // 6️⃣ Social Proof Section
    'testimonials-mashrook': {
        ...node('TestimonialWidget', {
            title: 'গ্রাহকদের রিভিউ',
            subtitle: 'যাঁরা আমাদের মাশরুক মরিয়ম কিনেছেন তাঁদের অভিজ্ঞতা',
            bgColor: '#fff1f2', padding: 60,
            layout: 'grid', columns: 2, cardStyle: 'border', borderColor: '#fecdd3',
            starColor: '#f59e0b', showVerified: true,
            reviews: [
                { name: 'শহীদুল ইসলাম', role: 'চট্টগ্রাম', text: 'মাশরুক খেজুর আগে কখনো খাইনি, মাবরুম ভেবেছিলাম। কিন্তু এর কালার আর টেস্ট সত্যি অন্যরকম সুন্দর। শক্ত না হওয়ায় বাচ্চারাও বেশ মজা করে খাচ্ছে।', stars: 5, avatar: '' },
                { name: 'নাঈমা আক্তার', role: 'ঢাকা', text: 'অনেকদিন ধরে অরিজিনাল মরিয়ম খেজুর খুঁজছিলাম। আপনাদের খেজুরের সাইজ, কালার আর স্বাদ প্রমাণ করে যে এটা একদম ফ্রেশ আর অরিজিনাল। অনেক ধন্যবাদ।', stars: 5, avatar: '' },
            ],
        }),
    },

    // 7️⃣ Offer + Urgency Section
    'countdown-mashrook': {
        ...node('CountdownWidget', {
            mode: 'daily',
            showDays: false,
            showHeadline: true,
            headline: '🎁 আজকের স্পেশাল অফার!',
            headlineSize: 28, headlineColor: '#e11d48', headlineWeight: '800',
            showSubtitle: true,
            subtitle: 'মাশরুক মরিয়ম - Regular Price: 1400৳ | Today Price: 1100৳',
            subtitleColor: '#4c0519', subtitleSize: 18,
            expiredMessage: '⚠️ আজকের স্পেশাল অফার শেষ হয়েছে।',
            displayStyle: 'card', boxSize: 'md',
            boxBg: '#ffffff', boxTextColor: '#9f1239',
            labelColor: '#881337', boxRadius: 16, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '📦 স্টক খুব দ্রুত শেষ হয়ে যাচ্ছে। এখনই অর্ডার করুন!',
            urgencyBarBg: '#ffe4e6', urgencyBarText: '#e11d48',
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 40, paddingBottom: 40, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
        }),
    },

    // 8️⃣ Checkout Section
    'checkout-mashrook': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 32, borderRadius: 20,
            shadow: '2xl', borderWidth: 2, borderColor: '#9f1239', 
            showHeader: true, headerText: '🛒 অফার মূল্যে অর্ডার কনফার্ম করুন',
            headerBgColor: '#ffe4e6', headerTextColor: '#9f1239', headerSize: 22,
            showProductSummary: true, summaryLayout: 'row',
            showRating: true, ratingValue: 4.8, reviewCount: 820,
            showMultiProduct: false,
            showQuantity: true, showAddress: true, showDistrict: true, showNote: false,
            nameLabel: 'আপনার নাম', phoneLabel: 'মোবাইল নাম্বার',
            addressLabel: 'সম্পূর্ণ ঠিকানা', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'বিশেষ নির্দেশ', quantityLabel: 'পরিমাণ (কেজি)',
            formLayout: 'two-col',
            unitLabel: 'কেজি', presetQuantities: '1, 2, 3, 5', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true,
            bundles: [
                { qty: 1, price: 1100, highlight: false, badge: '' }, 
                { qty: 2, price: 2150, highlight: true, badge: 'জনপ্রিয় অফার' }, 
                { qty: 5, price: 5300, highlight: false, badge: 'সুপার সেভার' },
            ],
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার কনফার্ম করুন ৳১১০০',
            buttonBgColor: '#9f1239', buttonTextColor: '#ffffff',
            buttonBorderRadius: 50, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '✅', buttonSubText: 'সারা বাংলাদেশে ক্যাশ অন ডেলিভারি',
            showTrustBadges: true,
            trustBadges: [
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি',   show: true },
                { icon: '🔍', text: 'চেক করে নেওয়ার সুযোগ', show: true },
            ],
            showUrgency: true, urgencyText: '⚡ দ্রুত আপনার নাম ও ঠিকানা লিখে অর্ডার কনফার্ম করুন!',
            urgencyBgColor: '#ffe4e6', urgencyTextColor: '#e11d48',
            showSocialProof: true,
            socialProofText: 'গত ১ ঘণ্টায় ৩১ জন অর্ডার কনফার্ম করেছেন',
            socialProofIcon: '🔥',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true, 
            mobileStickyText: '🛒 অর্ডার করুন (৳১১০০)',
            mobileStickyBg: '#ffffff',
            themeColor: '#9f1239',
            labelColor: '#4c0519', inputBorderColor: '#fecdd3', inputBgColor: '#fff1f2',
        }),
    },
};