// resources/js/Features/PageBuilder/Templates/NabiyeRahmatTemplate.js
import { node, container } from './helpers';

export const NABIYE_RAHMAT_TEMPLATE = {
    ROOT: container({ 
        bgColor: '#f8fafc', 
        bgType: 'color', 
        gap: 0, 
        paddingTop: 0, 
        paddingBottom: 0 
    }, [
        'hero-book', 
        'product-book', 
        'features-book', 
        'video-book',
        'testimonials-book',
        'countdown-book', 
        'faq-book', 
        'checkout-book',
    ]),

    'hero-book': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#064e3b', // Deep Forest Green / Emerald 900 (Matched from cover)
            bgGradientTo: '#022c22',
            bgGradientDirection: 180,
            bgImage: '',
            overlayColor: '#000000',
            overlayOpacity: 20,
            minHeight: 650,
            paddingTop: 120,
            paddingBottom: 100,
            paddingLeft: 24,
            paddingRight: 24,
            contentAlign: 'center',
            contentMaxWidth: 900,
            contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '⭐ বিশেষ অফার — ১১৫০ টাকার বই মাত্র ৪৯০ টাকায়!',
            badgeColor: '#78350f',
            badgeBgColor: '#fde68a',
            title: 'নবীয়ে রহমত\nএক জীবন্ত বিপ্লবের গল্প',
            titleSize: 56,
            titleWeight: '900',
            titleColor: '#ffffff',
            titleLineHeight: 1.2,
            titleLetterSpacing: -0.02,
            subtitle: 'রাসূলুল্লাহ ﷺ-এর জীবন কেবল ইতিহাস নয়, বরং অন্ধকার থেকে আলোতে ফেরার এক জীবন্ত বিপ্লব। লেখক অত্যন্ত প্রাঞ্জল ভাষায় জাহেলিয়াতের অন্ধকার যুগের চিত্র এবং সীরাতের মহান শিক্ষাগুলো তুলে ধরেছেন।',
            subtitleSize: 20,
            subtitleColor: '#d1fae5',
            subtitleMaxWidth: 750,
            subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '📖 অর্ডার করুন — মাত্র ৪৯০ ৳',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#d97706', // Gold/Amber (Matched from cover text/border)
            primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#d97706',
            primaryBtnBorderRadius: 8,
            primaryBtnSize: 'xl',
            showSecondaryBtn: true,
            secondaryBtnText: 'বইয়ের বৈশিষ্ট্যগুলো দেখুন',
            secondaryBtnUrl: '#features',
            secondaryBtnStyle: 'outline',
            secondaryBtnBgColor: 'transparent',
            secondaryBtnTextColor: '#ffffff',
            secondaryBtnBorderColor: '#d97706', // Gold border
            secondaryBtnBorderRadius: 8,
            secondaryBtnSize: 'xl',
            showStats: true,
            stats: [
                { value: 'বেস্টসেলার', label: 'সীরাত গ্রন্থ', show: true, color: '#fcd34d' },
                { value: '৪.৯/৫ ★',    label: 'পাঠক রেটিং', show: true, color: '#fcd34d' },
                { value: '১০০০+', label: 'সন্তুষ্ট পাঠক', show: true, color: '#fcd34d' },
            ],
            decorShape: 'dots',
            decorColor: '#ffffff',
            decorOpacity: 10,
            animation: 'slideUp',
            animationDelay: '0',
        }),
    },

    'product-book': {
        ...node('BookWidget', {
            showTitle: true, showGallery: true, showDescription: true,
            showMeta: true, showWriter: true, showPublication: true,
            showPages: true, showLanguage: true,
            showPrice: true, showRating: true, showCta: true,
            titleOverride: 'নবীয়ে রহমত (হার্ডকভার)',
            writerName: 'সাইয়েদ আবুল হাসান আলী নদভী (রহ.)',
            publicationName: 'মাকতাবাতুল ইসলাম',
            totalPages: '৫০০+',
            language: 'বাংলা',
            descriptionOverride: 'জাহেলিয়াতের অন্ধকার থেকে মানবতার মুক্তি: এক জীবন্ত বিপ্লবের গল্প। আপনি যদি এমন একটি সীরাত গ্রন্থ খুঁজেন যা আপনার হৃদয়ে নবীর প্রতি ভালোবাসা বাড়িয়ে দেবে এবং ইতিহাস সম্পর্কে গভীর জ্ঞান দেবে, তবে এই বইটি আপনার সংগ্রহে থাকা আবশ্যক।',
            shortDescLength: 350,
            ratingValue: 4.9,
            reviewCount: 450,
            starColor: '#d97706',
            currencySymbol: '৳',
            layout: 'row',
            maxWidth: 1060,
            metaStyle: 'grid', 
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            imageBorderRadius: 12, imageShadow: '2xl',
            titleSize: 36, titleWeight: '800', titleColor: '#064e3b',
            metaLabelColor: '#64748b', metaValueColor: '#0f172a',
            descColor: '#334155', descSize: 16, descLineHeight: 1.8,
            priceColor: '#d97706', priceSize: 42,
            ctaText: '🛒 এখনই অর্ডার করুন',
            ctaUrl: '#checkout',
            ctaBg: '#064e3b', ctaTextColor: '#ffffff', ctaRadius: 8,
            ctaFullWidth: true,
        }),
    },

    'features-book': {
        ...node('FeaturesWidget', {
            sectionTitle: 'কেন ‘নবীয়ে রহমত’ বইটি আপনার সংগ্রহে রাখা জরুরি?',
            sectionSubtitle: 'এই বইটি আপনাকে সীরাত সম্পর্কে এক নতুন দৃষ্টিভঙ্গি প্রদান করবে।',
            titleColor: '#064e3b', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 32,
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#e2e8f0', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 40,
            iconShape: 'soft-square', iconBg: '#ecfdf5', iconColor: '#064e3b', iconSize: 'xl',
            itemTitleColor: '#022c22', itemDescColor: '#475569',
            itemTitleSize: 20, itemDescSize: 15, itemDescLineHeight: 1.6,
            showNumbers: false,
            items: [
                { title: 'বিশ্ববিখ্যাত লেখকের লেখনী', description: 'মুসলিম বিশ্বের অন্যতম শ্রেষ্ঠ চিন্তাবিদ ও ইতিহাসবেত্তা সাইয়েদ আবুল হাসান আলী নদভী (রহ.)-এর অমর সৃষ্টি।', icon: '✍️', iconBg: '', iconColor: '' },
                { title: 'ঐতিহাসিক প্রেক্ষাপটের নিখুঁত চিত্র', description: 'রাসূল ﷺ-এর আগমনের আগে আরব, রোম ও পারস্য সাম্রাজ্যের সামাজিক ও রাজনৈতিক পতনের বিশদ বিবরণ।', icon: '🕌', iconBg: '', iconColor: '' },
                { title: 'হৃদয়স্পর্শী বর্ণনাশৈলী', description: 'তথ্যবহুল হওয়ার পাশাপাশি বইটির ভাষা অত্যন্ত প্রাঞ্জল এবং আবেগপূর্ণ, যা পাঠককে ঘটনার সাথে একাত্ম করে ফেলে।', icon: '❤️', iconBg: '', iconColor: '' },
                { title: 'নির্ভরযোগ্য তথ্যের সমাহার', description: 'কুরআন, সুন্নাহ এবং বিশুদ্ধ ইতিহাসের ওপর ভিত্তি করে রচিত একটি প্রামাণ্য দলিল।', icon: '📚', iconBg: '', iconColor: '' },
                { title: 'আধুনিক জীবনের পাথেয়', description: 'চৌদ্দশ বছর আগের আদর্শকে বর্তমান সময়ের প্রেক্ষাপটে কিভাবে প্রয়োগ করা যায়, তার এক অনন্য দিকনির্দেশনা।', icon: '🧭', iconBg: '', iconColor: '' },
                { title: 'চরিত্র গঠন ও নৈতিক শিক্ষা', description: 'রাসূল ﷺ-এর রহমত ও মমত্ববোধের দিকগুলো এখানে বিশেষভাবে গুরুত্ব পেয়েছে, যা একজন মুমিনের চরিত্র গঠনে সহায়ক।', icon: '🌟', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'video-book': {
        ...node('VideoWidget', {
            sectionTitle: 'বইটি সম্পর্কে বিদগ্ধ আলেমদের মতামত',
            sectionSubtitle: 'কেন তারা এই বইটি সবাইকে পড়ার পরামর্শ দিচ্ছেন।',
            titleColor: '#064e3b', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 
            platform: 'youtube',
            layout: 'center',
            maxWidth: 800,
            aspectRatio: '16/9',
            borderRadius: 16,
            shadow: '2xl',
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            showControls: true, autoplay: false, loop: false, muted: false,
        }),
    },

    'testimonials-book': {
        ...node('TestimonialWidget', {
            title: 'পাঠকদের অনুভূতি',
            subtitle: 'যারা বইটি পড়েছেন, তাদের জীবনের কিছু পরিবর্তন ও মতামত।',
            bgColor: '#ecfdf5', padding: 80,
            layout: 'masonry', cardStyle: 'modern',
            starColor: '#d97706', showVerified: true,
            cardRadius: 16, cardShadow: 'sm',
            reviews: [
                { name: 'আব্দুল্লাহ আল মাহমুদ', role: 'শিক্ষক', text: 'রাসূল ﷺ এর জীবনী এত সুন্দর করে উপস্থাপন করা হয়েছে যে পড়তে বসলে চোখ ভিজে আসে। প্রতিটি মুসলিমের ঘরে বইটি থাকা উচিত।', stars: 5, avatar: '' },
                { name: 'ফাতেমা আক্তার', role: 'শিক্ষার্থী', text: 'অসাধারণ একটি বই। জাহেলিয়াতের যুগের চিত্র এত নিখুঁতভাবে ফুটে উঠেছে যা সত্যিই ভাবিয়ে তোলে।', stars: 5, avatar: '' },
                { name: 'মাওলানা রফিকুল ইসলাম', role: 'খতিব', text: 'সীরাতের ওপর অন্যতম শ্রেষ্ঠ একটি রচনা। সাইয়েদ আবুল হাসান আলী নদভী (রহ.)-এর লেখনীর জাদুকরী প্রভাব রয়েছে এতে।', stars: 5, avatar: '' },
                { name: 'তারেক রহমান', role: 'ব্যবসায়ী', text: 'অফারের মূল্যে বইটি পেয়ে আলহামদুলিল্লাহ অনেক খুশি। প্রিন্ট কোয়ালিটি ও বাইন্ডিং ছিল চমৎকার।', stars: 5, avatar: '' },
            ],
        }),
    },

    'countdown-book': {
        ...node('CountdownWidget', {
            mode: 'evergreen', durationHours: 48,
            showDays: false,
            showHeadline: true,
            headline: '⏳ বিশেষ অফার: ৪৯০ টাকায় বইটি সংগ্রহ করার সময় শেষ হয়ে আসছে!',
            headlineSize: 30, headlineColor: '#064e3b', headlineWeight: '900',
            showSubtitle: true,
            subtitle: '১১৫০ টাকার বইটি মাত্র ৪৯০ টাকায়! স্টক ফুরিয়ে যাওয়ার আগেই আপনার কপি নিশ্চিত করুন।',
            subtitleColor: '#475569', subtitleSize: 16,
            expiredMessage: '⚠️ অফার শেষ হয়ে গেছে।',
            displayStyle: 'modern', boxSize: 'lg', 
            boxBg: '#ffffff', boxTextColor: '#064e3b',
            labelColor: '#475569', boxRadius: 12, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '🔥 সীমিত সময়ের অফার — স্টক শেষ হলেই দাম বাড়বে!',
            urgencyBarBg: '#fef2f2', urgencyBarText: '#991b1b',
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
            shadow: 'md',
        }),
    },

    'faq-book': {
        ...node('FaqWidget', {
            title: 'সাধারণ প্রশ্নোত্তর (FAQ)',
            subtitle: 'অর্ডার করার আগে আপনার মনের কনফিউশন দূর করুন।',
            bgColor: '#ffffff', padding: 80,
            accentColor: '#064e3b', iconStyle: 'chevron', layout: 'accordion', 
            questions: [
                { q: 'বইটি কি আসল (Original)?',    a: 'হ্যাঁ, আমরা সরাসরি প্রকাশকের কাছ থেকে বই সংগ্রহ করি। ১০০% আসল ও ঝকঝকে প্রিন্টের গ্যারান্টি।' },
                { q: 'ডেলিভারি পেতে কতদিন সময় লাগবে?', a: 'অর্ডার কনফার্ম হওয়ার ২৪ ঘণ্টার মধ্যে শিপমেন্ট হয়। ঢাকার ভেতরে ১-২ দিন, ঢাকার বাইরে ২-৩ দিন সময় লাগে।' },
                { q: 'ক্যাশ অন ডেলিভারি (COD) আছে কি?', a: 'হ্যাঁ! বই হাতে পেয়ে চেক করে টাকা পেমেন্ট করার সুবিধা রয়েছে। কোনো অগ্রিম পেমেন্ট নেই।' },
                { q: 'বই ছেঁড়া বা নষ্ট থাকলে কী করবো?',  a: 'ডেলিভারি ম্যানের সামনে চেক করবেন। কোনো সমস্যা পেলে সাথে সাথে রিটার্ন করতে পারবেন, আমরা সম্পূর্ণ বিনামূল্যে নতুন বই পাঠাবো।' },
            ],
        }),
    },

    'checkout-book': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 40, borderRadius: 16,
            shadow: '2xl', borderWidth: 1, borderColor: '#e2e8f0',
            showHeader: true, headerText: '📖 এখনই অর্ডার করুন মাত্র ৪৯০ টাকায়',
            headerBgColor: '#ecfdf5', headerTextColor: '#064e3b', headerSize: 22,
            showProductSummary: true, summaryLayout: 'card', 
            showRating: true, ratingValue: 5, reviewCount: 450,
            showMultiProduct: false, multiProductLabel: '',
            showQuantity: true, showAddress: true, showDistrict: true, showNote: true,
            nameLabel: 'আপনার পূর্ণ নাম', phoneLabel: 'সচল ফোন নম্বর',
            addressLabel: 'বিস্তারিত ডেলিভারি ঠিকানা', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'অতিরিক্ত নির্দেশনা (যদি থাকে)', quantityLabel: 'কপি সংখ্যা',
            formLayout: 'two-col',
            unitLabel: 'কপি', presetQuantities: '1, 2, 3, 5', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true, 
            bundles: [
                { qty: 2, discountText: 'ফ্রি ডেলিভারি' },
                { qty: 3, discountText: '১০% ছাড় + ফ্রি ডেলিভারি' },
            ],
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার নিশ্চিত করুন — ক্যাশ অন ডেলিভারি',
            buttonBgColor: '#064e3b', buttonTextColor: '#ffffff',
            buttonBorderRadius: 8, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '🚀', buttonSubText: 'কোনো হিডেন চার্জ নেই • ১০০% নিরাপদ',
            showTrustBadges: true,
            trustBadges: [
                { icon: '📚', text: '১০০% অরিজিনাল',  show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি', show: true },
                { icon: '🚚', text: 'ফাস্ট ডেলিভারি', show: true },
                { icon: '↩️', text: 'সহজ রিটার্ন', show: true },
            ],
            showUrgency: true, urgencyText: '🔥 অফার মূল্যে মাত্র কয়েক কপি স্টকে অবশিষ্ট আছে!',
            urgencyBgColor: '#fef2f2', urgencyTextColor: '#991b1b',
            showSocialProof: true,
            socialProofText: 'গত ২৪ ঘণ্টায় ৮৬ জন এই বইটি অর্ডার করেছেন',
            socialProofIcon: '🔥',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true,
            mobileStickyText: '📖 অর্ডার করুন — ৪৯০ ৳',
            mobileStickyBg: '#ffffff',
            themeColor: '#064e3b',
            labelColor: '#334155', inputBorderColor: '#cbd5e1', inputBgColor: '#f8fafc', inputRadius: 8,
        }),
    },
};