// resources/js/Features/PageBuilder/Templates/QuranSciencePackageTemplate.js
import { node, container } from './helpers';

export const QURAN_SCIENCE_PACKAGE_TEMPLATE = {
    ROOT: container({ 
        bgColor: '#f8fafc', 
        bgType: 'color', 
        gap: 0, 
        paddingTop: 0, 
        paddingBottom: 0 
    }, [
        'hero-qsci', 
        'product-qsci', 
        'books-details-qsci',
        'benefits-qsci',
        'importance-qsci',
        'testimonials-qsci',
        'countdown-qsci',
        'checkout-qsci',
    ]),

    'hero-qsci': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#0f172a', // Deep Midnight Blue / Space Blue
            bgGradientTo: '#1e293b',
            bgGradientDirection: 180,
            bgImage: '',
            overlayColor: '#000000',
            overlayOpacity: 30,
            minHeight: 650,
            paddingTop: 120,
            paddingBottom: 100,
            paddingLeft: 24,
            paddingRight: 24,
            contentAlign: 'center',
            contentMaxWidth: 900,
            contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '✨ জ্ঞানের এক বিস্ময়কর ভান্ডার',
            badgeColor: '#0891b2', // Cyan
            badgeBgColor: '#cffafe',
            title: 'বিজ্ঞান ও কুরআন প্যাকেজ\n১৪০০ বছর আগের মহাবিশ্বের রহস্য',
            titleSize: 52,
            titleWeight: '900',
            titleColor: '#ffffff',
            titleLineHeight: 1.2,
            titleLetterSpacing: -0.02,
            subtitle: 'বিগ ব্যাং থেকে শুরু করে মানব ভ্রূণের গঠন— আজকের বিজ্ঞান যেসব বিষয় আবিষ্কার করছে, পবিত্র কুরআনে তা বহু শতাব্দী আগেই উল্লেখ করা হয়েছে। রহস্যগুলো জানতে আজই সংগ্রহ করুন ৩টি বইয়ের এই বিশেষ প্যাকেজ।',
            subtitleSize: 20,
            subtitleColor: '#cbd5e1',
            subtitleMaxWidth: 750,
            subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '📖 প্যাকেজটি অর্ডার করুন',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#0284c7', // Ocean Blue
            primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#0284c7',
            primaryBtnBorderRadius: 8,
            primaryBtnSize: 'xl',
            showSecondaryBtn: true,
            secondaryBtnText: 'প্যাকেজের বইগুলো দেখুন',
            secondaryBtnUrl: '#books',
            secondaryBtnStyle: 'outline',
            secondaryBtnBgColor: 'transparent',
            secondaryBtnTextColor: '#ffffff',
            secondaryBtnBorderColor: '#ffffff',
            secondaryBtnBorderRadius: 8,
            secondaryBtnSize: 'xl',
            showStats: true,
            stats: [
                { value: '৩টি', label: 'গবেষণামূলক বই', show: true, color: '#38bdf8' },
                { value: 'বেস্টসেলার', label: 'বিজ্ঞান ও ধর্ম', show: true, color: '#38bdf8' },
                { value: 'সীমিত', label: 'স্টক এভেইলেবল', show: true, color: '#38bdf8' },
            ],
            decorShape: 'dots',
            decorColor: '#ffffff',
            decorOpacity: 10,
            animation: 'slideUp',
            animationDelay: '0',
        }),
    },

    'product-qsci': {
        ...node('BookWidget', {
            showTitle: true, showGallery: true, showDescription: true,
            showMeta: false, showWriter: false, showPublication: false,
            showPages: false, showLanguage: true,
            showPrice: true, showRating: true, showCta: true,
            titleOverride: 'বিজ্ঞান ও কুরআন বিশেষ প্যাকেজ (৩টি বই)',
            writerName: '',
            publicationName: '',
            totalPages: '',
            language: 'বাংলা অনুবাদ',
            descriptionOverride: 'আল কুরআন শুধু একটি ধর্মগ্রন্থ নয়— এটি একটি জীবন্ত মু\'জিজা। আজকের যুগে অনেক তরুণ বিজ্ঞান ও যুক্তির আলোকে প্রশ্ন করে। এই বইগুলো তাদেরকে বুঝতে সাহায্য করবে কীভাবে আল কুরআন জ্ঞানের এক অনন্য উৎস। এটি আপনার চিন্তার জগৎ বদলে দেওয়ার মতো একটি কালেকশন।',
            shortDescLength: 350,
            ratingValue: 4.9,
            reviewCount: 650,
            starColor: '#f59e0b',
            currencySymbol: '৳',
            layout: 'row',
            maxWidth: 1060,
            metaStyle: 'grid', 
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            imageBorderRadius: 12, imageShadow: '2xl',
            titleSize: 36, titleWeight: '800', titleColor: '#0f172a',
            metaLabelColor: '#64748b', metaValueColor: '#0f172a',
            descColor: '#334155', descSize: 16, descLineHeight: 1.8,
            priceColor: '#0284c7', priceSize: 42,
            ctaText: '🛒 ক্যাশ অন ডেলিভারিতে অর্ডার করুন',
            ctaUrl: '#checkout',
            ctaBg: '#0f172a', ctaTextColor: '#ffffff', ctaRadius: 8,
            ctaFullWidth: true,
        }),
    },

    'books-details-qsci': {
        ...node('FeaturesWidget', {
            sectionTitle: '📚 প্যাকেজে যে ৩টি অসাধারণ বই থাকছে',
            sectionSubtitle: 'কুরআনের বৈজ্ঞানিক ও গাণিতিক অলৌকিকত্ব প্রমাণের সেরা তিনটি বই।',
            titleColor: '#0f172a', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 32,
            bgType: 'color', bgColor: '#f1f5f9',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#e2e8f0', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'md', cardPadding: 40,
            iconShape: 'soft-square', iconBg: '#e0f2fe', iconColor: '#0284c7', iconSize: 'xl',
            itemTitleColor: '#0f172a', itemDescColor: '#475569',
            itemTitleSize: 20, itemDescSize: 15, itemDescLineHeight: 1.6,
            showNumbers: false,
            items: [
                { title: '📘 আল কুরআন ও আধুনিক বিজ্ঞান', description: 'কুরআনের আয়াতগুলোর সাথে আধুনিক বিজ্ঞানের আশ্চর্য মিল। মহাবিশ্ব, প্রকৃতি ও মানব সৃষ্টি নিয়ে বিস্ময়কর আলোচনা।', icon: '🌌', iconBg: '', iconColor: '' },
                { title: '📙 বাইবেল, কোরআন ও বিজ্ঞান', description: 'লেখক: মরিস বুকাই। ধর্ম ও বিজ্ঞানের তুলনামূলক বিশ্লেষণের একটি বিখ্যাত গ্রন্থ। আধুনিক বৈজ্ঞানিক তথ্যের সাথে কুরআনের গভীর সামঞ্জস্য।', icon: '⚖️', iconBg: '', iconColor: '' },
                { title: '📗 গাণিতিক রহস্যময় কুরআন', description: 'কুরআনের গাণিতিক বিন্যাস ও অলৌকিক সংখ্যাতাত্ত্বিক দিক নিয়ে আকর্ষণীয় আলোচনা যা আপনাকে অবাক করে দেবে।', icon: '🔢', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'benefits-qsci': {
        ...node('FeaturesWidget', {
            sectionTitle: '💡 এই বইগুলো পড়লে কী উপকার পাবেন?',
            sectionSubtitle: 'যুক্তি ও জ্ঞানের আলোয় আপনার চিন্তার জগৎ আলোকিত করুন।',
            titleColor: '#0f172a', subtitleColor: '#0284c7',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 2, layout: 'horizontal', gap: 24,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#f8fafc', cardBorderColor: '#e2e8f0', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'none', cardPadding: 24,
            iconShape: 'circle', iconBg: '#0f172a', iconColor: '#ffffff', iconSize: 'md',
            itemTitleColor: '#0f172a', itemDescColor: '#475569',
            itemTitleSize: 18, itemDescSize: 15, itemDescLineHeight: 1.5,
            showNumbers: false,
            items: [
                { title: 'ঈমান আরও দৃঢ় হবে', description: 'কুরআনের প্রতি আপনার ভালোবাসা ও শ্রদ্ধা আরও বৃদ্ধি পাবে এবং যুক্তি ও জ্ঞানের আলোয় ঈমান মজবুত হবে।', icon: '❤️', iconBg: '', iconColor: '' },
                { title: 'প্রশ্নের উত্তর পাবেন', description: 'ইসলাম ও বিজ্ঞান নিয়ে মনে থাকা অনেক অজানা প্রশ্নের চমৎকার যৌক্তিক উত্তর পাবেন।', icon: '❓', iconBg: '', iconColor: '' },
                { title: 'নাস্তিকদের জবাব দিতে পারবেন', description: 'সংশয়বাদী বা নাস্তিকদের বিভিন্ন প্রশ্নের বৈজ্ঞানিক জবাব দিতে আত্মবিশ্বাস পাবেন।', icon: '🛡️', iconBg: '', iconColor: '' },
                { title: 'নতুন দৃষ্টিভঙ্গি', description: 'কুরআনকে কেবল তেলাওয়াতের গ্রন্থ নয়, বরং এক নতুন বিজ্ঞানময় দৃষ্টিতে উপলব্ধি করতে পারবেন।', icon: '👁️', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'importance-qsci': {
        ...node('FeaturesWidget', {
            sectionTitle: '🌙 কেন এই প্যাকেজটি প্রতিটি তরুণের জন্য গুরুত্বপূর্ণ?',
            sectionSubtitle: 'এটি শুধু পড়ার বই নয়, বরং আপনার চিন্তার জগৎ বদলে দেওয়ার মতো জ্ঞানভিত্তিক সংগ্রহ।',
            titleColor: '#0f172a', subtitleColor: '#475569',
            titleSize: 30, subtitleSize: 16, headerAlign: 'center',
            columns: 1, layout: 'vertical', gap: 24,
            bgType: 'color', bgColor: '#e0f2fe', // Very light ocean blue
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#bae6fd', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'sm', cardPadding: 32,
            iconShape: 'none', iconBg: '', iconColor: '', iconSize: 'md',
            itemTitleColor: '#0f172a', itemDescColor: '#334155',
            itemTitleSize: 20, itemDescSize: 16, itemDescLineHeight: 1.8,
            showNumbers: false,
            items: [
                { title: '', description: 'আজকের যুগে অনেক তরুণ বিজ্ঞান ও যুক্তির আলোকে প্রশ্ন করে। তারা সবকিছুতেই প্রমাণ খোঁজে। এই বইগুলো তাদেরকে বুঝতে সাহায্য করবে— কীভাবে আল কুরআন জ্ঞানের এক অনন্য উৎস এবং ১৪০০ বছর আগেই কীভাবে এমন নিখুঁত বৈজ্ঞানিক তথ্য দেওয়া সম্ভব হয়েছিল যা আধুনিক বিজ্ঞান আজ প্রমাণ করছে।', icon: '', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0',
        }),
    },

    'testimonials-qsci': {
        ...node('TestimonialWidget', {
            title: 'পাঠকদের অনুভূতি',
            subtitle: 'যারা বইগুলো পড়েছেন তাদের চমৎকার মতামত।',
            bgColor: '#ffffff', padding: 80,
            layout: 'masonry', cardStyle: 'modern',
            starColor: '#f59e0b', showVerified: true,
            cardRadius: 16, cardShadow: 'sm',
            reviews: [
                { name: 'রাকিবুল হাসান', role: 'বিশ্ববিদ্যালয় শিক্ষার্থী', text: 'মরিস বুকাইয়ের বইটি আমার চিন্তাধারা সম্পূর্ণ বদলে দিয়েছে। বিজ্ঞান ও ধর্মের এমন সুন্দর সমন্বয় আগে কখনো দেখিনি। অসাধারণ একটি প্যাকেজ!', stars: 5, avatar: '' },
                { name: 'ডা. ইমতিয়াজ', role: 'চিকিৎসক', text: 'কুরআনে মানব ভ্রূণের গঠনের যে নিখুঁত বর্ণনা দেওয়া আছে, তা একজন ডাক্তার হিসেবে আমাকে বিস্মিত করেছে। প্রতিটি শিক্ষিত মানুষের এই বইগুলো পড়া উচিত।', stars: 5, avatar: '' },
                { name: 'সাদিয়া ইসলাম', role: 'ঢাকা', text: 'বইগুলোর প্রিন্ট কোয়ালিটি খুব ভালো। গাণিতিক রহস্যময় কুরআন বইটি পড়ে সত্যিই অবাক হয়েছি যে কুরআনের প্রতিটি শব্দের হিসাব কতটা নিখুঁত।', stars: 5, avatar: '' },
            ],
        }),
    },

    'countdown-qsci': {
        ...node('CountdownWidget', {
            mode: 'evergreen', durationHours: 24,
            showDays: false,
            showHeadline: true,
            headline: '⏳ স্টক শেষ হওয়ার আগেই সংগ্রহ করুন!',
            headlineSize: 30, headlineColor: '#0f172a', headlineWeight: '900',
            showSubtitle: true,
            subtitle: 'এই বিশেষ বিজ্ঞান ও কুরআন বই প্যাকেজ সীমিত সংখ্যায় উপলব্ধ।',
            subtitleColor: '#475569', subtitleSize: 16,
            expiredMessage: '⚠️ অফার শেষ হয়ে গেছে।',
            displayStyle: 'modern', boxSize: 'lg', 
            boxBg: '#ffffff', boxTextColor: '#0284c7',
            labelColor: '#475569', boxRadius: 12, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '🔥 খুবই সীমিত স্টক! দ্রুত অর্ডার করুন।',
            urgencyBarBg: '#fee2e2', urgencyBarText: '#991b1b',
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
            shadow: 'md',
        }),
    },

    'checkout-qsci': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 40, borderRadius: 16,
            shadow: '2xl', borderWidth: 1, borderColor: '#e2e8f0',
            showHeader: true, headerText: '📖 এখনই অর্ডার করুন',
            headerBgColor: '#e0f2fe', headerTextColor: '#0f172a', headerSize: 22,
            showProductSummary: true, summaryLayout: 'card', 
            showRating: true, ratingValue: 5, reviewCount: 650,
            showMultiProduct: false, multiProductLabel: '',
            showQuantity: true, showAddress: true, showDistrict: true, showNote: true,
            nameLabel: 'আপনার নাম', phoneLabel: 'মোবাইল নাম্বার',
            addressLabel: 'সম্পূর্ণ ঠিকানা', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'অতিরিক্ত নির্দেশনা (যদি থাকে)', quantityLabel: 'প্যাকেজ সংখ্যা',
            formLayout: 'two-col',
            unitLabel: 'প্যাকেজ', presetQuantities: '1, 2, 3', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: false, 
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার কনফার্ম করুন (ক্যাশ অন ডেলিভারি)',
            buttonBgColor: '#0f172a', buttonTextColor: '#ffffff',
            buttonBorderRadius: 8, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '🚀', buttonSubText: 'কুরআনের জ্ঞানভান্ডারের নতুন দিগন্ত আবিষ্কার করুন',
            showTrustBadges: true,
            trustBadges: [
                { icon: '📦', text: 'ক্যাশ অন ডেলিভারি', show: true },
                { icon: '🚚', text: 'সারা দেশে হোম ডেলিভারি', show: true },
                { icon: '💯', text: 'অরিজিনাল প্রিন্ট', show: true },
            ],
            showUrgency: true, urgencyText: '🔥 স্টক শেষ হওয়ার আগেই অর্ডার করে ফেলুন!',
            urgencyBgColor: '#fee2e2', urgencyTextColor: '#991b1b',
            showSocialProof: true,
            socialProofText: 'গত ২৪ ঘণ্টায় ৫৬ জন এই প্যাকেজটি অর্ডার করেছেন',
            socialProofIcon: '🔥',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true, 
            mobileStickyText: '🛒 অর্ডার করুন — COD',
            mobileStickyBg: '#ffffff',
            themeColor: '#0f172a',
            labelColor: '#334155', inputBorderColor: '#cbd5e1', inputBgColor: '#f8fafc', inputRadius: 8,
        }),
    },
};