// resources/js/Features/PageBuilder/Templates/QuranTemplate.js
import { node, container } from './helpers';

export const QURAN_TEMPLATE = {
    ROOT: container({ 
        bgColor: '#f8fafc', 
        bgType: 'color', 
        gap: 0, 
        paddingTop: 0, 
        paddingBottom: 0 
    }, [
        'hero-quran', 
        'product-quran', 
        'gallery-quran', 
        'features-quran', 
        'tajweed-rules-quran',
        'video-quran', 
        'testimonials-quran',
        'countdown-quran', 
        'faq-quran', 
        'checkout-quran',
    ]),

    'hero-quran': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#f8fafc',
            bgGradientTo: '#ecfdf5',
            bgGradientDirection: 180,
            bgImage: '',
            overlayColor: '#ffffff',
            overlayOpacity: 0,
            minHeight: 600,
            paddingTop: 120,
            paddingBottom: 100,
            paddingLeft: 24,
            paddingRight: 24,
            contentAlign: 'center',
            contentMaxWidth: 900,
            contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '🔥 স্টক সীমিত - বাংলাদেশের প্রথম ক্বারীয়ানা কালার কোডেড কুরআন',
            badgeColor: '#b45309', 
            badgeBgColor: '#fef3c7',
            title: 'তাজবীদ বা মাখরাজ না জানলেও\nএখন সহীহ শুদ্ধভাবে কুরআন তিলাওয়াত করুন!',
            titleSize: 52,
            titleWeight: '900',
            titleColor: '#064e3b',
            titleLineHeight: 1.2,
            titleLetterSpacing: -0.02,
            subtitle: '১, ৩, ৪ আলিফ টান এবং কালার কোড দেখে যে কেউ এখন সহজেই শুদ্ধ তিলাওয়াত শিখতে পারবেন। প্রতিটি আয়াতের নিচে রয়েছে সহজ বাংলা উচ্চারণ, শানে নুযূল ও সরল অনুবাদ।',
            subtitleSize: 22,
            subtitleColor: '#334155',
            subtitleMaxWidth: 800,
            subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '🛒 অর্ডার করুন (ফ্রি হোম ডেলিভারি)',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#d97706', 
            primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#d97706',
            primaryBtnBorderRadius: 8,
            primaryBtnSize: 'xl',
            showSecondaryBtn: true,
            secondaryBtnText: 'বিস্তারিত দেখুন',
            secondaryBtnUrl: '#video-quran',
            secondaryBtnStyle: 'outline',
            secondaryBtnBgColor: 'transparent',
            secondaryBtnTextColor: '#064e3b',
            secondaryBtnBorderColor: '#064e3b',
            secondaryBtnBorderRadius: 8,
            secondaryBtnSize: 'xl',
            showStats: true,
            stats: [
                { value: 'ফ্রি', label: 'সারা দেশে ডেলিভারি', show: true },
                { value: 'বড় ফন্ট', label: 'স্পষ্ট আরবী লেখা', show: true },
                { value: '১০০%', label: 'টাকা ফেরত গ্যারান্টি', show: true }, 
            ],
            decorShape: 'dots',
            decorColor: '#064e3b',
            decorOpacity: 10,
            animation: 'slideUp',
            animationDelay: '0',
        }),
    },

    'product-quran': {
        ...node('BookWidget', {
            showTitle: true, showGallery: true, showDescription: true,
            showMeta: true, showWriter: false, showPublication: false,
            showPages: true, showLanguage: true,
            showPrice: true, showRating: true, showCta: true,
            titleOverride: 'ক্বারীয়ানা কালার কোডেড কুরআন মাজীদ',
            writerName: '',
            publicationName: '',
            totalPages: '১০০ জিএসএম প্রিমিয়াম ম্যাট পেপার',
            language: 'আরবি ও বাংলা (উচ্চারণ ও অর্থসহ)',
            descriptionOverride: 'পবিত্র মক্কার অনুরুপ গাড় নীলের ভিতর গোল্ডেন কালার ডিজাইনে তৈরি রাজকীয় কভার। সাইজ: ১১.১৫ X ৯ ইঞ্চি (বড় সাইজ, তাই বয়স্কদের পড়তেও সুবিধা)। প্রতিটি আয়াতের নিচে বাংলা উচ্চারণ ও সরল অনুবাদ দেয়া আছে। \n\n✅ আমরা দিচ্ছি ১০০% কোয়ালিটি গ্যারান্টি। হাতে পেয়ে, চেক করে পেমেন্ট করবেন। পছন্দ না হলে সাথে সাথে রিটার্ন করতে পারবেন!',
            shortDescLength: 450,
            ratingValue: 4.9,
            reviewCount: 12540, 
            starColor: '#d97706',
            currencySymbol: '৳',
            layout: 'row',
            maxWidth: 1060,
            metaStyle: 'grid',
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 100, paddingBottom: 100, paddingLeft: 24, paddingRight: 24,
            imageBorderRadius: 12, imageShadow: '2xl',
            titleSize: 36, titleWeight: '800', titleColor: '#0f172a',
            metaLabelColor: '#64748b', metaValueColor: '#0f172a',
            descColor: '#334155', descSize: 17, descLineHeight: 1.8,
            priceColor: '#b45309', priceSize: 42,
            ctaText: '👉 এখনই আপনার কপিটি নিশ্চিত করুন',
            ctaUrl: '#checkout',
            ctaBg: '#064e3b', ctaTextColor: '#ffffff', ctaRadius: 8,
            ctaFullWidth: true,
        }),
    },

    'gallery-quran': {
        ...node('ImageSliderWidget', {
            headline: 'ভেতরের পৃষ্ঠাগুলো কতটা স্পষ্ট? নিজেই দেখে নিন!',
            showHeadline: true,
            headlineColor: '#0f172a',
            headlineFontSize: 32,
            headlineWeight: '800',
            autoPlay: true,
            autoPlayInterval: 3.5,
            showDots: true,
            showArrows: true,
            showCaptions: true,
            borderRadius: 16,
            aspectRatio: '4:3',
            objectFit: 'cover',
            bgColor: '#f8fafc',
            paddingTop: 80,
            paddingBottom: 40,
            paddingLeft: 24,
            paddingRight: 24,
            transitionSpeed: 500,
            overlayColor: '#000000',
            overlayOpacity: 0,
            captionBgColor: 'rgba(6, 78, 59, 0.90)',
            captionTextColor: '#ffffff',
            images: [
                { url: '', caption: 'সহজ ক্বারীয়ানা তাজউইদ কালার কোড নির্দেশিকা' },
                { url: '', caption: 'বয়স্কদের পড়ার সুবিধার জন্য বড় ও স্পষ্ট ফন্ট' },
                { url: '', caption: 'প্রতিটি শব্দের সঠিক বাংলা উচ্চারণ ও সাবলীল অনুবাদ' },
                { url: '', caption: 'প্রতি পেজে স্মার্ট QR স্ক্যানার - স্ক্যান করলেই অডিও চালু' },
            ],
        }),
    },

    'features-quran': {
        ...node('FeaturesWidget', {
            sectionTitle: 'যে কারণে হাজারো মানুষের প্রথম পছন্দ এই কুরআনটি',
            sectionSubtitle: 'আপনার কুরআন শিক্ষাকে সহজ ও নির্ভুল করতে এতে যুক্ত করা হয়েছে অসাধারণ সব ফিচার।',
            titleColor: '#064e3b', subtitleColor: '#475569',
            titleSize: 36, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 32,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 100, paddingLeft: 24, paddingRight: 24,
            cardBg: '#f8fafc', cardBorderColor: '#e2e8f0', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'md', cardPadding: 40,
            iconShape: 'soft-square', iconBg: '#ecfdf5', iconColor: '#064e3b', iconSize: 'xl',
            itemTitleColor: '#0f172a', itemDescColor: '#475569',
            itemTitleSize: 20, itemDescSize: 16, itemDescLineHeight: 1.6,
            showNumbers: false,
            items: [
                { title: 'নির্ভুল তিলাওয়াতের গ্যারান্টি', description: 'কোথায় কয় আলিফ টানতে হবে তা আরবি হরফের এবং বাংলা উচ্চারনের ওপর ১, ৩, ৪ দিয়ে খুব সহজেই বোঝানো আছে।', icon: '✨' },
                { title: 'স্মার্ট অডিও QR স্ক্যানার', description: 'পড়তে গিয়ে আটকে গেছেন? মোবাইল দিয়ে পেজের QR কোড স্ক্যান করেই প্রতিটা লাইন ক্বারীর কণ্ঠে শুনে মিলিয়ে নিতে পারবেন।', icon: '🎧' },
                { title: 'চোখের প্রশান্তির জন্য বড় অক্ষর', description: 'সবচেয়ে বড় এবং স্পষ্ট অক্ষরে ছাপা। তাই বাড়ির বয়স্ক মানুষেরাও চশমা ছাড়া খুব স্বাচ্ছন্দ্যে পড়তে পারবেন।', icon: '🔍' },
                { title: 'বাংলা উচ্চারণ ও শানে নুযূল', description: 'প্রতিটি আয়াতের নিচে সাবলীল বাংলা উচ্চারণ, সরল অনুবাদ এবং আয়াতটি নাজিলের প্রেক্ষাপট (শানে নুযূল) দেয়া আছে।', icon: '💡' },
                { title: '১০০ বছর টিকবে ইনশাআল্লাহ', description: 'মক্কার অনুরুপ রাজকীয় ডিজাইনের কভার। ভেতরের প্রতিটি পৃষ্ঠা ১০০ জিএসএম প্রিমিয়াম আর্ট/ম্যাট পেপার দিয়ে ছাপা, যা সহজে ছিঁড়বে না।', icon: '🛡️' },
                { title: 'সারা দেশে ফ্রি ডেলিভারি', description: 'আপনাদের সুবিধার্থে সারা বাংলাদেশে আমরা দিচ্ছি সম্পূর্ণ ফ্রি হোম ডেলিভারি। কোনো অতিরিক্ত চার্জ ছাড়াই প্রোডাক্ট হাতে পেয়ে পেমেন্ট করবেন।', icon: '🚚' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'tajweed-rules-quran': {
        ...node('FeaturesWidget', {
            sectionTitle: 'এক নজরে তাজবীদের সহজ নিয়মগুলো',
            sectionSubtitle: 'এই কয়েকটি সাধারণ সাংকেতিক চিহ্ন দেখেই আপনি সঠিক তাজবীদ মেনে কুরআন পড়তে পারবেন।',
            titleColor: '#0f172a', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            columns: 4, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 60, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#e2e8f0', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'sm', cardPadding: 20,
            iconShape: 'circle', iconBg: '#ecfdf5', iconColor: '#064e3b', iconSize: 'lg',
            itemTitleColor: '#0f172a', itemDescColor: '#475569',
            itemTitleSize: 16, itemDescSize: 14, itemDescLineHeight: 1.5,
            showNumbers: false,
            items: [
                { title: '১, ২, ৩, ৪ লিখা', description: 'যেখানে যেই সংখ্যা থাকবে, সেখানে সেই অনুযায়ী ১, ২, ৩ বা ৪ আলিফ টানতে হবে।', icon: '🔢' },
                { title: 'গোলের মাঝে (১)', description: 'দম ফেলিলে এক আলিফ, না ফেলিলে টেনে পড়া যাবে না।', icon: '⭕' },
                { title: 'গোলের মাঝে সাকিন', description: 'যেখানে দম ফেলিলে আরদ্বী সাকিন ধরতে হবে।', icon: '⏸️' },
                { title: 'তিনের মাঝে উল্টা ১', description: 'দম ফেলিলে তিন আলিফ, না ফেলিলে এক আলিফ টানতে হবে।', icon: '🔄' },
                { title: 'ং এবং (গুন) লিখা', description: 'এই চিহ্নগুলো থাকলে সেখানে গুন্নাহ্ করে পড়তে হবে।', icon: 'গ' },
                { title: '(ক) লিখা', description: 'যেখানে ক্বলক্বলাহ্ করতে হবে।', icon: 'ক' },
                { title: '(শ) লিখা', description: 'যেখানে শিষ দিয়ে পড়তে হবে।', icon: 'শ' },
                { title: '(ম) লিখা', description: 'যেখানে মোটা করে পড়তে হবে।', icon: 'ম' },
            ],
            animation: 'fadeUp', staggerDelay: '0.05',
        }),
    },

    'video-quran': {
        ...node('VideoWidget', {
            sectionTitle: 'বিশ্বাস হচ্ছে না? নিজেই ভিডিওতে দেখে নিন!',
            sectionSubtitle: 'এই কুরআনটি দিয়ে পড়া কতটা সহজ, তা সরাসরি এই ভিডিওটিতে দেখানো হয়েছে।',
            titleColor: '#064e3b', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 
            platform: 'youtube',
            layout: 'center',
            maxWidth: 800,
            aspectRatio: '16/9',
            borderRadius: 16,
            shadow: '2xl',
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            showControls: true, autoplay: false, loop: false, muted: false,
        }),
    },

    'testimonials-quran': {
        ...node('TestimonialWidget', {
            title: 'আলহামদুলিল্লাহ, হাজারো ক্রেতা সন্তুষ্ট',
            subtitle: 'যারা আমাদের থেকে কুরআন সংগ্রহ করেছেন, তাদের সৎ ও বাস্তব মতামত।',
            bgColor: '#ecfdf5', padding: 80,
            layout: 'masonry', cardStyle: 'modern', 
            starColor: '#d97706', showVerified: true,
            cardRadius: 16, cardShadow: 'sm',
            reviews: [
                { name: 'আব্দুর রহমান', role: 'ঢাকা', text: 'ফেসবুকে এড দেখে ভয় পাচ্ছিলাম কেমন না কেমন হয়! কিন্তু আলহামদুলিল্লাহ! কুরআনের প্রিন্ট কোয়ালিটি অসাধারণ। ১, ৩, ৪ আলিফ টান উল্লেখ থাকায় তাজউইদ মেনে পড়া এখন অনেক সহজ হয়ে গেছে।', stars: 5, avatar: '' },
                { name: 'ফাতেমা আক্তার', role: 'চট্টগ্রাম', text: 'বড় ও স্পষ্ট লেখা হওয়ায় আমার মায়ের পড়তে খুব সুবিধা হচ্ছে। উনি চোখে কম দেখেন, কিন্তু এই কুরআনের অক্ষরগুলো অনেক বড়। জাযাকাল্লাহ খায়ের।', stars: 5, avatar: '' },
                { name: 'সাইফুল ইসলাম', role: 'সিলেট', text: 'কাগজের মান এবং কভার এক কথায় চমৎকার। সত্যি বলতে পছন্দ না হলে ফেরত দেওয়ার অপশন থাকায় নিশ্চিন্তে অর্ডার করেছিলাম, হাতে পেয়ে আমি সত্যিই মুগ্ধ।', stars: 5, avatar: '' },
                { name: 'ডা. রফিকুল হাসান', role: 'রাজশাহী', text: 'ফ্রি ডেলিভারি অফার পেয়ে আমি ৩ কপি অর্ডার করেছি গিফট করার জন্য। বাংলা উচ্চারণ এবং অনুবাদটি খুবই সাবলীল। প্রতিটি শব্দের অর্থ বুঝতে সুবিধা হয়। প্যাকেজিংটাও খুব সুন্দর এবং নিরাপদ ছিল।', stars: 5, avatar: '' },
            ],
        }),
    },

    'countdown-quran': {
        ...node('CountdownWidget', {
            mode: 'evergreen', durationHours: 12, 
            showDays: false,
            showHeadline: true,
            headline: '⏳ ফ্রি ডেলিভারি অফার ফুরিয়ে যাওয়ার আগেই অর্ডার করুন!',
            headlineSize: 32, headlineColor: '#991b1b', headlineWeight: '900',
            showSubtitle: true,
            subtitle: 'আজকের স্পেশাল ফ্রি হোম ডেলিভারি অফারটি যেকোনো সময় শেষ হয়ে যেতে পারে।',
            subtitleColor: '#475569', subtitleSize: 18,
            expiredMessage: '⚠️ অফার শেষ হয়ে গেছে।',
            displayStyle: 'modern', boxSize: 'lg',
            boxBg: '#ffffff', boxTextColor: '#991b1b',
            labelColor: '#475569', boxRadius: 12, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '🔥 আর মাত্র কয়েকটি কপি স্টকে অবশিষ্ট আছে!',
            urgencyBarBg: '#fee2e2', urgencyBarText: '#991b1b',
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
            shadow: 'md',
        }),
    },

    'faq-quran': {
        ...node('FaqWidget', {
            title: 'সাধারণ প্রশ্নোত্তর (FAQ)',
            subtitle: 'আপনার মনে কোনো কনফিউশন থাকলে এখান থেকে ক্লিয়ার হয়ে নিন।',
            bgColor: '#ffffff', padding: 80,
            accentColor: '#064e3b', iconStyle: 'chevron', layout: 'accordion', 
            questions: [
                { q: 'পাওয়ার পর কোয়ালিটি পছন্দ না হলে কি ফেরত দিতে পারবো?', a: 'অবশ্যই! আমাদের প্রোডাক্টের ওপর আমাদের ১০০% আস্থা রয়েছে। ডেলিভারি ম্যান থাকা অবস্থায় পার্সেল খুলে চেক করবেন। পছন্দ না হলে কোনো চার্জ ছাড়াই সাথে সাথে ফেরত দিতে পারবেন।' },
                { q: 'কুরআনটির সাইজ এবং ওজন কত?', a: 'এর সাইজ ১১.১৫ X ৯ ইঞ্চি এবং ওজন প্রায় ২ কেজি ৭০০ গ্রাম। এটি রেগুলার কুরআনের চেয়ে বেশ বড় সাইজের হওয়ায় পড়তে অনেক সুবিধা হয়।' },
                { q: 'অডিও শোনার QR কোড কীভাবে কাজ করে?', a: 'প্রতিটি পেজে একটি নির্দিষ্ট QR কোড দেওয়া আছে। আপনার স্মার্টফোনের ক্যামেরা বা যেকোনো স্ক্যানার অ্যাপ দিয়ে স্ক্যান করলেই ঐ পেজের অডিও তিলাওয়াত চালু হয়ে যাবে। খুব সহজ!' },
                { q: 'ডেলিভারি পেতে কতদিন সময় লাগবে? ডেলিভারি চার্জ কত?', a: 'বর্তমানে আমাদের সম্পূর্ণ ফ্রি হোম ডেলিভারি অফার চলছে, তাই ডেলিভারি চার্জ ৳০! অর্ডার কনফার্ম হওয়ার পর ঢাকার ভেতরে ১-২ দিন এবং ঢাকার বাইরে ২-৩ দিনের মধ্যে ইনশাআল্লাহ ডেলিভারি পেয়ে যাবেন।' },
            ],
        }),
    },

    'checkout-quran': {
        ...node('CheckoutWidget', {
            maxWidth: 650, bgColor: '#ffffff', padding: 40, borderRadius: 16,
            shadow: '2xl', borderWidth: 1, borderColor: '#e2e8f0',
            showHeader: true, headerText: '👇 ফর্মটি পূরণ করে অর্ডার কনফার্ম করুন',
            headerBgColor: '#ecfdf5', headerTextColor: '#064e3b', headerSize: 22,
            showProductSummary: true, summaryLayout: 'card',
            showRating: true, ratingValue: 5, reviewCount: 12540,
            showMultiProduct: false, multiProductLabel: '',
            
            showVariants: false, // Variants removed as requested
            variantLabel: '',
            variants: [],

            showQuantity: true, showAddress: true, showDistrict: true, showNote: false, 
            nameLabel: 'আপনার নাম', phoneLabel: 'মোবাইল নম্বর',
            addressLabel: 'সম্পূর্ণ ঠিকানা (গ্রাম/মহল্লা, থানা, জেলা)', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'অতিরিক্ত নির্দেশনা', quantityLabel: 'কয় কপি নিবেন?',
            formLayout: 'two-col',
            unitLabel: 'কপি', presetQuantities: '1, 2, 3', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true,
            bundles: [
                { qty: 2, discountText: 'স্পেশাল ছাড়' },
                { qty: 3, discountText: 'মেগা ডিসকাউন্ট (উপহারের জন্য সেরা)' },
            ],
            
            showDeliveryInfo: true, insideDhakaCharge: 0, outsideDhakaCharge: 0, showDeliveryBreakdown: true,
            
            buttonText: 'অর্ডার কনফার্ম করুন — ৳০ অগ্রিম', 
            buttonBgColor: '#d97706', buttonTextColor: '#ffffff', 
            buttonBorderRadius: 8, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '✅', buttonSubText: 'হাতে পেয়ে, চেক করে সম্পূর্ণ টাকা পে করবেন',
            showTrustBadges: true,
            trustBadges: [
                { icon: '🚚', text: 'ফ্রি হোম ডেলিভারি', show: true },
                { icon: '🛡️', text: '১০০% মানিব্যাক গ্যারান্টি', show: true },
                { icon: '👀', text: 'চেক করে নেওয়ার সুযোগ', show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি', show: true },
            ],
            showUrgency: true, urgencyText: '🔥 স্টক ও ফ্রি ডেলিভারি অফার প্রায় শেষের দিকে!',
            urgencyBgColor: '#fef3c7', urgencyTextColor: '#b45309',
            showSocialProof: true,
            socialProofText: '🟢 বর্তমানে ৯৪ জন এই পেজটি দেখছেন',
            socialProofIcon: '🔥',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true,
            mobileStickyText: '🛒 অর্ডার করুন (ফ্রি ডেলিভারি)',
            mobileStickyBg: '#ffffff',
            themeColor: '#064e3b',
            labelColor: '#334155', inputBorderColor: '#cbd5e1', inputBgColor: '#f8fafc', inputRadius: 8,
        }),
    },
};