// resources/js/Features/PageBuilder/Templates/RiyadusSalihinTemplate.js
import { node, container } from './helpers';

export const RIYADUS_SALIHIN_TEMPLATE = {
    ROOT: container({ 
        bgColor: '#ffffff', 
        bgType: 'color', 
        gap: 0, 
        paddingTop: 0, 
        paddingBottom: 0 
    }, [
        'hero-riyadus', 
        'reflection-riyadus',
        'product-riyadus', 
        'content-riyadus',
        'benefits-riyadus',
        'testimonials-riyadus',
        'countdown-riyadus',
        'checkout-riyadus',
    ]),

    'hero-riyadus': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#064e3b', // Deep Green (Matched from new cover)
            bgGradientTo: '#022c22',
            bgGradientDirection: 180,
            bgImage: '',
            overlayColor: '#000000',
            overlayOpacity: 10,
            minHeight: 650,
            paddingTop: 120,
            paddingBottom: 100,
            paddingLeft: 24,
            paddingRight: 24,
            contentAlign: 'center',
            contentMaxWidth: 900,
            contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '🌙 রমজান স্পেশাল অফার — ৭৫% বিশাল ছাড়!',
            badgeColor: '#064e3b',
            badgeBgColor: '#ffffff', // White badge for contrast
            title: 'রিয়াদুস সালেহীন\n(৪ খণ্ডের সম্পূর্ণ সেট)',
            titleSize: 56,
            titleWeight: '900',
            titleColor: '#ffffff',
            titleLineHeight: 1.2,
            titleLetterSpacing: -0.02,
            subtitle: 'আপনার পরিবারে প্রতিদিন মাত্র ১০ মিনিট দ্বীনি তালিম শুরু করুন। সন্তানদের হাতে শুধু দামী মোবাইল নয়, তুলে দিন আল্লাহভীতি ও নবীজির আদর্শ।',
            subtitleSize: 20,
            subtitleColor: '#ecfdf5',
            subtitleMaxWidth: 750,
            subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '📖 অর্ডার করুন — মাত্র ৮৯৯ ৳',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#ffffff', // White button
            primaryBtnTextColor: '#064e3b', // Green text on white button
            primaryBtnBorderColor: '#ffffff',
            primaryBtnBorderRadius: 8,
            primaryBtnSize: 'xl',
            showSecondaryBtn: true,
            secondaryBtnText: 'বিস্তারিত জানুন',
            secondaryBtnUrl: '#reflection',
            secondaryBtnStyle: 'outline',
            secondaryBtnBgColor: 'transparent',
            secondaryBtnTextColor: '#ffffff',
            secondaryBtnBorderColor: '#ffffff',
            secondaryBtnBorderRadius: 8,
            secondaryBtnSize: 'xl',
            showStats: true,
            stats: [
                { value: '৪ খণ্ড', label: 'সম্পূর্ণ সেট', show: true, color: '#ffffff' },
                { value: '৩০৫০ ৳', label: 'মুদ্রিত মূল্য', show: true, color: '#ffffff' },
                { value: '৭৫%', label: 'বিশাল ছাড়', show: true, color: '#ffffff' },
            ],
            decorShape: 'dots',
            decorColor: '#ffffff',
            decorOpacity: 15,
            animation: 'slideUp',
            animationDelay: '0',
        }),
    },

    'reflection-riyadus': {
        ...node('FeaturesWidget', {
            sectionTitle: '🛑 একটু ভেবে দেখুন...',
            sectionSubtitle: 'আপনি কি চান আপনার শেষ বয়সটা বৃদ্ধাশ্রমে কাটুক? নাকি সন্তানের পরম সেবায়?',
            titleColor: '#991b1b', subtitleColor: '#064e3b',
            titleSize: 36, subtitleSize: 20, headerAlign: 'center',
            columns: 2, layout: 'horizontal', gap: 24,
            bgType: 'color', bgColor: '#f0fdf4', // Very light green
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#dcfce7', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'sm', cardPadding: 30,
            iconShape: 'circle', iconBg: '#fef2f2', iconColor: '#b91c1c', iconSize: 'lg',
            itemTitleColor: '#064e3b', itemDescColor: '#475569',
            itemTitleSize: 18, itemDescSize: 16, itemDescLineHeight: 1.6,
            showNumbers: false,
            items: [
                { title: 'দ্বীনি শিক্ষার অভাব', description: 'আজ আমরা ব্যস্ততার অজুহাতে সন্তানকে দ্বীন শেখাচ্ছি না। তাদের হাতে তুলে দিচ্ছি দামী মোবাইল, কিন্তু দিচ্ছি না আল্লাহভীতি।', icon: '📱', iconBg: '', iconColor: '' },
                { title: 'ভবিষ্যতের পরিণতি', description: 'যে সন্তান আল্লাহর ভয় জানে না, রাসূল ﷺ-এর আদর্শ জানে না, সে বড় হয়ে একদিন নিজের মা-বাবাকেই বোঝা মনে করতে পারে। 😢', icon: '⚠️', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'product-riyadus': {
        ...node('BookWidget', {
            showTitle: true, showGallery: true, showDescription: true,
            showMeta: true, showWriter: true, showPublication: false,
            showPages: false, showLanguage: true,
            showPrice: true, showRating: true, showCta: true,
            titleOverride: 'রিয়াদুস সালেহীন (৪ খণ্ড সেট)',
            writerName: 'ইমাম ইয়াহইয়া ইবন শরফ আল‑নববী (রহ.)',
            publicationName: '',
            totalPages: '',
            language: 'বাংলা অনুবাদ',
            descriptionOverride: 'এই কালজয়ী হাদিস গ্রন্থে রয়েছে এমন সব হাদিস, যা একজন মুসলিমের চরিত্র, পরিবার ও সমাজ গঠনের জন্য পূর্ণাঙ্গ নির্দেশনা দেয়। আপনার পরিবারে প্রতিদিন মাত্র ১০ মিনিট দ্বীনি তালিম শুরু করার জন্য সবচেয়ে সহজ এবং কার্যকর বই এটি।',
            shortDescLength: 350,
            ratingValue: 5.0,
            reviewCount: 1540,
            starColor: '#059669',
            currencySymbol: '৳',
            layout: 'row',
            maxWidth: 1060,
            metaStyle: 'grid', 
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 80, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            imageBorderRadius: 12, imageShadow: '2xl',
            titleSize: 36, titleWeight: '800', titleColor: '#064e3b',
            metaLabelColor: '#64748b', metaValueColor: '#0f172a',
            descColor: '#334155', descSize: 16, descLineHeight: 1.8,
            priceColor: '#059669', priceSize: 42,
            ctaText: '🛒 ক্যাশ অন ডেলিভারিতে অর্ডার করুন',
            ctaUrl: '#checkout',
            ctaBg: '#064e3b', ctaTextColor: '#ffffff', ctaRadius: 8,
            ctaFullWidth: true,
        }),
    },

    'content-riyadus': {
        ...node('FeaturesWidget', {
            sectionTitle: '🌙 বইটিতে কী কী পাবেন?',
            sectionSubtitle: 'এই গ্রন্থে রয়েছে হাজারের বেশি সহীহ হাদিস যা জীবন বদলে দেওয়ার জন্য যথেষ্ট।',
            titleColor: '#064e3b', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 32,
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#d1fae5', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 32,
            iconShape: 'soft-square', iconBg: '#d1fae5', iconColor: '#064e3b', iconSize: 'xl',
            itemTitleColor: '#022c22', itemDescColor: '#475569',
            itemTitleSize: 18, itemDescSize: 15, itemDescLineHeight: 1.6,
            showNumbers: false,
            items: [
                { title: 'মা-বাবার খেদমত ও সম্মান', description: 'মা-বাবার প্রতি সন্তানের দায়িত্ব ও কর্তব্য সম্পর্কে রাসূল ﷺ এর অমূল্য নির্দেশনা।', icon: '🤲', iconBg: '', iconColor: '' },
                { title: 'বড়দের শ্রদ্ধা ও ছোটদের দয়া', description: 'পরিবার ও সমাজে বয়োজ্যেষ্ঠদের সম্মান এবং ছোটদের প্রতি স্নেহ প্রদর্শনের শিক্ষা।', icon: '👨‍👩‍👧‍👦', iconBg: '', iconColor: '' },
                { title: 'সুন্দর চরিত্র ও আখলাক', description: 'কীভাবে নিজের চরিত্রকে নববী আদর্শে রাঙিয়ে তোলা যায় তার বিস্তারিত বর্ণনা।', icon: '✨', iconBg: '', iconColor: '' },
                { title: 'ধৈর্য, কৃতজ্ঞতা ও আল্লাহভীতি', description: 'বিপদে ধৈর্য ধারণ এবং আল্লাহর নিয়ামতের শুকরিয়া আদায়ের ফজিলত।', icon: '❤️', iconBg: '', iconColor: '' },
                { title: 'শান্তি প্রতিষ্ঠার শিক্ষা', description: 'পরিবার ও সমাজে কীভাবে শান্তি ও সম্প্রীতি বজায় রাখা যায় তার গাইডলাইন।', icon: '🕊️', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'benefits-riyadus': {
        ...node('FeaturesWidget', {
            sectionTitle: '🏡 এই বই আপনার পরিবারে কী পরিবর্তন আনতে পারে?',
            sectionSubtitle: 'পারিবারিক তালিম কেন প্রতিটি মুসলিম ঘরের জন্য আবশ্যক।',
            titleColor: '#064e3b', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 2, layout: 'horizontal', gap: 24,
            bgType: 'color', bgColor: '#ecfdf5', // Light green bg
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#b91c1c22', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'none', cardPadding: 24,
            iconShape: 'circle', iconBg: '#064e3b', iconColor: '#ffffff', iconSize: 'md',
            itemTitleColor: '#022c22', itemDescColor: '#475569',
            itemTitleSize: 18, itemDescSize: 15, itemDescLineHeight: 1.5,
            showNumbers: false,
            items: [
                { title: 'দ্বীনি বুঝ তৈরি হবে', description: 'প্রতিদিন মাত্র ১০ মিনিট তালিম করলে সন্তান ও স্ত্রীর মধ্যে দ্বীনি বুঝ তৈরি হবে।', icon: '📖', iconBg: '', iconColor: '' },
                { title: 'পারিবারিক শান্তি', description: 'সংসার থেকে হিংসা, বিদ্বেষ ও ঝগড়া কমে গিয়ে প্রশান্তি নেমে আসবে।', icon: '🕊️', iconBg: '', iconColor: '' },
                { title: 'মা-বাবার প্রতি ভালোবাসা', description: 'সন্তানদের অন্তরে পিতা-মাতার প্রতি অকৃত্রিম ভালোবাসা ও সম্মান তৈরি হবে।', icon: '❤️', iconBg: '', iconColor: '' },
                { title: 'সদকায়ে জারিয়া', description: 'আপনার মৃত্যুর পর এই নেককার সন্তানরাই হবে আপনার জন্য সদকায়ে জারিয়া।', icon: '🌱', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'testimonials-riyadus': {
        ...node('TestimonialWidget', {
            title: 'পাঠকদের অনুভূতি',
            subtitle: 'যারা পরিবারে তালিম শুরু করেছেন তাদের জীবনের কিছু পরিবর্তন।',
            bgColor: '#ffffff', padding: 80,
            layout: 'grid', columns: 3, cardStyle: 'modern',
            starColor: '#059669', showVerified: true,
            cardRadius: 16, cardShadow: 'sm',
            reviews: [
                { name: 'আহমেদ শরীফ', role: 'ঢাকা', text: 'অফারে এত কম দামে ৪ খণ্ডের সেট পাবো ভাবিনি। এখন প্রতিদিন মাগরিবের পর পরিবারের সবাইকে নিয়ে বইটি পড়ি। আলহামদুলিল্লাহ, ঘরের পরিবেশটাই পাল্টে গেছে।', stars: 5, avatar: '' },
                { name: 'ফাতেমা আক্তার', role: 'শিক্ষিকা', text: 'সন্তানদের মোবাইল আসক্তি দূর করার জন্য তালিম শুরু করি। এখন তারা নিজেরাই বই নিয়ে বসে পড়ে হাদিস শোনার জন্য।', stars: 5, avatar: '' },
                { name: 'মাওলানা কামরুল', role: 'কুমিল্লা', text: 'বইয়ের প্রিন্ট এবং বাইন্ডিং খুবই চমৎকার। প্রতিটি পরিবারের ড্রয়িংরুমে অন্য বইয়ের বদলে এই বইটি থাকা উচিত।', stars: 5, avatar: '' },
            ],
        }),
    },

    'countdown-riyadus': {
        ...node('CountdownWidget', {
            mode: 'evergreen', durationHours: 12,
            showDays: false,
            showHeadline: true,
            headline: '⏳ রমজান স্পেশাল অফারটি যেকোনো সময় শেষ হতে পারে!',
            headlineSize: 30, headlineColor: '#064e3b', headlineWeight: '900',
            showSubtitle: true,
            subtitle: '৩০৫০ টাকার ৪ খণ্ডের সেটটি মাত্র ৮৯৯ টাকায় পেতে এখনি অর্ডার করুন।',
            subtitleColor: '#475569', subtitleSize: 16,
            expiredMessage: '⚠️ অফার শেষ হয়ে গেছে।',
            displayStyle: 'modern', boxSize: 'lg', 
            boxBg: '#ffffff', boxTextColor: '#064e3b',
            labelColor: '#475569', boxRadius: 12, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '🔥 খুবই সীমিত স্টক! স্টক শেষ হওয়ার আগেই অর্ডার করুন।',
            urgencyBarBg: '#fee2e2', urgencyBarText: '#991b1b',
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
            shadow: 'md',
        }),
    },

    'checkout-riyadus': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 40, borderRadius: 16,
            shadow: '2xl', borderWidth: 1, borderColor: '#e2e8f0',
            showHeader: true, headerText: '📖 এখনই অর্ডার করুন মাত্র ৮৯৯ টাকায়',
            headerBgColor: '#ecfdf5', headerTextColor: '#064e3b', headerSize: 22,
            showProductSummary: true, summaryLayout: 'card', 
            showRating: true, ratingValue: 5, reviewCount: 1540,
            showMultiProduct: false, multiProductLabel: '',
            showQuantity: true, showAddress: true, showDistrict: true, showNote: true,
            nameLabel: 'আপনার নাম', phoneLabel: 'মোবাইল নাম্বার',
            addressLabel: 'সম্পূর্ণ ঠিকানা', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'অতিরিক্ত নির্দেশনা (যদি থাকে)', quantityLabel: 'সেট সংখ্যা',
            formLayout: 'two-col',
            unitLabel: 'সেট', presetQuantities: '1, 2, 3', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: false, 
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার কনফার্ম করুন (ক্যাশ অন ডেলিভারি)',
            buttonBgColor: '#064e3b', buttonTextColor: '#ffffff',
            buttonBorderRadius: 8, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '🚀', buttonSubText: '৩০৫০ টাকার সেট পাচ্ছেন মাত্র ৮৯৯ টাকায়',
            showTrustBadges: true,
            trustBadges: [
                { icon: '📦', text: 'ক্যাশ অন ডেলিভারি', show: true },
                { icon: '🚚', text: 'সারা দেশে হোম ডেলিভারি', show: true },
                { icon: '💯', text: 'অরিজিনাল প্রিন্ট', show: true },
            ],
            showUrgency: true, urgencyText: '🔥 অফার মূল্যে স্টক প্রায় শেষের দিকে!',
            urgencyBgColor: '#fee2e2', urgencyTextColor: '#991b1b',
            showSocialProof: true,
            socialProofText: 'গত ২৪ ঘণ্টায় ৭৮ জন এই সেটটি অর্ডার করেছেন',
            socialProofIcon: '🔥',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true, 
            mobileStickyText: '🛒 অর্ডার করুন — ৮৯৯ ৳',
            mobileStickyBg: '#ffffff',
            themeColor: '#064e3b',
            labelColor: '#334155', inputBorderColor: '#cbd5e1', inputBgColor: '#f8fafc', inputRadius: 8,
        }),
    },
};