// resources/js/Features/PageBuilder/Templates/SahihBukhariTemplate.js
import { node, container } from './helpers';

export const SAHIH_BUKHARI_TEMPLATE = {
    ROOT: container({ 
        bgColor: '#f8fafc', 
        bgType: 'color', 
        gap: 0, 
        paddingTop: 0, 
        paddingBottom: 0 
    }, [
        'hero-bukhari', 
        'product-bukhari', 
        'features-bukhari', 
        'topics-bukhari',
        'video-bukhari',
        'testimonials-bukhari',
        'countdown-bukhari', 
        'faq-bukhari', 
        'checkout-bukhari',
    ]),

    'hero-bukhari': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#0a0a0a', 
            bgGradientTo: '#171717',   
            bgGradientDirection: 180,
            bgImage: '',
            overlayColor: '#000000',
            overlayOpacity: 20,
            minHeight: 650,
            paddingTop: 120,
            paddingBottom: 100,
            paddingLeft: 24,
            paddingRight: 24,
            contentAlign: 'center',
            contentMaxWidth: 900,
            contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '🔥 সীমিত সময়ের অফার — ৭৫% বিশাল ছাড়!',
            badgeColor: '#000000',
            badgeBgColor: '#fef08a', 
            title: 'সহীহ বুখারী শরীফ\n(১–১০ খণ্ড একত্রে)',
            titleSize: 56,
            titleWeight: '900',
            titleColor: '#ffffff',
            titleLineHeight: 1.2,
            titleLetterSpacing: -0.02,
            subtitle: 'সহীহ হাদীসের সবচেয়ে নির্ভরযোগ্য সংকলন এখন আপনার ঘরে। রাসূল ﷺ এর জীবন ও সুন্নাহ জানার জন্য বিশ্বের সবচেয়ে প্রসিদ্ধ হাদীস গ্রন্থ। ১০০% অরিজিনাল ও ঝকঝকে প্রিন্টের গ্যারান্টি।',
            subtitleSize: 20,
            subtitleColor: '#d4d4d8',
            subtitleMaxWidth: 750,
            subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '📖 অর্ডার করুন — মাত্র ১০৯৯ ৳',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#eab308', 
            primaryBtnTextColor: '#000000', 
            primaryBtnBorderColor: '#eab308',
            primaryBtnBorderRadius: 8,
            primaryBtnSize: 'xl',
            showSecondaryBtn: true,
            secondaryBtnText: 'বিস্তারিত দেখুন',
            secondaryBtnUrl: '#product',
            secondaryBtnStyle: 'outline',
            secondaryBtnBgColor: 'transparent',
            secondaryBtnTextColor: '#ffffff',
            secondaryBtnBorderColor: '#eab308', 
            secondaryBtnBorderRadius: 8,
            secondaryBtnSize: 'xl',
            showStats: true,
            stats: [
                { value: '৪টি', label: 'বইয়ের সেট', show: true, color: '#fef08a' },
                { value: '১-১০', label: 'খণ্ড একত্রে', show: true, color: '#fef08a' },
                { value: '৭৫%', label: 'মূল্য ছাড়', show: true, color: '#fef08a' },
            ],
            decorShape: 'dots',
            decorColor: '#ffffff',
            decorOpacity: 10,
            animation: 'slideUp',
            animationDelay: '0',
        }),
    },

    'product-bukhari': {
        ...node('BookWidget', {
            showTitle: true, showGallery: true, showDescription: true,
            showMeta: true, showWriter: true, showPublication: false,
            showPages: true, showLanguage: true,
            showPrice: true, showRating: true, showCta: true,
            titleOverride: 'সহীহ বুখারী শরীফ (৪টি বইয়ের সেট)',
            writerName: 'ইমাম মুহাম্মদ ইবনে ইসমাইল আল‑বুখারী (রহ.)',
            publicationName: '',
            totalPages: '১-১০ খণ্ড একত্রে (৪টি বই)',
            language: 'সহজবোধ্য বাংলা অনুবাদ',
            descriptionOverride: 'এই গ্রন্থে সংকলিত হয়েছে হাজারো সহীহ হাদীস যা মুসলিম জীবনের প্রতিটি দিক নির্দেশনা দেয়। প্রিমিয়াম কোয়ালিটি কাগজ, মজবুত হার্ডকভার বাইন্ডিং এবং স্পষ্ট ও সহজবোধ্য বাংলা অনুবাদে বইটি আপনার ঘরে সংরক্ষণের জন্য সেরা একটি সংগ্রহ। স্টক শেষ হওয়ার আগেই আজই সংগ্রহ করুন।',
            shortDescLength: 350,
            ratingValue: 5.0,
            reviewCount: 1250,
            starColor: '#eab308',
            currencySymbol: '৳',
            layout: 'row',
            maxWidth: 1060,
            metaStyle: 'grid', 
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 100, paddingBottom: 100, paddingLeft: 24, paddingRight: 24,
            imageBorderRadius: 12, imageShadow: '2xl',
            titleSize: 36, titleWeight: '800', titleColor: '#000000',
            metaLabelColor: '#64748b', metaValueColor: '#0f172a',
            descColor: '#334155', descSize: 16, descLineHeight: 1.8,
            priceColor: '#b45309', priceSize: 42,
            ctaText: '🛒 ক্যাশ অন ডেলিভারিতে অর্ডার করুন',
            ctaUrl: '#checkout',
            ctaBg: '#000000', ctaTextColor: '#eab308', ctaRadius: 8, 
            ctaFullWidth: true,
        }),
    },

    'features-bukhari': {
        ...node('FeaturesWidget', {
            sectionTitle: 'কেন সহীহ বুখারী আপনার ঘরে থাকা প্রয়োজন?',
            sectionSubtitle: 'আপনার এবং আপনার পরিবারের ইসলামিক জীবনব্যবস্থা গড়ার এক পূর্ণাঙ্গ গাইডলাইন।',
            titleColor: '#000000', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 32,
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 100, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#e2e8f0', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'md', cardPadding: 40,
            iconShape: 'soft-square', iconBg: '#fefce8', iconColor: '#000000', iconSize: 'xl',
            itemTitleColor: '#000000', itemDescColor: '#475569',
            itemTitleSize: 20, itemDescSize: 15, itemDescLineHeight: 1.6,
            showNumbers: false,
            items: [
                { title: 'নির্ভরযোগ্য গ্রন্থ', description: 'রাসূল ﷺ এর সহীহ হাদীস জানার সবচেয়ে নির্ভরযোগ্য ও বিশ্বস্ত সংকলন।', icon: '📖' },
                { title: 'পূর্ণাঙ্গ দিকনির্দেশনা', description: 'ইসলামিক জীবনব্যবস্থার পূর্ণাঙ্গ দিকনির্দেশনা ও রীতিনীতি।', icon: '🧭' },
                { title: 'জাল হাদীস থেকে সুরক্ষা', description: 'দুর্বল ও জাল হাদীস থেকে বাঁচতে এবং সঠিক আমল করতে সহায়তা করবে।', icon: '🛡️' },
                { title: 'পারিবারিক শিক্ষা', description: 'পরিবার ও সন্তানদের সঠিক ইসলামিক শিক্ষার জন্য অত্যন্ত গুরুত্বপূর্ণ একটি সংগ্রহ।', icon: '👨‍👩‍👧‍👦' },
                { title: 'প্রিমিয়াম কোয়ালিটি', description: 'মজবুত হার্ডকভার বাইন্ডিং ও দীর্ঘদিন সংরক্ষণযোগ্য মানসম্পন্ন প্রিন্ট।', icon: '💎' },
                { title: 'সহজবোধ্য অনুবাদ', description: 'সাধারণ পাঠকদের জন্য অত্যন্ত সহজ ও সাবলীল বাংলা ভাষায় উপস্থাপন।', icon: '✍️' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'topics-bukhari': {
        ...node('FeaturesWidget', {
            sectionTitle: 'এই বইয়ে কী পাবেন?',
            sectionSubtitle: 'একজন মুসলিমের জীবনের প্রায় প্রতিটি বিষয়ের হাদীস এতে সংকলিত রয়েছে।',
            titleColor: '#000000', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'horizontal', gap: 24,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 60, paddingBottom: 100, paddingLeft: 24, paddingRight: 24,
            cardBg: '#f8fafc', cardBorderColor: '#e2e8f0', cardBorderWidth: 1,
            cardRadius: 12, cardShadow: 'none', cardPadding: 24,
            iconShape: 'circle', iconBg: '#000000', iconColor: '#eab308', iconSize: 'md',
            itemTitleColor: '#000000', itemDescColor: '#475569',
            itemTitleSize: 18, itemDescSize: 14, itemDescLineHeight: 1.5,
            showNumbers: false,
            items: [
                { title: 'ঈমান ও আকীদা', description: 'ইসলামের মূল বিশ্বাস, তাওহীদ এবং রিসালাতের উপর ভিত্তি করে ঈমানকে মজবুত করার সঠিক দিকনির্দেশনা।', icon: '✨' },
                { title: 'সালাত, সিয়াম, যাকাত, হজ', description: 'ইসলামের মূল স্তম্ভগুলোর সঠিক নিয়ম-কানুন ও রাসূল (সা.) এর সুন্নাহভিত্তিক নির্ভুল আমল।', icon: '🕌' },
                { title: 'নৈতিকতা ও চরিত্র', description: 'একজন মুমিনের আচার-আচরণ, সততা এবং উত্তম চরিত্র গঠনের জন্য প্রয়োজনীয় দিকনির্দেশনা।', icon: '🤝' },
                { title: 'পরিবার ও সমাজ', description: 'পিতামাতার অধিকার, স্বামী-স্ত্রীর সম্পর্ক, সন্তান লালন-পালন এবং সামাজিক দায়িত্ববোধ।', icon: '🏡' },
                { title: 'ব্যবসা-বাণিজ্য', description: 'হালাল উপার্জন, ব্যবসার সঠিক নিয়ম এবং সুদ-ঘুষ ও হারাম থেকে বেঁচে থাকার উপায়।', icon: '⚖️' },
                { title: 'দোয়া ও আখলাক', description: 'দৈনন্দিন জীবনের প্রয়োজনীয় দোয়া, যিকির এবং আল্লাহর নৈকট্য লাভের আমলসমূহ।', icon: '🤲' },
            ],
            animation: 'fadeUp', staggerDelay: '0.1',
        }),
    },

    'video-bukhari': {
        ...node('VideoWidget', {
            sectionTitle: 'বইটির সরাসরি ভিডিও রিভিউ দেখুন',
            sectionSubtitle: 'অরিজিনাল বইয়ের প্রিন্ট কোয়ালিটি, বাইন্ডিং ও ভেতরের পাতা ভিডিওতে দেখে নিশ্চিত হয়ে অর্ডার করুন।',
            titleColor: '#000000', subtitleColor: '#475569',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 
            platform: 'youtube',
            layout: 'center',
            maxWidth: 800,
            aspectRatio: '16/9',
            borderRadius: 16,
            shadow: '2xl',
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            showControls: true, autoplay: false, loop: false, muted: false,
        }),
    },

    'testimonials-bukhari': {
        ...node('TestimonialWidget', {
            title: 'গ্রাহকদের রিভিউ',
            subtitle: 'যারা আমাদের থেকে বুখারী শরীফের এই সেটটি নিয়েছেন তাদের মতামত।',
            bgColor: '#ffffff', padding: 80,
            layout: 'masonry', cardStyle: 'modern',
            starColor: '#eab308', showVerified: true,
            cardRadius: 16, cardShadow: 'sm',
            reviews: [
                { name: 'শফিকুল ইসলাম', role: 'ঢাকা (Verified Buyer)', text: 'আলহামদুলিল্লাহ, বইগুলোর বাইন্ডিং এবং কাগজের মান খুব ভালো। এত কম দামে পুরো সেট পাবো ভাবিনি। প্যাকেজিংও অনেক সুরক্ষিত ছিল।', stars: 5, avatar: '' },
                { name: 'মাওলানা ইব্রাহিম', role: 'চট্টগ্রাম (Verified Buyer)', text: 'অনুবাদ খুব চমৎকার এবং সহজবোধ্য। প্রতিটি মুসলিম পরিবারে এই সেটটি থাকা জরুরি। যারা অরিজিনাল বই খুঁজছেন, চোখ বন্ধ করে নিতে পারেন।', stars: 5, avatar: '' },
                { name: 'তারেক রহমান', role: 'সিলেট (Verified Buyer)', text: 'অর্ডার করার ২ দিনের মধ্যেই হাতে পেয়েছি। ডেলিভারি ম্যানের সামনে চেক করে পেমেন্ট করেছি। জাযাকাল্লাহু খাইরান।', stars: 5, avatar: '' },
            ],
        }),
    },

    'countdown-bukhari': {
        ...node('CountdownWidget', {
            mode: 'evergreen', durationHours: 4, // Reduced time for higher urgency
            showDays: false,
            showHeadline: true,
            headline: '⏳ স্টক শেষ হওয়ার আগেই আপনার কপিটি নিশ্চিত করুন!',
            headlineSize: 30, headlineColor: '#000000', headlineWeight: '900',
            showSubtitle: true,
            subtitle: '৭৫% ছাড়ে এই অফারটি খুবই সীমিত সময়ের জন্য।',
            subtitleColor: '#475569', subtitleSize: 16,
            expiredMessage: '⚠️ অফার শেষ হয়ে গেছে।',
            displayStyle: 'modern', boxSize: 'lg', 
            boxBg: '#ffffff', boxTextColor: '#000000',
            labelColor: '#475569', boxRadius: 12, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '🔥 আজকে মাত্র ১২টি সেট বাকি আছে!', // Reduced stock number for perceived scarcity
            urgencyBarBg: '#fefce8', urgencyBarText: '#dc2626', // Made urgency text red for attention
            bgType: 'color', bgColor: '#f8fafc',
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
            shadow: 'md',
        }),
    },

    'faq-bukhari': {
        ...node('FaqWidget', {
            title: 'সাধারণ প্রশ্নোত্তর (FAQ)',
            subtitle: 'অর্ডার করার আগে আপনার মনের কনফিউশন দূর করুন।',
            bgColor: '#ffffff', padding: 80,
            accentColor: '#000000', iconStyle: 'chevron', layout: 'accordion', 
            questions: [
                { q: 'এই সেটে মোট কয়টি বই থাকবে?', a: 'এই সেটে ১ থেকে ১০ খণ্ড একত্রে মোট ৪টি বই (হার্ডকভার) থাকবে।' },
                { q: 'বইয়ের প্রিন্ট ও কাগজের কোয়ালিটি কেমন হবে?', a: 'আমরা দিচ্ছি ১০০% অরিজিনাল, ঝকঝকে সাদা কাগজের গ্যারান্টি। কোনো কারণে প্রিন্টে সমস্যা থাকলে আমরা নিজ খরচে রিপ্লেস করে দেবো।' },
                { q: 'ডেলিভারি পেতে কতদিন সময় লাগবে?', a: 'ঢাকার ভেতরে ১-২ দিন এবং ঢাকার বাইরে ২-৩ দিন সময় লাগে।' },
                { q: 'বই হাতে পেয়ে টাকা দেওয়ার সুযোগ আছে কি?', a: 'হ্যাঁ! ১০০% ক্যাশ অন ডেলিভারি। বই হাতে পেয়ে, চেক করে তারপর টাকা পেমেন্ট করবেন। অগ্রিম কোনো টাকা দিতে হবে না।' },
                { q: 'বই ছেঁড়া বা নষ্ট থাকলে কী করবো?',  a: 'ডেলিভারি ম্যানের সামনে চেক করবেন। কোনো সমস্যা পেলে রিটার্ন করতে পারবেন, আমরা নিজ খরচে নতুন সেট পাঠিয়ে দেবো।' },
            ],
        }),
    },

    'checkout-bukhari': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 40, borderRadius: 16,
            shadow: '2xl', borderWidth: 1, borderColor: '#e2e8f0',
            showHeader: true, headerText: '📖 এখনই অর্ডার করুন মাত্র ১০৯৯ টাকায়',
            headerBgColor: '#fafafa', headerTextColor: '#000000', headerSize: 22,
            showProductSummary: true, summaryLayout: 'card', 
            showRating: true, ratingValue: 5, reviewCount: 1250,
            showMultiProduct: false, multiProductLabel: '',
            showQuantity: true, showAddress: true, showDistrict: true, showNote: true,
            nameLabel: 'আপনার পূর্ণ নাম', phoneLabel: 'সচল ফোন নম্বর',
            addressLabel: 'বিস্তারিত ডেলিভারি ঠিকানা', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'অতিরিক্ত নির্দেশনা (যদি থাকে)', quantityLabel: 'কপি সংখ্যা',
            formLayout: 'two-col',
            unitLabel: 'সেট', presetQuantities: '1, 2, 3', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: false, 
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার কনফার্ম করুন — ক্যাশ অন ডেলিভারি',
            buttonBgColor: '#000000', buttonTextColor: '#eab308',
            buttonBorderRadius: 8, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '🚀', buttonSubText: 'বই হাতে পেয়ে টাকা পরিশোধ করবেন', // Stronger reassurance at the final click
            showTrustBadges: true,
            trustBadges: [
                { icon: '📚', text: '১০০% অরিজিনাল',  show: true },
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি', show: true },
                { icon: '🚚', text: 'দ্রুত ডেলিভারি', show: true },
                { icon: '↩️', text: 'রিটার্ন গ্যারান্টি', show: true }, // Changed to Guarantee for higher trust
            ],
            showUrgency: true, urgencyText: '🔥 আজকে মাত্র ১২টি সেট স্টকে অবশিষ্ট আছে!',
            urgencyBgColor: '#fee2e2', urgencyTextColor: '#dc2626', // Red background for urgent checkout alert
            showSocialProof: true,
            socialProofText: 'এই মুহূর্তে ৩ জন এই পেজটি দেখছেন', // Live view simulation
            socialProofIcon: '👁️',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true,
            mobileStickyText: '📖 অর্ডার করুন — ১০৯৯ ৳',
            mobileStickyBg: '#ffffff',
            themeColor: '#000000',
            labelColor: '#334155', inputBorderColor: '#cbd5e1', inputBgColor: '#f8fafc', inputRadius: 8,
        }),
    },
};