// resources/js/Features/PageBuilder/Templates/SukkariRotabTemplate.js
import { node, container } from './helpers';

export const SUKKARI_ROTAB_TEMPLATE = {
    ROOT: container({ bgColor: '#fffbeb', bgType: 'color', gap: 0, paddingTop: 0, paddingBottom: 0 }, [
        'hero-sukkari', 
        'problem-sukkari',     // 2. Problem Section (New)
        'product-sukkari', 
        'breakdown-sukkari',   // 4. Breakdown Section (New)
        'benefits-sukkari', 
        'why-us-sukkari',
        'testimonials-sukkari',// 6. Social Proof (New)
        'countdown-sukkari',   // 7. Offer + Urgency
        'checkout-sukkari',
    ]),

    'hero-sukkari': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#fffbeb',
            bgGradientTo: '#fef3c7',
            bgGradientDirection: 145,
            minHeight: 520,
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center', contentMaxWidth: 820, contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '🔥 মেটা স্পেশাল অফার',
            badgeColor: '#b45309', badgeBgColor: '#fde68a',
            title: 'বাছাইকৃত গাছপাকা সৌদি\nসুক্কারি রোতাব!',
            titleSize: 52, titleWeight: '900', titleColor: '#78350f',
            titleLineHeight: 1.1, titleLetterSpacing: -0.02,
            subtitle: '⭐ গত ৬ বছর ধরে ২ লক্ষ + কাস্টমারের বিশ্বাসই আমাদের সবচেয়ে বড় অর্জন। মুখে দিলেই গলে যাওয়া অসাধারণ স্বাদের ১০০% অরিজিনাল সুক্কারি রোতাব।',
            subtitleSize: 18, subtitleColor: '#92400e', subtitleMaxWidth: 650, subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '🛒 অফার মূল্যে অর্ডার করুন',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#d97706', primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#d97706', primaryBtnBorderRadius: 50, primaryBtnSize: 'lg',
            showSecondaryBtn: false,
            showStats: true,
            stats: [
                { value: '২ লক্ষ+', label: 'সন্তুষ্ট কাস্টমার',  show: true },
                { value: '১০০%',   label: 'অরিজিনাল পণ্য',     show: true },
                { value: '−২০°C', label: 'কোল্ড চেইন', show: true },
            ],
            decorShape: 'blob-tr', decorColor: '#fcd34d', decorOpacity: 30,
            animation: 'slideUp', animationDelay: '0',
        }),
    },

    'problem-sukkari': {
        ...node('FeaturesWidget', {
            sectionTitle: 'মিষ্টি খেতে মন চায় কিন্তু চিনির ভয়ে খেতে পারছেন না?',
            sectionSubtitle: 'অরিজিনাল রোতাব খেজুরের নামে বাজারে নকল খেজুর বিক্রি হচ্ছে প্রতিনিয়ত।',
            titleColor: '#dc2626', subtitleColor: '#78350f',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fff1f2',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fecdd3', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fee2e2', iconColor: '#dc2626', iconSize: 'md',
            itemTitleColor: '#78350f', itemDescColor: '#92400e',
            itemTitleSize: 16, itemDescSize: 15,
            showNumbers: false,
            items: [
                { title: 'চিনির ক্ষতিকর দিক', description: 'মিষ্টি জাতীয় খাবারে থাকা চিনি ডায়াবেটিস ও অন্যান্য রোগের প্রধান কারণ।', icon: '❌', iconBg: '', iconColor: '' },
                { title: 'আসল রোতাব পাওয়া কঠিন', description: 'বাজারে সুক্কারি রোতাবের নামে লোকাল মিষ্টি মেশানো খেজুর বিক্রি হয়।', icon: '❌', iconBg: '', iconColor: '' },
                { title: 'সতেজতা নষ্ট হওয়া', description: 'কোল্ড চেইন মেইনটেইন না করায় রোতাব খেজুর তার আসল স্বাদ ও নরম ভাব হারিয়ে ফেলে।', icon: '❌', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    'product-sukkari': {
        ...node('ProductWidget', {
            layout: 'side-by-side', maxWidth: 1000,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            imageRatio: '1:1', imageBorderRadius: 20, imageShadow: 'lg',
            showGallery: true,
            showBadge: true, badgeText: 'বেস্ট সেলার', badgeBg: '#d97706', badgeColor: '#ffffff',
            showTitle: true, titleSize: 32, titleWeight: '800', titleColor: '#78350f', titleLineHeight: 1.25,
            showPrice: true, priceColor: '#d97706', priceSize: 42, priceWeight: '900',
            showOriginalPrice: true, originalPrice: 1200, showDiscountBadge: true, currencySymbol: '৳',
            showRating: true, ratingValue: 4.9, reviewCount: 2450, starColor: '#f59e0b',
            showDescription: true, descriptionSize: 16, descriptionColor: '#92400e', descriptionLines: 6,
            descriptionText: 'রাসূলুল্লাহ (সা.) বলেন, "তোমাদের কেউ রোজা রাখলে খেজুর দিয়ে যেন ইফতার করে, খেজুর না হলে পানি দ্বারা; নিশ্চয় পানি পবিত্র।"\n(তিরমিজী ও আবু দাউদ; আলফিয়্যাতুল হাদিস: ৫৬২, পৃষ্ঠা: ১৩১-১৩২)\n\nসুক্কারি রোতাব মুখে দিলেই গলে যায় এবং এর স্বাদ অনেকটা ক্যারামেলের মতো।',
            showSpecs: true,
            specs: [
                { icon: '🌴', label: 'উৎস',    value: 'সরাসরি সৌদি আরব থেকে আমদানীকৃত', show: true },
                { icon: '❄️', label: 'সংরক্ষণ', value: '−২০°C তাপমাত্রায় কোল্ড চেইন', show: true },
                { icon: '✅', label: 'ধরণ', value: 'গাছপাকা রোতাব (নরম ও রসালো)', show: true },
            ],
            showTrust: true,
            trustItems: [
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি', bg: '#fff7ed', color: '#ea580c', show: true },
                { icon: '🔍', text: 'চেক করে নেওয়ার সুযোগ', bg: '#f0fdf4', color: '#16a34a', show: true },
            ],
            showStock: true, stockText: '🔥 স্টক প্রায় শেষের দিকে!', stockBg: '#fef3c7', stockColor: '#b45309',
            showCta: true,
            ctaText: '🛒 এখনই অর্ডার করুন',
            ctaUrl: '#checkout', ctaBg: '#d97706', ctaTextColor: '#ffffff',
            ctaRadius: 50, ctaSize: 'lg',
            ctaSubText: 'অগ্রিম কোনো টাকা দিতে হবে না',
            animation: 'fadeUp',
        }),
    },

    'breakdown-sukkari': {
        ...node('FeaturesWidget', {
            sectionTitle: 'সুক্কারি রোতাবের বিশেষত্ব',
            sectionSubtitle: 'কেন এই খেজুরটি সবার প্রিয়?',
            titleColor: '#78350f', subtitleColor: '#92400e',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fef3c7',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fcd34d', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fef3c7', iconColor: '#d97706', iconSize: 'xl',
            itemTitleColor: '#78350f', itemDescColor: '#92400e',
            itemTitleSize: 18, itemDescSize: 14,
            showNumbers: false,
            items: [
                { title: 'মুখে দিলেই গলে যায়', description: 'অত্যন্ত নরম ও রসালো হওয়ায় এটি চিবানোর আগেই মুখে গলে যায়।', icon: '🤤', iconBg: '', iconColor: '' },
                { title: 'প্রাকৃতিক ক্যারামেল মিষ্টি', description: 'চিনির নিখুঁত বিকল্প, এর স্বাদ একেবারে ক্যারামেলের মতো।', icon: '🍯', iconBg: '', iconColor: '' },
                { title: 'কোল্ড স্টোরেজ ফ্রেশনেস', description: '−২০° তাপমাত্রায় সংরক্ষিত হওয়ায় এর স্বাদ ও মান থাকে ১০০% অটুট।', icon: '❄️', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    'benefits-sukkari': {
        ...node('FeaturesWidget', {
            sectionTitle: 'সুক্কারি রোতাব খেজুরের উপকারিতা',
            sectionSubtitle: 'কেন সুক্কারি খেজুর আপনার প্রতিদিনের খাদ্যতালিকায় রাখা উচিত?',
            titleColor: '#78350f', subtitleColor: '#92400e',
            titleSize: 28, subtitleSize: 16, headerAlign: 'center',
            columns: 2, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fffbeb',
            paddingTop: 60, paddingBottom: 40, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fde68a', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fef3c7', iconColor: '#d97706', iconSize: 'lg',
            itemTitleColor: '#78350f', itemDescColor: '#92400e',
            itemTitleSize: 18, itemDescSize: 15,
            showNumbers: false,
            items: [
                { title: 'তাৎক্ষণিক শক্তি', description: 'প্রাকৃতিক শর্করা থাকায় এটি দ্রুত ক্লান্তি দূর করে তাৎক্ষণিক শক্তি দেয়।', icon: '⚡', iconBg: '', iconColor: '' },
                { title: 'প্রাকৃতিক মিষ্টি', description: 'কৃত্রিম চিনি এড়িয়ে মিষ্টি খাওয়ার সেরা প্রাকৃতিক উপায়।', icon: '🍯', iconBg: '', iconColor: '' },
                { title: 'উন্নত হজমশক্তি', description: 'উচ্চ ফাইবার সমৃদ্ধ, যা হজমশক্তি বাড়াতে দারুণ কাজ করে।', icon: '🌿', iconBg: '', iconColor: '' },
                { title: 'হাড় মজবুত রাখে', description: 'প্রয়োজনীয় মিনারেল (ক্যালসিয়াম, পটাশিয়াম) দিয়ে হাড় মজবুত রাখে।', icon: '🦴', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    'why-us-sukkari': {
        ...node('FeaturesWidget', {
            sectionTitle: 'আমাদের থেকে কেন "সুক্কারি রোতাব" কিনবেন?',
            sectionSubtitle: 'অনলাইনে প্রতারণার ভিড়ে আমরা দিচ্ছি ১০০% অরিজিনাল পণ্যের গ্যারান্টি',
            titleColor: '#78350f', subtitleColor: '#92400e',
            titleSize: 28, subtitleSize: 16, headerAlign: 'center',
            columns: 2, layout: 'horizontal', gap: 20,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 40, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#fffbeb', cardBorderColor: '#fde68a', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fde68a', iconColor: '#d97706', iconSize: 'md',
            itemTitleColor: '#78350f', itemDescColor: '#92400e',
            itemTitleSize: 16, itemDescSize: 14,
            showNumbers: true,
            items: [
                { title: 'সরাসরি আমদানি', description: 'সরাসরি সৌদি আরবের থেকে আমদানীকৃত গাছ পাকা খেজুর।', icon: '🇸🇦', iconBg: '', iconColor: '' },
                { title: 'কেমিক্যালমুক্ত', description: 'শতভাগ কেমিক্যালমুক্ত, বাছাইকৃত ও স্বাস্থ্যসম্মত উপায়ে প্যাকেজিং করা হয়।', icon: '🛡️', iconBg: '', iconColor: '' },
                { title: 'কঠোর কোল্ড চেইন', description: '−২০° তাপমাত্রায় কঠোর কোল্ড চেইন-এ সতেজতা নিশ্চিত করা হয়।', icon: '❄️', iconBg: '', iconColor: '' },
                { title: '১০০% অরিজিনাল', description: '১০০% সৌদি অরিজিনাল পণ্য, কোনো লোকাল বা নকল নয়।', icon: '✅', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    'testimonials-sukkari': {
        ...node('TestimonialWidget', {
            title: 'গ্রাহকদের রিভিউ',
            subtitle: 'যাঁরা আমাদের সুক্কারি রোতাব কিনেছেন তাঁদের অভিজ্ঞতা',
            bgColor: '#fffbeb', padding: 60,
            layout: 'grid', columns: 2, cardStyle: 'border', borderColor: '#fde68a',
            starColor: '#f59e0b', showVerified: true,
            reviews: [
                { name: 'তানভীর আহমেদ', role: 'ঢাকা', text: 'খেজুরগুলো সত্যি অসাধারণ ছিল! ফ্রিজ থেকে বের করে একটু পর খেলে একদম আইসক্রিমের মতো স্বাদ লাগে। ফ্যামিলির সবাই খুব পছন্দ করেছে।', stars: 5, avatar: '' },
                { name: 'শরিফুল ইসলাম', role: 'রাজশাহী', text: 'অনেক পেজ থেকে সুক্কারি কিনেছি কিন্তু আপনাদেরটার মতো এতো ফ্রেশ আর নরম পাইনি। আপনাদের প্যাকেজিং আর কোল্ড চেইন ডেলিভারি সত্যি প্রশংসনীয়।', stars: 5, avatar: '' },
            ],
        }),
    },

    'countdown-sukkari': {
        ...node('CountdownWidget', {
            mode: 'daily',
            showDays: false,
            showHeadline: true,
            headline: '⏰ স্টক শেষ হওয়ার আগেই অর্ডার করুন!',
            headlineSize: 26, headlineColor: '#b45309', headlineWeight: '800',
            showSubtitle: true,
            subtitle: 'সুক্কারি রোতাবের আজকের স্পেশাল প্রাইস মিস করবেন না।',
            subtitleColor: '#78350f', subtitleSize: 16,
            expiredMessage: '⚠️ আজকের স্পেশাল অফার শেষ হয়েছে।',
            displayStyle: 'card', boxSize: 'md',
            boxBg: '#ffffff', boxTextColor: '#d97706',
            labelColor: '#78350f', boxRadius: 16, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '🔥 দ্রুত শেষ হয়ে যাচ্ছে! আর মাত্র অল্প কিছু বক্স বাকি।',
            urgencyBarBg: '#fef3c7', urgencyBarText: '#b45309',
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 40, paddingBottom: 40, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
        }),
    },

    'checkout-sukkari': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 32, borderRadius: 20,
            shadow: '2xl', borderWidth: 2, borderColor: '#d97706', 
            showHeader: true, headerText: '🔥 স্পেশাল ডিসকাউন্টে অর্ডার কনফার্ম করুন',
            headerBgColor: '#fef3c7', headerTextColor: '#b45309', headerSize: 22,
            showProductSummary: true, summaryLayout: 'row',
            showRating: true, ratingValue: 4.9, reviewCount: 2450,
            showMultiProduct: false,
            showQuantity: true, showAddress: true, showDistrict: true, showNote: false,
            nameLabel: 'আপনার নাম', phoneLabel: 'মোবাইল নম্বর',
            addressLabel: 'সম্পূর্ণ ঠিকানা', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'বিশেষ নির্দেশ', quantityLabel: 'পরিমাণ নির্বাচন করুন',
            formLayout: 'two-col',
            unitLabel: 'কেজি', presetQuantities: '1, 2, 3, 5', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true,
            bundles: [
                { qty: 1, price: 950, highlight: false, badge: '' },
                { qty: 2, price: 1800, highlight: true, badge: 'জনপ্রিয়' }, 
                { qty: 5, price: 4400, highlight: false, badge: 'সুপার সেভার' },
            ],
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার কনফার্ম করুন',
            buttonBgColor: '#d97706', buttonTextColor: '#ffffff',
            buttonBorderRadius: 50, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '✅', buttonSubText: '১০০% ক্যাশ অন ডেলিভারি - প্রোডাক্ট হাতে পেয়ে টাকা দিন',
            showTrustBadges: true,
            trustBadges: [
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি',   show: true },
                { icon: '🔍', text: 'চেক করে নেওয়ার সুযোগ', show: true },
                { icon: '🔒', text: 'নিরাপদ শপিং',    show: true },
            ],
            showUrgency: true, urgencyText: '⚡ দ্রুত আপনার নাম ও ঠিকানা লিখে অর্ডার কনফার্ম করুন!',
            urgencyBgColor: '#fef3c7', urgencyTextColor: '#b45309',
            showSocialProof: true,
            socialProofText: 'গত ১ ঘণ্টায় ৪২ জন অর্ডার কনফার্ম করেছেন',
            socialProofIcon: '🔥',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '',
            showMobileStickyCta: true, 
            mobileStickyText: '🛒 অর্ডার করুন',
            mobileStickyBg: '#ffffff',
            themeColor: '#d97706',
            labelColor: '#78350f', inputBorderColor: '#fcd34d', inputBgColor: '#fffbeb',
        }),
    },
};