// resources/js/Features/PageBuilder/Templates/SukkariMufattalTemplate.js
import { node, container } from './helpers';

export const SUKKARI_MUFATTAL_TEMPLATE = {
    ROOT: container({ bgColor: '#fffcf7', bgType: 'color', gap: 0, paddingTop: 0, paddingBottom: 0 }, [
        'hero-sukkari-mufattal', 
        'problem-sukkari-mufattal',    // 2. Problem Section (New)
        'product-sukkari-mufattal', 
        'breakdown-sukkari-mufattal',  // 4. Breakdown Section (New)
        'benefits-sukkari-mufattal', 
        'why-us-sukkari-mufattal',
        'faq-sukkari-mufattal',
        'testimonials-sukkari-mufattal', 
        'countdown-sukkari-mufattal',  // 7. Offer + Urgency (New)
        'checkout-sukkari-mufattal',
    ]),

    'hero-sukkari-mufattal': {
        ...node('HeroWidget', {
            bgType: 'gradient',
            bgGradientFrom: '#fffcf7',
            bgGradientTo: '#ffedd5',
            bgGradientDirection: 145,
            minHeight: 520,
            paddingTop: 80, paddingBottom: 80, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center', contentMaxWidth: 850, contentVerticalAlign: 'center',
            showBadge: true,
            badgeText: '✨ প্রিমিয়াম কোয়ালিটি',
            badgeColor: '#c2410c', badgeBgColor: '#ffedd5',
            title: 'সরাসরি সৌদি আরবের বিখ্যাত সুক্কারী খেজুর যাবে আপনার ঘরে ইনশাআল্লাহ',
            titleSize: 48, titleWeight: '900', titleColor: '#431407',
            titleLineHeight: 1.15, titleLetterSpacing: -0.02,
            subtitle: 'শরীরকে শক্তি যোগায়, রোগ প্রতিরোধ ক্ষমতা বাড়ায় এবং ক্লান্তি দূর করে। ১০০% ফ্রেশ ও বাছাইকৃত সুক্কারী মুফাত্তাল।',
            subtitleSize: 18, subtitleColor: '#7c2d12', subtitleMaxWidth: 700, subtitleLineHeight: 1.6,
            showPrimaryBtn: true,
            primaryBtnText: '🛒 অর্ডার করতে চাই',
            primaryBtnUrl: '#checkout',
            primaryBtnStyle: 'solid',
            primaryBtnBgColor: '#c2410c', primaryBtnTextColor: '#ffffff',
            primaryBtnBorderColor: '#c2410c', primaryBtnBorderRadius: 50, primaryBtnSize: 'lg',
            showSecondaryBtn: true,
            secondaryBtnText: '📞 01898292795',
            secondaryBtnUrl: 'tel:01898292795',
            secondaryBtnStyle: 'outline',
            secondaryBtnBgColor: 'transparent', secondaryBtnTextColor: '#c2410c',
            secondaryBtnBorderColor: '#c2410c', secondaryBtnBorderRadius: 50, secondaryBtnSize: 'lg',
            showStats: false,
            decorShape: 'blob-tr', decorColor: '#fed7aa', decorOpacity: 30,
            animation: 'slideUp', animationDelay: '0',
        }),
    },

    'problem-sukkari-mufattal': {
        ...node('FeaturesWidget', {
            sectionTitle: 'সারাদিন কাজের পর ক্লান্তি ও দুর্বলতায় ভুগছেন?',
            sectionSubtitle: 'মিষ্টি জাতীয় খাবারের ক্রেভিং মেটাতে চিনির ক্ষতিকর দিক নিয়ে চিন্তিত?',
            titleColor: '#dc2626', subtitleColor: '#431407',
            titleSize: 32, subtitleSize: 18, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fff1f2',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fecdd3', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#fee2e2', iconColor: '#dc2626', iconSize: 'md',
            itemTitleColor: '#431407', itemDescColor: '#7c2d12',
            itemTitleSize: 16, itemDescSize: 15,
            showNumbers: false,
            items: [
                { title: 'দ্রুত এনার্জি লস', description: 'কাজের চাপে শরীর দ্রুত দুর্বল হয়ে পড়ে এবং ইনস্ট্যান্ট এনার্জি পান না।', icon: '❌', iconBg: '', iconColor: '' },
                { title: 'চিনির ক্ষতিকর প্রভাব', description: 'সাধারণ মিষ্টি খাবারে প্রচুর চিনি থাকে যা স্বাস্থ্যের জন্য মারাত্মক ক্ষতিকর।', icon: '❌', iconBg: '', iconColor: '' },
                { title: 'কোষ্ঠকাঠিন্য ও গ্যাস্ট্রিক', description: 'ফাইবার যুক্ত খাবারের অভাবে হজমে সমস্যা ও গ্যাস্ট্রিকের সমস্যা হয়।', icon: '❌', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    'product-sukkari-mufattal': {
        ...node('ProductWidget', {
            layout: 'side-by-side', maxWidth: 1000,
            bgType: 'color', bgColor: '#ffffff',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            imageRatio: '1:1', imageBorderRadius: 20, imageShadow: 'lg',
            showGallery: true,
            showBadge: true, badgeText: 'এনার্জি বুস্টার', badgeBg: '#c2410c', badgeColor: '#ffffff',
            showTitle: true, titleSize: 32, titleWeight: '800', titleColor: '#431407', titleLineHeight: 1.25,
            showPrice: true, priceColor: '#c2410c', priceSize: 42, priceWeight: '900',
            showOriginalPrice: false, currencySymbol: '৳',
            showRating: true, ratingValue: 4.9, reviewCount: 1250, starColor: '#f97316',
            showDescription: true, descriptionSize: 16, descriptionColor: '#7c2d12', descriptionLines: 6,
            descriptionText: 'এনার্জিয়েট খেজুর সুক্কারী খেজুর একটি পুষ্টিসমৃদ্ধ ফল যা শরীরকে শক্তি যোগায়, কোষ্ঠকাঠিন্য দূর করে, কোলেস্টেরল ও রক্তচাপ নিয়ন্ত্রণে সাহায্য করে, এবং হাড়ের স্বাস্থ্য ভালো রাখে।\n\nএটি আয়রন, ফাইবার, পটাশিয়াম এবং অ্যান্টিঅক্সিডেন্ট সমৃদ্ধ, যা রোগ প্রতিরোধ ক্ষমতা বাড়াতে এবং ক্লান্তি দূর করতে সহায়ক।',
            showSpecs: false,
            showTrust: true,
            trustItems: [
                { icon: '💵', text: 'কোয়ালিটি চেক করে পেমেন্ট', bg: '#fff7ed', color: '#ea580c', show: true },
                { icon: '↩️', text: 'পছন্দ না হলে সাথে সাথে রিটার্ন', bg: '#fef2f2', color: '#dc2626', show: true },
            ],
            showStock: false,
            showCta: true,
            ctaText: '🛒 অর্ডার করতে চাই',
            ctaUrl: '#checkout', ctaBg: '#c2410c', ctaTextColor: '#ffffff',
            ctaRadius: 50, ctaSize: 'lg',
            ctaSubText: 'হটলাইন: 01898292795 / 01320777416',
            animation: 'fadeUp',
        }),
    },

    'breakdown-sukkari-mufattal': {
        ...node('FeaturesWidget', {
            sectionTitle: 'সুক্কারী মুফাত্তাল খেজুরের বৈশিষ্ট্য',
            sectionSubtitle: 'কেন এটি অন্যান্য খেজুর থেকে আলাদা?',
            titleColor: '#431407', subtitleColor: '#7c2d12',
            titleSize: 32, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#ffedd5',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fed7aa', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#ffedd5', iconColor: '#c2410c', iconSize: 'xl',
            itemTitleColor: '#431407', itemDescColor: '#7c2d12',
            itemTitleSize: 18, itemDescSize: 14,
            showNumbers: false,
            items: [
                { title: 'সোনালী রঙ ও টেক্সচার', description: 'হালকা সোনালী রঙের এই খেজুরটি কিছুটা ড্রাই হলেও চিবিয়ে খেতে দারুণ মজা।', icon: '✨', iconBg: '', iconColor: '' },
                { title: 'ক্যারামেল স্বাদ', description: 'মুখে দিলে একেবারে ক্যারামেলের মতো চমৎকার মিষ্টি স্বাদ পাওয়া যায়।', icon: '🍯', iconBg: '', iconColor: '' },
                { title: 'দীর্ঘস্থায়ী সংরক্ষণ', description: 'রোতাবের তুলনায় মুফাত্তাল খেজুর স্বাভাবিক তাপমাত্রায় বেশি দিন ভালো থাকে।', icon: '⏳', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    'benefits-sukkari-mufattal': {
        ...node('FeaturesWidget', {
            sectionTitle: 'সুক্কারি খেজুরের উপকারিতা',
            sectionSubtitle: 'পুষ্টিগুণে ভরপুর এই খেজুর কেন প্রতিদিন খাবেন?',
            titleColor: '#431407', subtitleColor: '#7c2d12',
            titleSize: 28, subtitleSize: 16, headerAlign: 'center',
            columns: 3, layout: 'vertical', gap: 20,
            bgType: 'color', bgColor: '#fffcf7',
            paddingTop: 60, paddingBottom: 40, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fed7aa', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#ffedd5', iconColor: '#c2410c', iconSize: 'lg',
            itemTitleColor: '#431407', itemDescColor: '#7c2d12',
            itemTitleSize: 18, itemDescSize: 14,
            showNumbers: false,
            items: [
                { title: 'শক্তি বৃদ্ধি', description: 'প্রাকৃতিক শর্করার উচ্চ পরিমাণ থাকায় এটি দ্রুত শরীরে শক্তি সরবরাহ করে, যা ক্লান্তি দূর করতে সহায়ক।', icon: '⚡', iconBg: '', iconColor: '' },
                { title: 'রোগ প্রতিরোধ ক্ষমতা', description: 'এতে থাকা অ্যান্টিঅক্সিডেন্ট শরীরের রোগ প্রতিরোধ ক্ষমতা বাড়াতে সাহায্য করে।', icon: '🛡️', iconBg: '', iconColor: '' },
                { title: 'হজমে সহায়তা', description: 'খেজুরে থাকা ফাইবার হজম প্রক্রিয়াকে উন্নত করে এবং কোষ্ঠকাঠিন্য দূর করতে সাহায্য করে।', icon: '🌿', iconBg: '', iconColor: '' },
                { title: 'গর্ভাবস্থায় উপকারী', description: 'গর্ভবতী মহিলাদের কোষ্ঠকাঠিন্য ও অন্যান্য গ্যাস্ট্রিক সমস্যা সমাধানে খেজুরের ফাইবার উপকারী হতে পারে।', icon: '🤰', iconBg: '', iconColor: '' },
                { title: 'শর্করার মাত্রা নিয়ন্ত্রণ', description: 'কিছু গবেষণায় দেখা গেছে যে, খেজুর ব্লাড সুগার লেভেল নিয়ন্ত্রণে সহায়ক হতে পারে।', icon: '🩸', iconBg: '', iconColor: '' },
                { title: 'মানসিক চাপ কমায়', description: 'এর অ্যান্টিঅক্সিডেন্ট উপাদান মানসিক চাপ কমাতে সাহায্য করে।', icon: '🧠', iconBg: '', iconColor: '' },
                { title: 'লিভার ও কিডনির সুরক্ষা', description: 'খেজুরে থাকা প্রোঅ্যান্থোসায়ানিডিন লিভার এবং কিডনিকে অক্সিডেটিভ স্ট্রেস থেকে রক্ষা করতে সাহায্য করে।', icon: '🩺', iconBg: '', iconColor: '' },
                { title: 'পেটের রোগের উপশম', description: 'খেজুর পেটের বিভিন্ন রোগ নিরাময়ে উপকারী হতে পারে।', icon: '⚕️', iconBg: '', iconColor: '' },
                { title: 'দাঁতের সুরক্ষা', description: 'এটি দাঁতের ক্ষয় রোধ করতে পারে এবং একটি প্রাকৃতিক মিষ্টি হিসেবেও ব্যবহার করা যায়।', icon: '🦷', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    'why-us-sukkari-mufattal': {
        ...node('FeaturesWidget', {
            sectionTitle: 'আমাদের উপর কেন আস্থা রাখবেন?',
            sectionSubtitle: 'কাস্টমার স্যাটিসফেকশনই আমাদের মূল লক্ষ্য',
            titleColor: '#431407', subtitleColor: '#7c2d12',
            titleSize: 28, subtitleSize: 16, headerAlign: 'center',
            columns: 2, layout: 'horizontal', gap: 20,
            bgType: 'color', bgColor: '#ffedd5',
            paddingTop: 60, paddingBottom: 60, paddingLeft: 24, paddingRight: 24,
            cardBg: '#ffffff', cardBorderColor: '#fed7aa', cardBorderWidth: 1,
            cardRadius: 16, cardShadow: 'sm', cardPadding: 24,
            iconShape: 'circle', iconBg: '#ffedd5', iconColor: '#c2410c', iconSize: 'md',
            itemTitleColor: '#431407', itemDescColor: '#7c2d12',
            itemTitleSize: 16, itemDescSize: 14,
            showNumbers: true,
            items: [
                { title: 'চেক করে পেমেন্ট', description: 'প্রোডাক্ট হাতে পেয়ে, দেখে, কোয়ালিটি চেক করে পেমেন্ট করার সুবিধা।', icon: '🔍', iconBg: '', iconColor: '' },
                { title: 'সহজ রিটার্ন পলিসি', description: 'প্রোডাক্ট পছন্দ না হলে ডেলিভারি ম্যানের কাছে সাথে সাথে রিটার্ন দিতে পারবেন।', icon: '↩️', iconBg: '', iconColor: '' },
                { title: 'হোম ডেলিভারি', description: 'সারা বাংলাদেশে কুরিয়ারের মাধ্যমে দ্রুত হোম ডেলিভারি পাবেন।', icon: '🚚', iconBg: '', iconColor: '' },
                { title: 'সার্বক্ষণিক সাপোর্ট', description: 'যে কোন সময় আমাদের সাথে যোগাযোগ করতে পারবেন। হটলাইন: 01898292795', icon: '📞', iconBg: '', iconColor: '' },
            ],
            animation: 'fadeUp', staggerDelay: '0.08',
        }),
    },

    'faq-sukkari-mufattal': {
        ...node('FaqWidget', {
            title: 'সাধারণ জিজ্ঞাসা (FAQ)',
            subtitle: 'নীচের প্রশ্নগুলো আমরা প্রতিনিয়ত পেয়ে থাকি। আশা করছি এর মধ্যে আপনি আপনার প্রশ্নের উত্তর পেয়ে যাবেন।',
            bgColor: '#ffffff', padding: 60,
            accentColor: '#c2410c', iconStyle: 'plus', layout: 'default',
            questions: [
                { q: 'কিভাবে অর্ডার করবো এবং দাম কতো?', a: 'অর্ডার করতে “অর্ডার করতে চাই” বাটনে ক্লিক করে, আপনার নাম, মোবাইল নাম্বার এবং ডেলিভারি ঠিকানা দিয়ে ফর্মটি সম্পূর্ণ পূরন করুন। আমরা আপনাকে কল করে অর্ডার কনফার্ম করবো। ফোনে অর্ডার করতে কল করুন 01898292795 অথবা 01320777416 নম্বরে। দাম ফর্মের বান্ডেল অংশে দেওয়া আছে।' },
                { q: 'খেজুর ফ্রেশ হবেতো?', a: 'জি ইনশাআল্লাহ, আমরা সরাসরি সৌদি থেকে আমদানি করা নতুন সিজনের ফ্রেশ খেজুর সরবরাহ করে থাকি। প্যাকেট খোলার পর আপনি নিজেই এর ফ্রেশনেস বুঝতে পারবেন।' },
                { q: 'ফ্রেশ সুক্কারী খেজুর কিভাবে চিনবো?', a: 'অরিজিনাল সুক্কারী খেজুরের রঙ হালকা সোনালী বা বাদামী হয়, এর টেক্সচার কিছুটা ড্রাই কিন্তু মুখে দিলে ক্যারামেলের মতো গলে যায় এবং অসাধারণ মিষ্টি স্বাদ থাকে।' },
                { q: 'ডায়াবেটিস রোগী কি খেজুর খেতে পারবে?', a: 'খেজুরে প্রাকৃতিক শর্করা থাকে। ডায়াবেটিস রোগীদের ক্ষেত্রে যেকোনো মিষ্টি ফল খাওয়ার আগে চিকিৎসকের পরামর্শ নেওয়া উত্তম।' },
                { q: 'প্রতিদিন কত পিস খেজুর খাওয়া উচিত?', a: 'সুস্থ মানুষের জন্য প্রতিদিন ৩-৫ টি খেজুর খাওয়া অত্যন্ত উপকারী। তবে এনার্জি লেভেল ও ডায়েট অনুযায়ী এর পরিমাণ কম-বেশি হতে পারে।' },
                { q: 'কিভাবে সংরক্ষণ করব এবং কতদিন ভালো থাকবে?', a: 'স্বাভাবিক তাপমাত্রায় এয়ারটাইট বক্সে রাখলে ১৫-২০ দিন ভালো থাকে। তবে দীর্ঘদিনের জন্য সংরক্ষণ করতে চাইলে নরমাল ফ্রিজে রাখুন, এতে ৩-৬ মাস পর্যন্ত স্বাদ ও মান ঠিক থাকবে।' },
                { q: 'অগ্রীম কোন টাকা দেওয়া লাগে কিনা?', a: 'না, কোনো অগ্রিম পেমেন্ট করতে হবে backward করতে হবে না। প্রোডাক্ট হাতে পেয়ে, চেক করে তারপর ডেলিভারি ম্যানকে টাকা পরিশোধ করবেন।' },
            ],
        }),
    },

    'testimonials-sukkari-mufattal': {
        ...node('TestimonialWidget', {
            title: 'সম্মানিত কাস্টমার রিভিউ',
            subtitle: 'যাঁরা আমাদের সুক্কারী খেজুর কিনেছেন তাঁদের অভিজ্ঞতা',
            bgColor: '#fffcf7', padding: 60,
            layout: 'grid', columns: 2, cardStyle: 'border', borderColor: '#fed7aa',
            starColor: '#f97316', showVerified: true,
            reviews: [
                { name: 'আরিফ হোসেন', role: 'ঢাকা', text: 'অসাধারণ স্বাদ! খেজুরগুলো খুবই ফ্রেশ ছিল। আপনারা চেক করে নেওয়ার যে সুযোগ দিয়েছেন তার জন্যই মূলত অর্ডার করেছিলাম। কোয়ালিটি নিয়ে আমি ১০০% সন্তুষ্ট।', stars: 5, avatar: '' },
                { name: 'মাহমুদুল হাসান', role: 'সিলেট', text: 'সুক্কারী খেজুর আগে অনেক জায়গা থেকে নিয়েছি, কিন্তু আপনাদের খেজুরের সাইজ এবং মিষ্টির পরিমাণ একদম পারফেক্ট। প্যাকেজিং ও ডেলিভারি সার্ভিসও বেশ ভালো ছিল।', stars: 5, avatar: '' },
            ],
        }),
    },

    'countdown-sukkari-mufattal': {
        ...node('CountdownWidget', {
            mode: 'daily',
            showDays: false,
            showHeadline: true,
            headline: '🎁 স্পেশাল ডিসকাউন্ট অফার!',
            headlineSize: 28, headlineColor: '#dc2626', headlineWeight: '800',
            showSubtitle: true,
            subtitle: 'অরিজিনাল সুক্কারী মুফাত্তাল খেজুরের আজকের স্পেশাল অফার।',
            subtitleColor: '#431407', subtitleSize: 18,
            expiredMessage: '⚠️ আজকের অফারটি শেষ হয়েছে।',
            displayStyle: 'card', boxSize: 'md',
            boxBg: '#ffffff', boxTextColor: '#c2410c',
            labelColor: '#7c2d12', boxRadius: 16, separatorColor: '#ffffff', showLabels: true,
            showUrgencyBar: true,
            urgencyText: '📦 স্টক খুবই সীমিত, দ্রুত অর্ডার কনফার্ম করুন।',
            urgencyBarBg: '#fee2e2', urgencyBarText: '#dc2626',
            bgType: 'color', bgColor: '#fffcf7',
            paddingTop: 40, paddingBottom: 40, paddingLeft: 24, paddingRight: 24,
            contentAlign: 'center',
        }),
    },

    'checkout-sukkari-mufattal': {
        ...node('CheckoutWidget', {
            maxWidth: 600, bgColor: '#ffffff', padding: 32, borderRadius: 20,
            shadow: '2xl', borderWidth: 2, borderColor: '#c2410c', 
            showHeader: true, headerText: '🛒 আপনার অর্ডারটি কনফার্ম করতে নিচের ফর্মটি সঠিকভাবে পূরণ করুন।',
            headerBgColor: '#ffedd5', headerTextColor: '#c2410c', headerSize: 20,
            showProductSummary: true, summaryLayout: 'row',
            showRating: true, ratingValue: 4.9, reviewCount: 1250,
            showMultiProduct: false,
            showQuantity: true, showAddress: true, showDistrict: true, showNote: false,
            nameLabel: 'আপনার নাম', phoneLabel: 'মোবাইল নাম্বার',
            addressLabel: 'ডেলিভারি ঠিকানা', districtLabel: 'জেলা নির্বাচন করুন',
            noteLabel: 'বিশেষ নির্দেশ', quantityLabel: 'পরিমাণ নির্বাচন করুন',
            formLayout: 'two-col',
            unitLabel: 'কেজি', presetQuantities: '1, 2, 3, 5', showCustomQty: false, defaultQuantity: 1,
            showBundlePricing: true,
            bundles: [
                { qty: 1, price: 850, highlight: false, badge: '' }, // Dummy price, you can change
                { qty: 2, price: 1600, highlight: true, badge: 'জনপ্রিয়' }, 
                { qty: 5, price: 4000, highlight: false, badge: 'সুপার সেভার' },
            ],
            showDeliveryInfo: true, insideDhakaCharge: 60, outsideDhakaCharge: 120, showDeliveryBreakdown: true,
            showVariants: false,
            buttonText: 'অর্ডার কনফার্ম করুন',
            buttonBgColor: '#c2410c', buttonTextColor: '#ffffff',
            buttonBorderRadius: 50, buttonSize: 'xl', buttonFullWidth: true,
            buttonIcon: '✅', buttonSubText: 'যেকোন প্রয়োজনে কল করুন: 01898292795 অথবা 01320777416',
            showTrustBadges: true,
            trustBadges: [
                { icon: '💵', text: 'ক্যাশ অন ডেলিভারি',   show: true },
                { icon: '🔍', text: 'চেক করে নেওয়ার সুযোগ', show: true },
            ],
            showUrgency: false, 
            showSocialProof: true,
            socialProofText: 'গত ১ ঘণ্টায় অনেকেই অর্ডার কনফার্ম করেছেন',
            socialProofIcon: '🔥',
            enableSpamPrevention: true, spamIntervalMinutes: 30, whatsappNumber: '01898292795',
            showMobileStickyCta: true, 
            mobileStickyText: '🛒 অর্ডার করতে চাই',
            mobileStickyBg: '#ffffff',
            themeColor: '#c2410c',
            labelColor: '#431407', inputBorderColor: '#fed7aa', inputBgColor: '#fffcf7',
        }),
    },
};